-- GÉNÉRÉ par tools/generate_tracker_pack_en.py — ne pas éditer.
AP_ITEMS = {
  [59420000] = {action="toggle", code="bicycle"},
  [59420001] = {action="toggle", code="bicycle"},
  [59420003] = {action="rang_inc"},
  [59420004] = {action="rang_set", n=1},
  [59420005] = {action="rang_set", n=2},
  [59420006] = {action="rang_set", n=3},
  [59420007] = {action="rang_set", n=4},
  [59420008] = {action="rang_set", n=5},
  [59420009] = {action="chapitre_inc"},
  [59420042] = {action="toggle", code="select_a_coin"},
  [59420043] = {action="toggle", code="school_keys"},
  [59420044] = {action="toggle", code="ancient_herb"},
  [59420045] = {action="toggle", code="pro_screwdriver"},
  [59420046] = {action="toggle", code="fishing_rod"},
  [59420047] = {action="toggle", code="rockin_jumpsuit"},
  [59420048] = {action="toggle", code="model_zero"},
  [59420049] = {action="toggle", code="small_fancy_key"},
  [59420050] = {action="toggle", code="large_fancy_key"},
  [59420051] = {action="toggle", code="key_to_apt_c_101"},
  [59420052] = {action="toggle", code="key_to_apt_c_303"},
  [59420053] = {action="toggle", code="key_to_apt_b_301"},
  [59420054] = {action="toggle", code="back_door_key"},
  [59420055] = {action="toggle", code="bug_net"},
  [59420056] = {action="toggle", code="mom_s_directions"},
  [59420057] = {action="toggle", code="gold_card_key"},
  [59420058] = {action="toggle", code="treasure_room_key"},
  [59420059] = {action="toggle", code="key_to_apt_b_204"},
  [59420060] = {action="toggle", code="payn_oil"},
  [59420061] = {action="toggle", code="strange_handle"},
}
AP_LOCATIONS = {
  [59420000] = "@Chapters/Chapters/Chapter 1: The Vanishing Watch",
  [59420001] = "@Chapters/Chapters/Chapter 2: Hi-Tech Hide-and-Seek",
  [59420002] = "@Chapters/Chapters/Chapter 3: School Is Strange",
  [59420003] = "@Chapters/Chapters/Chapter 4: Let's Go to Harrisville!",
  [59420004] = "@Chapters/Chapters/Chapter 5: Wind It Back 60 Years!",
  [59420005] = "@Chapters/Chapters/Chapter 6: Yo-kai Watch Model Zero",
  [59420006] = "@Chapters/Chapters/Chapter 7: The Storm Is Here!",
  [59420007] = "@Chapters/Chapters/Chapter 8: Big Yo-kai Battle",
  [59420008] = "@Chapters/Chapters/Chapter 9: Master Nyada's Trials",
  [59420009] = "@Chapters/Chapters/Chapter 10: Back to Normal!",
  [59420010] = "@Chapters/Chapters/Chapter 11: Old Springdale's in Peril!",
  [59420050] = "@Go for Rank C!/Go for Rank C!/Go for Rank C!",
  [59420051] = "@Go for Rank C!/Go for Rank C!/Go for Rank B!",
  [59420052] = "@Go for Rank C!/Go for Rank C!/Go for Rank A!",
  [59420053] = "@Go for Rank C!/Go for Rank C!/Go for Rank S!",
  [59420054] = "@Go for Rank C!/Go for Rank C!/Rank Up: D",
  [59420055] = "@Go for Rank C!/Go for Rank C!/Rank Up: C",
  [59420056] = "@Go for Rank C!/Go for Rank C!/Rank Up: B",
  [59420057] = "@Go for Rank C!/Go for Rank C!/Rank Up: A",
  [59420058] = "@Go for Rank C!/Go for Rank C!/Rank Up: S",
  [59420100] = "@Boss: Gutsy Bones/Boss: Gutsy Bones/Boss: Gutsy Bones",
  [59420101] = "@Boss: Meganyan/Boss: Meganyan/Boss: Meganyan",
  [59420102] = "@Boss: Cap'n Crash/Boss: Cap'n Crash/Boss: Cap'n Crash",
  [59420103] = "@Boss: Kin/Boss: Kin/Boss: Kin",
  [59420104] = "@Boss: Kin/Boss: Kin/Boss: Gin",
  [59420105] = "@Boss: Eyeclone/Boss: Eyeclone/Boss: Eyeclone",
  [59420106] = "@Boss: Dame Demona/Boss: Dame Demona/Boss: Dame Dedtime",
  [59420107] = "@Boss: Dame Demona/Boss: Dame Demona/Boss: Dame Demona",
  [59420200] = "@Request: A Cicada Professional/Request: A Cicada Professional/Request: A Cicada Professional",
  [59420201] = "@Request: Matt, Don't Give Up!/Request: Matt, Don't Give Up!/Request: Matt, Don't Give Up!",
  [59420202] = "@Request: Customer Attraction!/Request: Customer Attraction!/Request: Customer Attraction!",
  [59420203] = "@Request: The Gates of Whimsy/Request: The Gates of Whimsy/Request: Collection Correction",
  [59420204] = "@Request: Officially Official!/Request: Officially Official!/Request: Officially Official!",
  [59420205] = "@Request: Bam-Boom! Fusing!/Request: Bam-Boom! Fusing!/Request: Bam-Boom! Fusing!",
  [59420206] = "@Request: The Gates of Whimsy/Request: The Gates of Whimsy/Request: The Gates of Whimsy",
  [59420207] = "@Request: Bear Boy: Origins/Request: Bear Boy: Origins/Request: Bear Boy: Origins",
  [59420208] = "@Request: Hangout Havoc/Request: Hangout Havoc/Request: Hangout Havoc",
  [59420209] = "@Request: Matt, Don't Give Up!/Request: Matt, Don't Give Up!/Request: Treasure Hunters Pt. 1",
  [59420210] = "@Request: The Secret Base/Request: The Secret Base/Request: The Secret Base",
  [59420211] = "@Request: Makeover Takeover/Request: Makeover Takeover/Request: Makeover Takeover",
  [59420212] = "@Request: Slicenrice Under Fire/Request: Slicenrice Under Fire/Request: Slicenrice Under Fire",
  [59420213] = "@Request: Springdale Star Pt. 1/Request: Springdale Star Pt. 1/Request: Springdale Star Pt. 1",
  [59420214] = "@Request: Secrets of Soulcery/Request: Secrets of Soulcery/Request: Secrets of Soulcery",
  [59420215] = "@Request: No Time For Fishin'!/Request: No Time For Fishin'!/Request: No Time For Fishin'!",
  [59420216] = "@Request: True Hide-and-Seek/Request: True Hide-and-Seek/Request: True Hide-and-Seek",
  [59420217] = "@Request: Which Beetle's Better/Request: Which Beetle's Better/Request: Which Beetle's Better",
  [59420218] = "@Request: Timers & More's Part/Request: Timers & More's Part/Request: Timers & More's Part",
  [59420219] = "@Request: The Shrine's Part/Request: The Shrine's Part/Request: The Shrine's Part",
  [59420220] = "@Request: The Ironworks' Part/Request: The Ironworks' Part/Request: The Ironworks' Part",
  [59420221] = "@Request: Find Pallysol!/Request: Find Pallysol!/Request: Find Pallysol!",
  [59420222] = "@Request: Find Gnomey!/Request: Find Gnomey!/Request: Find Gnomey!",
  [59420223] = "@Request: Find Predictabull!/Request: Find Predictabull!/Request: Find Predictabull!",
  [59420224] = "@Request: Find Mermaidyn!/Request: Find Mermaidyn!/Request: Find Mermaidyn!",
  [59420225] = "@Request: No Time For Fishin'!/Request: No Time For Fishin'!/Request: Find Faux Kappa!",
  [59420226] = "@Request: The Gates of Whimsy/Request: The Gates of Whimsy/Request: The Final Gate",
  [59420227] = "@Request: Gourmet Grand Prix/Request: Gourmet Grand Prix/Request: Gourmet Grand Prix",
  [59420228] = "@Request: Long Lost Love/Request: Long Lost Love/Request: Long Lost Love",
  [59420229] = "@Request: Your Local Mascot/Request: Your Local Mascot/Request: Your Local Mascot",
  [59420230] = "@Request: Moving Blues/Request: Moving Blues/Request: Moving Blues",
  [59420231] = "@Request: Ghost Club at School/Request: Ghost Club at School/Request: Oden of the Soul Pt. 1",
  [59420232] = "@Request: Ghost Club at School/Request: Ghost Club at School/Request: Oden of the Soul Pt. 2",
  [59420233] = "@Request: Ghost Club at School/Request: Ghost Club at School/Request: Oden of the Soul Pt. 3",
  [59420234] = "@Request: Gone Haunting/Request: Gone Haunting/Request: Gone Haunting",
  [59420235] = "@Request: Inspirited Away/Request: Inspirited Away/Request: Inspirited Away",
  [59420236] = "@Request: Take to the Sea!/Request: Take to the Sea!/Request: Take to the Sea!",
  [59420237] = "@Request: Super Hide-and-Seek/Request: Super Hide-and-Seek/Request: Super Hide-and-Seek",
  [59420238] = "@Request: All Aboard/Request: All Aboard/Request: All Aboard",
  [59420239] = "@Request: Ghost Club at School/Request: Ghost Club at School/Request: Ghost Club at School",
  [59420240] = "@Request: The Price of Iron/Request: The Price of Iron/Request: The Price of Iron",
  [59420241] = "@Request: Bear Boy: Origins/Request: Bear Boy: Origins/Request: The Bear Boy Returns",
  [59420242] = "@Request: Matt, Don't Give Up!/Request: Matt, Don't Give Up!/Request: Treasure Hunters Pt. 2",
  [59420243] = "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Request: Jibanyan's Secret",
  [59420244] = "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Request: Retrace Dad's Steps",
  [59420245] = "@Request: The Heartthrobs/Request: The Heartthrobs/Request: The Heartthrobs",
  [59420246] = "@Request: Too Much Makeover/Request: Too Much Makeover/Request: Too Much Makeover",
  [59420247] = "@Request: A Cicada Professional/Request: A Cicada Professional/Request: King of the Cicadas",
  [59420248] = "@Request: A Steamy Friendship/Request: A Steamy Friendship/Request: A Steamy Friendship",
  [59420249] = "@Request: I Just Wanna Grow Up/Request: I Just Wanna Grow Up/Request: I Just Wanna Grow Up",
  [59420250] = "@Request: C-1 Grand Prix/Request: C-1 Grand Prix/Request: C-1 Grand Prix",
  [59420251] = "@Request: Catchy Fandom/Request: Catchy Fandom/Request: Catchy Fandom",
  [59420252] = "@Request: A Card-Carrying Liar/Request: A Card-Carrying Liar/Request: A Card-Carrying Liar",
  [59420253] = "@Request: Foodie Feuds/Request: Foodie Feuds/Request: Foodie Feuds",
  [59420254] = "@Request: The Gates of Whimsy/Request: The Gates of Whimsy/Request: Time and Toys",
  [59420255] = "@Request: From the Future!/Request: From the Future!/Request: From the Future!",
  [59420256] = "@Request: C-1 Grand Prix A/Request: C-1 Grand Prix A/Request: C-1 Grand Prix A",
  [59420257] = "@Request: The Gates of Whimsy/Request: The Gates of Whimsy/Request: Eerie, Roving Armor",
  [59420258] = "@Request: Ultra Hide-and-Seek/Request: Ultra Hide-and-Seek/Request: Ultra Hide-and-Seek",
  [59420259] = "@Request: Matt, Don't Give Up!/Request: Matt, Don't Give Up!/Request: Treasure Hunters Pt. 3",
  [59420260] = "@Request: Nyada's Trials IV/Request: Nyada's Trials IV/Request: Nyada's Trials IV",
  [59420261] = "@Request: Nyada's Trials V/Request: Nyada's Trials V/Request: Nyada's Trials V",
  [59420262] = "@Request: Nyada's Trials VI/Request: Nyada's Trials VI/Request: Nyada's Trials VI",
  [59420263] = "@Request: Springdale Star Pt. 2/Request: Springdale Star Pt. 2/Request: Springdale Star Pt. 2",
  [59420264] = "@Request: Who's That Girl/Request: Who's That Girl/Request: Who's That Girl",
  [59420265] = "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Request: Dinner on Hold",
  [59420266] = "@Request: The Haunted Hospital/Request: The Haunted Hospital/Request: The Haunted Hospital",
  [59420267] = "@Service: Stuck in the Heat/Service: Stuck in the Heat/Service: Stuck in the Heat",
  [59420268] = "@Service: Running on Empty/Service: Running on Empty/Service: Running on Empty",
  [59420269] = "@Service: A Likely Story/Service: A Likely Story/Service: A Likely Story",
  [59420270] = "@Service: Sweet Satisfaction/Service: Sweet Satisfaction/Service: Sweet Satisfaction",
  [59420271] = "@Service: Overstuffed Head/Service: Overstuffed Head/Service: Overstuffed Head",
  [59420272] = "@Service: School Pranks/Service: School Pranks/Service: School Pranks",
  [59420273] = "@Service: Popular Training/Service: Popular Training/Service: Popular Training",
  [59420274] = "@Service: Bug Hunting/Service: Bug Hunting/Service: Bug Hunting",
  [59420275] = "@Service: Fat Cat's Favor/Service: Fat Cat's Favor/Service: Fat Cat's Favor",
  [59420276] = "@Service: Struck with Love/Service: Struck with Love/Service: Struck with Love",
  [59421000] = "@Uptown Springdale - Chest 01/Uptown Springdale - Chest 01/Uptown Springdale - Chest 01",
  [59421001] = "@Uptown Springdale - Chest 02/Uptown Springdale - Chest 02/Uptown Springdale - Chest 02",
  [59421002] = "@Uptown Springdale - Chest 03/Uptown Springdale - Chest 03/Uptown Springdale - Chest 03",
  [59421003] = "@Uptown Springdale - Chest 04/Uptown Springdale - Chest 04/Uptown Springdale - Chest 04",
  [59421004] = "@Uptown Springdale - Chest 05/Uptown Springdale - Chest 05/Uptown Springdale - Chest 05",
  [59421005] = "@Uptown Springdale - Chest 06/Uptown Springdale - Chest 06/Uptown Springdale - Chest 06",
  [59421006] = "@Uptown Springdale - Chest 07/Uptown Springdale - Chest 07/Uptown Springdale - Chest 07",
  [59421007] = "@Uptown Springdale - Chest 08/Uptown Springdale - Chest 08/Uptown Springdale - Chest 08",
  [59421008] = "@Uptown Springdale - Chest 09/Uptown Springdale - Chest 09/Uptown Springdale - Chest 09",
  [59421009] = "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Uptown Springdale - Chest 10",
  [59421010] = "@Uptown Springdale (The Catwalk) - Chest 01/Uptown Springdale (The Catwalk) - Chest 01/Uptown Springdale (The Catwalk) - Chest 01",
  [59421011] = "@Harrisville (Facing Rocks) - Chest 01/Harrisville (Facing Rocks) - Chest 01/Harrisville (Facing Rocks) - Chest 01",
  [59421012] = "@Harrisville (Facing Rocks) - Chest 02/Harrisville (Facing Rocks) - Chest 02/Harrisville (Facing Rocks) - Chest 02",
  [59421013] = "@Harrisville (Facing Rocks) - Chest 03/Harrisville (Facing Rocks) - Chest 03/Harrisville (Facing Rocks) - Chest 03",
  [59421014] = "@Harrisville (Cicada Canyon) - Chest 01/Harrisville (Cicada Canyon) - Chest 01/Harrisville (Cicada Canyon) - Chest 01",
  [59421015] = "@Harrisville (Cicada Canyon) - Chest 02/Harrisville (Cicada Canyon) - Chest 02/Harrisville (Cicada Canyon) - Chest 02",
  [59421016] = "@Harrisville (Cicada Canyon) - Chest 03/Harrisville (Cicada Canyon) - Chest 03/Harrisville (Cicada Canyon) - Chest 03",
  [59421017] = "@Harrisville - Chest 01/Harrisville - Chest 01/Harrisville - Chest 01",
  [59421018] = "@Harrisville - Chest 02/Harrisville - Chest 02/Harrisville - Chest 02",
  [59421019] = "@Harrisville - Chest 03/Harrisville - Chest 03/Harrisville - Chest 03",
  [59421020] = "@Harrisville - Chest 04/Harrisville - Chest 04/Harrisville - Chest 04",
  [59421021] = "@Harrisville - Chest 05/Harrisville - Chest 05/Harrisville - Chest 05",
  [59421022] = "@Harrisville - Chest 06/Harrisville - Chest 06/Harrisville - Chest 06",
  [59421023] = "@Harrisville - Chest 07/Harrisville - Chest 07/Harrisville - Chest 07",
  [59421024] = "@Harrisville - Chest 08/Harrisville - Chest 08/Harrisville - Chest 08",
  [59421025] = "@Harrisville - Chest 09/Harrisville - Chest 09/Harrisville - Chest 09",
  [59421026] = "@Harrisville - Chest 10/Harrisville - Chest 10/Harrisville - Chest 10",
  [59421027] = "@Harrisville - Chest 11/Harrisville - Chest 11/Harrisville - Chest 11",
  [59421028] = "@Harrisville - Chest 12/Harrisville - Chest 12/Harrisville - Chest 12",
  [59421029] = "@Downtown Springdale - Chest 01/Downtown Springdale - Chest 01/Downtown Springdale - Chest 01",
  [59421030] = "@Downtown Springdale - Chest 02/Downtown Springdale - Chest 02/Downtown Springdale - Chest 02",
  [59421031] = "@Downtown Springdale - Chest 03/Downtown Springdale - Chest 03/Downtown Springdale - Chest 03",
  [59421032] = "@Downtown Springdale - Chest 04/Downtown Springdale - Chest 04/Downtown Springdale - Chest 04",
  [59421033] = "@Downtown Springdale - Chest 05/Downtown Springdale - Chest 05/Downtown Springdale - Chest 05",
  [59421034] = "@Downtown Springdale - Chest 06/Downtown Springdale - Chest 06/Downtown Springdale - Chest 06",
  [59421035] = "@Downtown Springdale - Chest 07/Downtown Springdale - Chest 07/Downtown Springdale - Chest 07",
  [59421036] = "@Downtown Springdale - Chest 08/Downtown Springdale - Chest 08/Downtown Springdale - Chest 08",
  [59421037] = "@Breezy Hills - Chest 01/Breezy Hills - Chest 01/Breezy Hills - Chest 01",
  [59421038] = "@Breezy Hills - Chest 02/Breezy Hills - Chest 02/Breezy Hills - Chest 02",
  [59421039] = "@Breezy Hills - Chest 03/Breezy Hills - Chest 03/Breezy Hills - Chest 03",
  [59421040] = "@Breezy Hills - Chest 04/Breezy Hills - Chest 04/Breezy Hills - Chest 04",
  [59421041] = "@Breezy Hills - Chest 05/Breezy Hills - Chest 05/Breezy Hills - Chest 05",
  [59421042] = "@Breezy Hills - Chest 06/Breezy Hills - Chest 06/Breezy Hills - Chest 06",
  [59421043] = "@Underground Waterway - Chest 01/Underground Waterway - Chest 01/Underground Waterway - Chest 01",
  [59421044] = "@Underground Waterway - Chest 02/Underground Waterway - Chest 02/Underground Waterway - Chest 02",
  [59421045] = "@Underground Waterway - Chest 03/Underground Waterway - Chest 03/Underground Waterway - Chest 03",
  [59421046] = "@Underground Waterway - Chest 04/Underground Waterway - Chest 04/Underground Waterway - Chest 04",
  [59421047] = "@Underground Waterway - Chest 05/Underground Waterway - Chest 05/Underground Waterway - Chest 05",
  [59421048] = "@Underground Waterway - Chest 06/Underground Waterway - Chest 06/Underground Waterway - Chest 06",
  [59421049] = "@Underground Waterway - Chest 07/Underground Waterway - Chest 07/Underground Waterway - Chest 07",
  [59421050] = "@Underground Waterway - Chest 08/Underground Waterway - Chest 08/Underground Waterway - Chest 08",
  [59421051] = "@Underground Waterway - Chest 09/Underground Waterway - Chest 09/Underground Waterway - Chest 09",
  [59421052] = "@Underground Waterway - Chest 10/Underground Waterway - Chest 10/Underground Waterway - Chest 10",
  [59421053] = "@Underground Waterway - Chest 11/Underground Waterway - Chest 11/Underground Waterway - Chest 11",
  [59421054] = "@Underground Waterway - Chest 12/Underground Waterway - Chest 12/Underground Waterway - Chest 12",
  [59421055] = "@Underground Waterway - Chest 13/Underground Waterway - Chest 13/Underground Waterway - Chest 13",
  [59421056] = "@Desolate Lane - Chest 01/Desolate Lane - Chest 01/Desolate Lane - Chest 01",
  [59421057] = "@Hidden Side Street - Chest 01/Hidden Side Street - Chest 01/Hidden Side Street - Chest 01",
  [59421058] = "@Hidden Side Street - Chest 01/Hidden Side Street - Chest 01/Lonely Waterway - Chest 01",
  [59421059] = "@Hidden Side Street - Chest 01/Hidden Side Street - Chest 01/Lonely Waterway - Chest 02",
  [59421060] = "@Breezy Hills (Stone House) - Chest 01/Breezy Hills (Stone House) - Chest 01/Breezy Hills (Stone House) - Chest 01",
  [59421061] = "@Breezy Hills (Jumbo Slider) - Chest 01/Breezy Hills (Jumbo Slider) - Chest 01/Breezy Hills (Jumbo Slider) - Chest 01",
  [59421062] = "@Breezy Hills (Jumbo Slider) - Chest 02/Breezy Hills (Jumbo Slider) - Chest 02/Breezy Hills (Jumbo Slider) - Chest 02",
  [59421063] = "@Breezy Hills (Jumbo Slider) - Chest 03/Breezy Hills (Jumbo Slider) - Chest 03/Breezy Hills (Jumbo Slider) - Chest 03",
  [59421064] = "@Breezy Hills (Gourd Pond Museum) - Chest 01/Breezy Hills (Gourd Pond Museum) - Chest 01/Breezy Hills (Gourd Pond Museum) - Chest 01",
  [59421065] = "@Breezy Hills (Gourd Pond Museum) - Chest 02/Breezy Hills (Gourd Pond Museum) - Chest 02/Breezy Hills (Gourd Pond Museum) - Chest 02",
  [59421066] = "@Breezy Hills (Gourd Pond Museum) - Chest 03/Breezy Hills (Gourd Pond Museum) - Chest 03/Breezy Hills (Gourd Pond Museum) - Chest 03",
  [59421067] = "@Breezy Hills (Gourd Pond Museum) - Chest 04/Breezy Hills (Gourd Pond Museum) - Chest 04/Breezy Hills (Gourd Pond Museum) - Chest 04",
  [59421068] = "@Breezy Hills (Gourd Pond Museum) - Chest 05/Breezy Hills (Gourd Pond Museum) - Chest 05/Breezy Hills (Gourd Pond Museum) - Chest 05",
  [59421069] = "@Breezy Hills (Gourd Pond Museum) - Chest 06/Breezy Hills (Gourd Pond Museum) - Chest 06/Breezy Hills (Gourd Pond Museum) - Chest 06",
  [59421070] = "@Breezy Hills (Gourd Pond Museum) - Chest 07/Breezy Hills (Gourd Pond Museum) - Chest 07/Breezy Hills (Gourd Pond Museum) - Chest 07",
  [59421071] = "@Breezy Hills (Gourd Pond Museum) - Chest 08/Breezy Hills (Gourd Pond Museum) - Chest 08/Breezy Hills (Gourd Pond Museum) - Chest 08",
  [59421072] = "@Abandoned Tunnel (Treasure Room) - Chest 01/Abandoned Tunnel (Treasure Room) - Chest 01/Abandoned Tunnel (Treasure Room) - Chest 01",
  [59421073] = "@Abandoned Tunnel (Treasure Room) - Chest 02/Abandoned Tunnel (Treasure Room) - Chest 02/Abandoned Tunnel (Treasure Room) - Chest 02",
  [59421074] = "@Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 03",
  [59421075] = "@Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 04",
  [59421076] = "@Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 05",
  [59421077] = "@Abandoned Tunnel (Treasure Room) - Chest 06/Abandoned Tunnel (Treasure Room) - Chest 06/Abandoned Tunnel (Treasure Room) - Chest 06",
  [59421078] = "@Abandoned Tunnel (Treasure Room) - Chest 07/Abandoned Tunnel (Treasure Room) - Chest 07/Abandoned Tunnel (Treasure Room) - Chest 07",
  [59421079] = "@Abandoned Tunnel (Treasure Room) - Chest 08/Abandoned Tunnel (Treasure Room) - Chest 08/Abandoned Tunnel (Treasure Room) - Chest 08",
  [59421080] = "@Abandoned Tunnel East - Chest 01/Abandoned Tunnel East - Chest 01/Abandoned Tunnel East - Chest 01",
  [59421081] = "@Abandoned Tunnel East - Chest 02/Abandoned Tunnel East - Chest 02/Abandoned Tunnel East - Chest 02",
  [59421082] = "@Abandoned Tunnel East - Chest 03/Abandoned Tunnel East - Chest 03/Abandoned Tunnel East - Chest 03",
  [59421083] = "@Abandoned Tunnel East - Chest 04/Abandoned Tunnel East - Chest 04/Abandoned Tunnel East - Chest 04",
  [59421084] = "@Abandoned Tunnel East - Chest 05/Abandoned Tunnel East - Chest 05/Abandoned Tunnel East - Chest 05",
  [59421085] = "@Abandoned Tunnel East - Chest 06/Abandoned Tunnel East - Chest 06/Abandoned Tunnel East - Chest 06",
  [59421086] = "@Mt. Wildwood - Summit - Chest 01/Mt. Wildwood - Summit - Chest 01/Mt. Wildwood - Summit - Chest 01",
  [59421087] = "@Mountain Path - Chest 01/Mountain Path - Chest 01/Mountain Path - Chest 01",
  [59421088] = "@Mt. Wildwood - Chest 01/Mt. Wildwood - Chest 01/Mt. Wildwood - Chest 01",
  [59421089] = "@Mt. Wildwood (Waterway Access) - Chest 01/Mt. Wildwood (Waterway Access) - Chest 01/Mt. Wildwood (Waterway Access) - Chest 01",
  [59421090] = "@Mt. Wildwood (Waterway Access) - Chest 01/Mt. Wildwood (Waterway Access) - Chest 01/Mt. Wildwood (Waterway Access) - Chest 02",
  [59421091] = "@Springdale Elementary School (night) - Chest 01/Springdale Elementary School (night) - Chest 01/Springdale Elementary School (night) - Chest 01",
  [59421092] = "@Springdale Elementary School (night) - Chest 02/Springdale Elementary School (night) - Chest 02/Springdale Elementary School (night) - Chest 02",
  [59421093] = "@Springdale Elementary School (night) - Chest 03/Springdale Elementary School (night) - Chest 03/Springdale Elementary School (night) - Chest 03",
  [59421094] = "@Springdale Elementary School (night) - Chest 04/Springdale Elementary School (night) - Chest 04/Springdale Elementary School (night) - Chest 04",
  [59421095] = "@Springdale Elementary School (night) - Chest 05/Springdale Elementary School (night) - Chest 05/Springdale Elementary School (night) - Chest 05",
  [59421096] = "@Springdale Elementary School (night) - Chest 06/Springdale Elementary School (night) - Chest 06/Springdale Elementary School (night) - Chest 06",
  [59421097] = "@Springdale Elementary School (night) - Chest 07/Springdale Elementary School (night) - Chest 07/Springdale Elementary School (night) - Chest 07",
  [59421098] = "@Springdale Elementary School (night) - Chest 08/Springdale Elementary School (night) - Chest 08/Springdale Elementary School (night) - Chest 08",
  [59421099] = "@Springdale Elementary School (night) - Chest 09/Springdale Elementary School (night) - Chest 09/Springdale Elementary School (night) - Chest 09",
  [59421100] = "@Springdale Elementary School (night) - Chest 10/Springdale Elementary School (night) - Chest 10/Springdale Elementary School (night) - Chest 10",
  [59421101] = "@Springdale Elementary School (night) - Chest 11/Springdale Elementary School (night) - Chest 11/Springdale Elementary School (night) - Chest 11",
  [59421102] = "@Springdale Elementary School (night) - Chest 12/Springdale Elementary School (night) - Chest 12/Springdale Elementary School (night) - Chest 12",
  [59421103] = "@Springdale Elementary School (night) - Chest 13/Springdale Elementary School (night) - Chest 13/Springdale Elementary School (night) - Chest 13",
  [59421104] = "@Blossom Heights - Chest 01/Blossom Heights - Chest 01/Blossom Heights - Chest 01",
  [59421105] = "@Blossom Heights - Chest 02/Blossom Heights - Chest 02/Blossom Heights - Chest 02",
  [59421106] = "@Blossom Heights - Chest 03/Blossom Heights - Chest 03/Blossom Heights - Chest 03",
  [59421107] = "@Blossom Heights - Chest 04/Blossom Heights - Chest 04/Blossom Heights - Chest 04",
  [59421108] = "@Blossom Heights - Chest 05/Blossom Heights - Chest 05/Blossom Heights - Chest 05",
  [59421109] = "@Blossom Heights - Chest 06/Blossom Heights - Chest 06/Blossom Heights - Chest 06",
  [59421110] = "@Blossom Heights - Chest 07/Blossom Heights - Chest 07/Blossom Heights - Chest 07",
  [59421111] = "@Springdale (Shopper's Row) - Chest 01/Springdale (Shopper's Row) - Chest 01/Springdale (Shopper's Row) - Chest 01",
  [59421112] = "@Springdale (Shopper's Row) - Chest 02/Springdale (Shopper's Row) - Chest 02/Springdale (Shopper's Row) - Chest 02",
  [59421113] = "@Springdale (Shopper's Row) - Chest 03/Springdale (Shopper's Row) - Chest 03/Springdale (Shopper's Row) - Chest 03",
  [59421114] = "@Springdale (Shopper's Row) - Chest 04/Springdale (Shopper's Row) - Chest 04/Springdale (Shopper's Row) - Chest 04",
  [59421115] = "@Springdale (Shopper's Row) - Chest 05/Springdale (Shopper's Row) - Chest 05/Springdale (Shopper's Row) - Chest 05",
  [59421116] = "@Springdale (Shopper's Row) - Chest 06/Springdale (Shopper's Row) - Chest 06/Springdale (Shopper's Row) - Chest 06",
  [59421117] = "@Downtown Springdale (sub-area) - Chest 01/Downtown Springdale (sub-area) - Chest 01/Downtown Springdale (sub-area) - Chest 01",
  [59421118] = "@Old Mansion (Blossom Heights) - Chest 01/Old Mansion (Blossom Heights) - Chest 01/Old Mansion (Blossom Heights) - Chest 01",
  [59421119] = "@Old Mansion (Blossom Heights) - Chest 02/Old Mansion (Blossom Heights) - Chest 02/Old Mansion (Blossom Heights) - Chest 02",
  [59421120] = "@Old Mansion (Blossom Heights) - Chest 03/Old Mansion (Blossom Heights) - Chest 03/Old Mansion (Blossom Heights) - Chest 03",
  [59421121] = "@Old Mansion (Blossom Heights) - Chest 04/Old Mansion (Blossom Heights) - Chest 04/Old Mansion (Blossom Heights) - Chest 04",
  [59421122] = "@Old Mansion (Blossom Heights) - Chest 05/Old Mansion (Blossom Heights) - Chest 05/Old Mansion (Blossom Heights) - Chest 05",
  [59421123] = "@Old Mansion (Blossom Heights) - Chest 06/Old Mansion (Blossom Heights) - Chest 06/Old Mansion (Blossom Heights) - Chest 06",
  [59421124] = "@Old Mansion (Back) (Blossom Heights) - Chest 01/Old Mansion (Back) (Blossom Heights) - Chest 01/Old Mansion (Back) (Blossom Heights) - Chest 01",
  [59421125] = "@Old Mansion (Back) (Blossom Heights) - Chest 02/Old Mansion (Back) (Blossom Heights) - Chest 02/Old Mansion (Back) (Blossom Heights) - Chest 02",
  [59421126] = "@Old Mansion (Back) (Blossom Heights) - Chest 03/Old Mansion (Back) (Blossom Heights) - Chest 03/Old Mansion (Back) (Blossom Heights) - Chest 03",
  [59421127] = "@Old Mansion (Back) (Blossom Heights) - Chest 04/Old Mansion (Back) (Blossom Heights) - Chest 04/Old Mansion (Back) (Blossom Heights) - Chest 04",
  [59421128] = "@Old Mansion (Back) (Blossom Heights) - Chest 05/Old Mansion (Back) (Blossom Heights) - Chest 05/Old Mansion (Back) (Blossom Heights) - Chest 05",
  [59421129] = "@Excellent Tower - Chest 01/Excellent Tower - Chest 01/Excellent Tower - Chest 01",
  [59421130] = "@Excellent Tower - Chest 02/Excellent Tower - Chest 02/Excellent Tower - Chest 02",
  [59421131] = "@Excellent Tower - Chest 03/Excellent Tower - Chest 03/Excellent Tower - Chest 03",
  [59421132] = "@Excellent Tower - Chest 04/Excellent Tower - Chest 04/Excellent Tower - Chest 04",
  [59421133] = "@Excellent Tower - Chest 05/Excellent Tower - Chest 05/Excellent Tower - Chest 05",
  [59421134] = "@Excellent Tower - Chest 05/Excellent Tower - Chest 05/Excellent Tower - Chest 06",
  [59421135] = "@Harrisville Station Plaza - Chest 01/Harrisville Station Plaza - Chest 01/Harrisville Station Plaza - Chest 01",
  [59421136] = "@Harrisville Station Plaza - Chest 02/Harrisville Station Plaza - Chest 02/Harrisville Station Plaza - Chest 02",
  [59421137] = "@Harrisville Station Plaza - Chest 03/Harrisville Station Plaza - Chest 03/Harrisville Station Plaza - Chest 03",
  [59421138] = "@Harrisville Station Plaza - Chest 04/Harrisville Station Plaza - Chest 04/Harrisville Station Plaza - Chest 04",
  [59421139] = "@Harrisville Station Plaza - Chest 05/Harrisville Station Plaza - Chest 05/Harrisville Station Plaza - Chest 05",
  [59421140] = "@Mt. Middleton (present) - Chest 01/Mt. Middleton (present) - Chest 01/Mt. Middleton (present) - Chest 01",
  [59421141] = "@San Fantastico - Chest 01/San Fantastico - Chest 01/San Fantastico - Chest 01",
  [59421142] = "@San Fantastico - Chest 02/San Fantastico - Chest 02/San Fantastico - Chest 02",
  [59421143] = "@San Fantastico - Chest 03/San Fantastico - Chest 03/San Fantastico - Chest 03",
  [59421144] = "@San Fantastico - Chest 04/San Fantastico - Chest 04/San Fantastico - Chest 04",
  [59421145] = "@San Fantastico - Chest 05/San Fantastico - Chest 05/San Fantastico - Chest 05",
  [59421146] = "@San Fantastico - Chest 06/San Fantastico - Chest 06/San Fantastico - Chest 06",
  [59421147] = "@San Fantastico - Chest 07/San Fantastico - Chest 07/San Fantastico - Chest 07",
  [59421148] = "@San Fantastico - Chest 08/San Fantastico - Chest 08/San Fantastico - Chest 08",
  [59421149] = "@San Fantastico - Chest 09/San Fantastico - Chest 09/San Fantastico - Chest 09",
  [59421150] = "@San Fantastico - Chest 10/San Fantastico - Chest 10/San Fantastico - Chest 10",
  [59421151] = "@San Fantastico - Chest 11/San Fantastico - Chest 11/San Fantastico - Chest 11",
  [59421152] = "@San Fantastico - Chest 12/San Fantastico - Chest 12/San Fantastico - Chest 12",
  [59421153] = "@San Fantastico - Chest 13/San Fantastico - Chest 13/San Fantastico - Chest 13",
  [59421154] = "@San Fantastico - Chest 14/San Fantastico - Chest 14/San Fantastico - Chest 14",
  [59421155] = "@San Fantastico - Chest 15/San Fantastico - Chest 15/San Fantastico - Chest 15",
  [59421156] = "@San Fantastico - Chest 16/San Fantastico - Chest 16/San Fantastico - Chest 16",
  [59421157] = "@San Fantastico (Rank C) - Chest 01/San Fantastico (Rank C) - Chest 01/San Fantastico (Rank C) - Chest 01",
  [59421158] = "@Springdale Business Tower (3rd Floor) - Chest 01/Springdale Business Tower (3rd Floor) - Chest 01/Springdale Business Tower (3rd Floor) - Chest 01",
  [59421159] = "@Springdale Business Tower (3rd Floor) - Chest 02/Springdale Business Tower (3rd Floor) - Chest 02/Springdale Business Tower (3rd Floor) - Chest 02",
  [59421160] = "@Springdale Business Tower (3rd Floor) - Chest 03/Springdale Business Tower (3rd Floor) - Chest 03/Springdale Business Tower (3rd Floor) - Chest 03",
  [59421161] = "@Springdale Business Tower (3rd Floor, Rank A) - Chest 01/Springdale Business Tower (3rd Floor, Rank A) - Chest 01/Springdale Business Tower (3rd Floor, Rank A) - Chest 01",
  [59421162] = "@Springdale Business Tower (12th Floor) - Chest 01/Springdale Business Tower (12th Floor) - Chest 01/Springdale Business Tower (12th Floor) - Chest 01",
  [59421163] = "@Springdale Business Tower (12th Floor) - Chest 02/Springdale Business Tower (12th Floor) - Chest 02/Springdale Business Tower (12th Floor) - Chest 02",
  [59421164] = "@Springdale Business Tower (12th Floor) - Chest 03/Springdale Business Tower (12th Floor) - Chest 03/Springdale Business Tower (12th Floor) - Chest 03",
  [59421165] = "@Shopper's Row (Apt. C-303) - Chest 01/Shopper's Row (Apt. C-303) - Chest 01/Shopper's Row (Apt. C-303) - Chest 01",
  [59421166] = "@Seaside Cave - Chest 01/Seaside Cave - Chest 01/Seaside Cave - Chest 01",
  [59421167] = "@Seaside Cave - Chest 02/Seaside Cave - Chest 02/Seaside Cave - Chest 02",
  [59421168] = "@Seaside Cave - Chest 03/Seaside Cave - Chest 03/Seaside Cave - Chest 03",
  [59421169] = "@Seaside Cave - Chest 04/Seaside Cave - Chest 04/Seaside Cave - Chest 04",
  [59421170] = "@Seaside Cave - Chest 05/Seaside Cave - Chest 05/Seaside Cave - Chest 05",
  [59421171] = "@Seaside Cave - Chest 06/Seaside Cave - Chest 06/Seaside Cave - Chest 06",
  [59421172] = "@Seaside Cave - Chest 07/Seaside Cave - Chest 07/Seaside Cave - Chest 07",
  [59421173] = "@Seaside Cave - Chest 08/Seaside Cave - Chest 08/Seaside Cave - Chest 08",
  [59421174] = "@Seaside Cave - Chest 09/Seaside Cave - Chest 09/Seaside Cave - Chest 09",
  [59421175] = "@Blossom Heights (present) - Chest 01/Blossom Heights (present) - Chest 01/Blossom Heights (present) - Chest 01",
  [59421176] = "@Blossom Heights (Rank C) - Chest 01/Blossom Heights (Rank C) - Chest 01/Blossom Heights (Rank C) - Chest 01",
  [59421177] = "@Blossom Heights (present) - Chest 01/Blossom Heights (present) - Chest 01/Blossom Heights (Rank C) - Chest 02",
  [59421178] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01",
  [59421179] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 02",
  [59421180] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 03",
  [59421181] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 04",
  [59421182] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 05",
  [59421183] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 06",
  [59421184] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 07",
  [59421185] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 08",
  [59421186] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 09",
  [59421187] = "@Old Uptown Springdale - Chest 01/Old Uptown Springdale - Chest 01/Old Uptown Springdale - Chest 01",
  [59421188] = "@Old Uptown Springdale - Chest 02/Old Uptown Springdale - Chest 02/Old Uptown Springdale - Chest 02",
  [59421189] = "@Old Uptown Springdale - Chest 03/Old Uptown Springdale - Chest 03/Old Uptown Springdale - Chest 03",
  [59421190] = "@Old Uptown Springdale - Chest 04/Old Uptown Springdale - Chest 04/Old Uptown Springdale - Chest 04",
  [59421191] = "@Old Uptown Springdale - Chest 05/Old Uptown Springdale - Chest 05/Old Uptown Springdale - Chest 05",
  [59421192] = "@Old Uptown Springdale (Ch.10 return) - Chest 01/Old Uptown Springdale (Ch.10 return) - Chest 01/Old Uptown Springdale (Ch.10 return) - Chest 01",
  [59421193] = "@Old Blossom Heights - Chest 01/Old Blossom Heights - Chest 01/Old Blossom Heights - Chest 01",
  [59421194] = "@Old Blossom Heights - Chest 02/Old Blossom Heights - Chest 02/Old Blossom Heights - Chest 02",
  [59421195] = "@Old Blossom Heights - Chest 03/Old Blossom Heights - Chest 03/Old Blossom Heights - Chest 03",
  [59421196] = "@Old Blossom Heights - Chest 04/Old Blossom Heights - Chest 04/Old Blossom Heights - Chest 04",
  [59421197] = "@Fox Shrine Road - Chest 01/Fox Shrine Road - Chest 01/Fox Shrine Road - Chest 01",
  [59421198] = "@Well Road - Chest 01/Well Road - Chest 01/Well Road - Chest 01",
  [59421199] = "@Springdale Ironworks - Chest 01/Springdale Ironworks - Chest 01/Springdale Ironworks - Chest 01",
  [59421200] = "@Springdale Ironworks - Chest 02/Springdale Ironworks - Chest 02/Springdale Ironworks - Chest 02",
  [59421201] = "@Old Mt. Wildwood - Chest 01/Old Mt. Wildwood - Chest 01/Old Mt. Wildwood - Chest 01",
  [59421202] = "@Gourd Pond (past) - Chest 01/Gourd Pond (past) - Chest 01/Gourd Pond (past) - Chest 01",
  [59421203] = "@Old Harrisville - Chest 01/Old Harrisville - Chest 01/Old Harrisville - Chest 01",
  [59421204] = "@Old Harrisville - Chest 02/Old Harrisville - Chest 02/Old Harrisville - Chest 02",
  [59421205] = "@Old Harrisville - Chest 03/Old Harrisville - Chest 03/Old Harrisville - Chest 03",
  [59421206] = "@Old Harrisville - Chest 04/Old Harrisville - Chest 04/Old Harrisville - Chest 04",
  [59421207] = "@Old Harrisville - Chest 05/Old Harrisville - Chest 05/Old Harrisville - Chest 05",
  [59421208] = "@Old Harrisville - Chest 06/Old Harrisville - Chest 06/Old Harrisville - Chest 06",
  [59421209] = "@Old Harrisville - Chest 07/Old Harrisville - Chest 07/Old Harrisville - Chest 07",
  [59421210] = "@Old Harrisville - Chest 08/Old Harrisville - Chest 08/Old Harrisville - Chest 08",
  [59421211] = "@Old Harrisville - Chest 09/Old Harrisville - Chest 09/Old Harrisville - Chest 09",
  [59421212] = "@Old Harrisville - Chest 10/Old Harrisville - Chest 10/Old Harrisville - Chest 10",
  [59421213] = "@Old Mt. Middleton - Chest 01/Old Mt. Middleton - Chest 01/Old Mt. Middleton - Chest 01",
  [59421214] = "@Old Mt. Middleton - Chest 02/Old Mt. Middleton - Chest 02/Old Mt. Middleton - Chest 02",
  [59421215] = "@Old Mt. Middleton - Chest 03/Old Mt. Middleton - Chest 03/Old Mt. Middleton - Chest 03",
  [59421216] = "@Old Mt. Middleton - Chest 04/Old Mt. Middleton - Chest 04/Old Mt. Middleton - Chest 04",
  [59421217] = "@Old Mt. Middleton - Chest 05/Old Mt. Middleton - Chest 05/Old Mt. Middleton - Chest 05",
  [59421218] = "@Blossom Heights (Rank B) - Chest 01/Blossom Heights (Rank B) - Chest 01/Blossom Heights (Rank B) - Chest 01",
  [59421219] = "@Flatpot Plains - Chest 01/Flatpot Plains - Chest 01/Flatpot Plains - Chest 01",
  [59421220] = "@Flatpot Plains - Chest 02/Flatpot Plains - Chest 02/Flatpot Plains - Chest 02",
  [59421221] = "@Flatpot Plains - Chest 02/Flatpot Plains - Chest 02/Flatpot Plains - Chest 03",
  [59421222] = "@Flatpot Plains - Chest 04/Flatpot Plains - Chest 04/Flatpot Plains - Chest 04",
  [59421223] = "@Flatpot Plains - Chest 05/Flatpot Plains - Chest 05/Flatpot Plains - Chest 05",
  [59421224] = "@Flatpot Plains - Chest 06/Flatpot Plains - Chest 06/Flatpot Plains - Chest 06",
  [59421225] = "@Flatpot Plains - Chest 07/Flatpot Plains - Chest 07/Flatpot Plains - Chest 07",
  [59421226] = "@Flatpot Plains - Chest 08/Flatpot Plains - Chest 08/Flatpot Plains - Chest 08",
  [59421227] = "@Flatpot Plains - Chest 09/Flatpot Plains - Chest 09/Flatpot Plains - Chest 09",
  [59421228] = "@Flatpot Plains - Chest 10/Flatpot Plains - Chest 10/Flatpot Plains - Chest 10",
  [59421229] = "@Flatpot Plains - Chest 11/Flatpot Plains - Chest 11/Flatpot Plains - Chest 11",
  [59421230] = "@Gate Room - Chest 01/Gate Room - Chest 01/Gate Room - Chest 01",
  [59421231] = "@Gate Room - Chest 02/Gate Room - Chest 02/Gate Room - Chest 02",
  [59421232] = "@Gate Room - Chest 03/Gate Room - Chest 03/Gate Room - Chest 03",
  [59421233] = "@Gate Room - Chest 04/Gate Room - Chest 04/Gate Room - Chest 04",
  [59421234] = "@Gate Room - Chest 05/Gate Room - Chest 05/Gate Room - Chest 05",
  [59421235] = "@Gate Room - Chest 06/Gate Room - Chest 06/Gate Room - Chest 06",
  [59421236] = "@Gate Room - Chest 07/Gate Room - Chest 07/Gate Room - Chest 07",
  [59421237] = "@Gate Room - Chest 08/Gate Room - Chest 08/Gate Room - Chest 08",
  [59421238] = "@Gate Room - Chest 09/Gate Room - Chest 09/Gate Room - Chest 09",
  [59421239] = "@Gate Room - Chest 10/Gate Room - Chest 10/Gate Room - Chest 10",
  [59422300] = "@Baffle Board #01: Hungramps/Baffle Board #01: Hungramps/Baffle Board #01: Hungramps",
  [59422301] = "@Baffle Board #02: Blazion/Baffle Board #02: Blazion/Baffle Board #02: Blazion",
  [59422302] = "@Baffle Board #03: Miradox/Baffle Board #03: Miradox/Baffle Board #03: Miradox",
  [59422303] = "@Baffle Board #04: Robonyan/Baffle Board #04: Robonyan/Baffle Board #04: Robonyan",
  [59422304] = "@Baffle Board #05: Draaagin/Baffle Board #05: Draaagin/Baffle Board #05: Draaagin",
  [59422307] = "@Baffle Board #08: Washogun/Baffle Board #08: Washogun/Baffle Board #08: Washogun",
  [59422308] = "@Baffle Board #09: Mochismo/Baffle Board #09: Mochismo/Baffle Board #09: Mochismo",
  [59422310] = "@Baffle Board #11: Illoo/Baffle Board #11: Illoo/Baffle Board #11: Illoo",
  [59422311] = "@Baffle Board #12: Master Oden/Baffle Board #12: Master Oden/Baffle Board #12: Master Oden",
  [59422312] = "@Baffle Board #13: Cupistol/Baffle Board #13: Cupistol/Baffle Board #13: Cupistol",
  [59422313] = "@Baffle Board #14: Cadin/Baffle Board #14: Cadin/Baffle Board #14: Cadin",
  [59422314] = "@Baffle Board #15: Peckpocket/Baffle Board #15: Peckpocket/Baffle Board #15: Peckpocket",
  [59422315] = "@Baffle Board #16: High Gnomey/Baffle Board #16: High Gnomey/Baffle Board #16: High Gnomey",
  [59422316] = "@Baffle Board #17: Wazzat/Baffle Board #17: Wazzat/Baffle Board #17: Wazzat",
  [59422317] = "@Baffle Board #18: Chummer/Baffle Board #18: Chummer/Baffle Board #18: Chummer",
  [59422318] = "@Baffle Board #19: Ol' Fortune/Baffle Board #19: Ol' Fortune/Baffle Board #19: Ol' Fortune",
  [59422319] = "@Baffle Board #20: Wiglin/Baffle Board #20: Wiglin/Baffle Board #20: Wiglin",
  [59422320] = "@Baffle Board #21: Steppa/Baffle Board #21: Steppa/Baffle Board #21: Steppa",
  [59422321] = "@Baffle Board #22: Rhyth/Baffle Board #22: Rhyth/Baffle Board #22: Rhyth",
  [59422450] = "@Yo-criminals/Yo-criminals/Yo-criminals: 1 capture",
  [59422451] = "@Yo-criminals/Yo-criminals/Yo-criminals: 5 captures",
  [59422452] = "@Yo-criminals/Yo-criminals/Yo-criminals: 10 captures",
  [59422453] = "@Yo-criminals/Yo-criminals/Yo-criminals: 20 captures",
  [59422454] = "@Yo-criminals/Yo-criminals/Yo-criminals: 30 captures",
  [59422700] = "@Request: No Time For Fishin'!/Request: No Time For Fishin'!/Key Item: Fishing Rod",
  [59422702] = "@Key Item: Select-A-Coin/Key Item: Select-A-Coin/Key Item: Select-A-Coin",
  [59422703] = "@Key Item: School Keys/Key Item: School Keys/Key Item: School Keys",
  [59422704] = "@Key Item: Ancient Herb/Key Item: Ancient Herb/Key Item: Ancient Herb",
  [59422705] = "@Key Item: Pro Screwdriver/Key Item: Pro Screwdriver/Key Item: Pro Screwdriver",
  [59422707] = "@Key Item: Model Zero/Key Item: Model Zero/Key Item: Model Zero",
  [59422713] = "@Key Item: Back Door Key/Key Item: Back Door Key/Key Item: Back Door Key",
  [59422714] = "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Key Item: Bug Net",
  [59422715] = "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Key Item: Mom's Directions",
  [59422716] = "@Key Item: Gold Card Key/Key Item: Gold Card Key/Key Item: Gold Card Key",
  [59422717] = "@Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 03/Key Item: Treasure Room Key",
  [59422720] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Key Item: Strange Handle",
  [59423001] = "@Key Item: Bicycle/Key Item: Bicycle/Key Item: Bicycle",
  [59423002] = "@Boss: Chirpster/Boss: Chirpster/Boss: Chirpster",
  [59423003] = "@Boss: Phantasmurai/Boss: Phantasmurai/Boss: Phantasmurai",
  [59423004] = "@Boss: Massiface/Boss: Massiface/Boss: Massiface",
  [59423005] = "@Boss: Tarantutor/Boss: Tarantutor/Boss: Tarantutor",
  [59423006] = "@Boss: Duwheel/Boss: Duwheel/Boss: Duwheel",
  [59423007] = "@Boss: Dromp/Boss: Dromp/Boss: Dromp",
  [59423008] = "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Boss: Hans Full",
  [59423009] = "@Boss: Demuncher/Boss: Demuncher/Boss: Demuncher",
  [59423010] = "@Boss: Unfairy/Boss: Unfairy/Boss: Unfairy",
  [59423011] = "@Boss: Unkaind/Boss: Unkaind/Boss: Unkaind",
  [59423012] = "@Boss: Untidy/Boss: Untidy/Boss: Untidy",
  [59423013] = "@Boss: Unpleasant/Boss: Unpleasant/Boss: Unpleasant",
  [59423014] = "@Boss: Unkeen/Boss: Unkeen/Boss: Unkeen",
  [59423015] = "@Baffle Board #08: Washogun/Baffle Board #08: Washogun/Boss: Sproink",
  [59423016] = "@Boss: Eyephoon/Boss: Eyephoon/Boss: Eyephoon",
}
AP_CHAPTER_LOCATIONS = {
  [59420000] = 1,
  [59420001] = 2,
  [59420002] = 3,
  [59420003] = 4,
  [59420004] = 5,
  [59420005] = 6,
  [59420006] = 7,
  [59420007] = 8,
  [59420008] = 9,
  [59420009] = 10,
  [59420010] = 11,
}
AP_ALL_SECTIONS = {
  "@Abandoned Tunnel (Treasure Room) - Chest 01/Abandoned Tunnel (Treasure Room) - Chest 01/Abandoned Tunnel (Treasure Room) - Chest 01",
  "@Abandoned Tunnel (Treasure Room) - Chest 02/Abandoned Tunnel (Treasure Room) - Chest 02/Abandoned Tunnel (Treasure Room) - Chest 02",
  "@Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 03",
  "@Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 04",
  "@Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 05",
  "@Abandoned Tunnel (Treasure Room) - Chest 03/Abandoned Tunnel (Treasure Room) - Chest 03/Key Item: Treasure Room Key",
  "@Abandoned Tunnel (Treasure Room) - Chest 06/Abandoned Tunnel (Treasure Room) - Chest 06/Abandoned Tunnel (Treasure Room) - Chest 06",
  "@Abandoned Tunnel (Treasure Room) - Chest 07/Abandoned Tunnel (Treasure Room) - Chest 07/Abandoned Tunnel (Treasure Room) - Chest 07",
  "@Abandoned Tunnel (Treasure Room) - Chest 08/Abandoned Tunnel (Treasure Room) - Chest 08/Abandoned Tunnel (Treasure Room) - Chest 08",
  "@Abandoned Tunnel East - Chest 01/Abandoned Tunnel East - Chest 01/Abandoned Tunnel East - Chest 01",
  "@Abandoned Tunnel East - Chest 02/Abandoned Tunnel East - Chest 02/Abandoned Tunnel East - Chest 02",
  "@Abandoned Tunnel East - Chest 03/Abandoned Tunnel East - Chest 03/Abandoned Tunnel East - Chest 03",
  "@Abandoned Tunnel East - Chest 04/Abandoned Tunnel East - Chest 04/Abandoned Tunnel East - Chest 04",
  "@Abandoned Tunnel East - Chest 05/Abandoned Tunnel East - Chest 05/Abandoned Tunnel East - Chest 05",
  "@Abandoned Tunnel East - Chest 06/Abandoned Tunnel East - Chest 06/Abandoned Tunnel East - Chest 06",
  "@Baffle Board #01: Hungramps/Baffle Board #01: Hungramps/Baffle Board #01: Hungramps",
  "@Baffle Board #02: Blazion/Baffle Board #02: Blazion/Baffle Board #02: Blazion",
  "@Baffle Board #03: Miradox/Baffle Board #03: Miradox/Baffle Board #03: Miradox",
  "@Baffle Board #04: Robonyan/Baffle Board #04: Robonyan/Baffle Board #04: Robonyan",
  "@Baffle Board #05: Draaagin/Baffle Board #05: Draaagin/Baffle Board #05: Draaagin",
  "@Baffle Board #08: Washogun/Baffle Board #08: Washogun/Baffle Board #08: Washogun",
  "@Baffle Board #08: Washogun/Baffle Board #08: Washogun/Boss: Sproink",
  "@Baffle Board #09: Mochismo/Baffle Board #09: Mochismo/Baffle Board #09: Mochismo",
  "@Baffle Board #11: Illoo/Baffle Board #11: Illoo/Baffle Board #11: Illoo",
  "@Baffle Board #12: Master Oden/Baffle Board #12: Master Oden/Baffle Board #12: Master Oden",
  "@Baffle Board #13: Cupistol/Baffle Board #13: Cupistol/Baffle Board #13: Cupistol",
  "@Baffle Board #14: Cadin/Baffle Board #14: Cadin/Baffle Board #14: Cadin",
  "@Baffle Board #15: Peckpocket/Baffle Board #15: Peckpocket/Baffle Board #15: Peckpocket",
  "@Baffle Board #16: High Gnomey/Baffle Board #16: High Gnomey/Baffle Board #16: High Gnomey",
  "@Baffle Board #17: Wazzat/Baffle Board #17: Wazzat/Baffle Board #17: Wazzat",
  "@Baffle Board #18: Chummer/Baffle Board #18: Chummer/Baffle Board #18: Chummer",
  "@Baffle Board #19: Ol' Fortune/Baffle Board #19: Ol' Fortune/Baffle Board #19: Ol' Fortune",
  "@Baffle Board #20: Wiglin/Baffle Board #20: Wiglin/Baffle Board #20: Wiglin",
  "@Baffle Board #21: Steppa/Baffle Board #21: Steppa/Baffle Board #21: Steppa",
  "@Baffle Board #22: Rhyth/Baffle Board #22: Rhyth/Baffle Board #22: Rhyth",
  "@Blossom Heights (Rank B) - Chest 01/Blossom Heights (Rank B) - Chest 01/Blossom Heights (Rank B) - Chest 01",
  "@Blossom Heights (Rank C) - Chest 01/Blossom Heights (Rank C) - Chest 01/Blossom Heights (Rank C) - Chest 01",
  "@Blossom Heights (present) - Chest 01/Blossom Heights (present) - Chest 01/Blossom Heights (Rank C) - Chest 02",
  "@Blossom Heights (present) - Chest 01/Blossom Heights (present) - Chest 01/Blossom Heights (present) - Chest 01",
  "@Blossom Heights - Chest 01/Blossom Heights - Chest 01/Blossom Heights - Chest 01",
  "@Blossom Heights - Chest 02/Blossom Heights - Chest 02/Blossom Heights - Chest 02",
  "@Blossom Heights - Chest 03/Blossom Heights - Chest 03/Blossom Heights - Chest 03",
  "@Blossom Heights - Chest 04/Blossom Heights - Chest 04/Blossom Heights - Chest 04",
  "@Blossom Heights - Chest 05/Blossom Heights - Chest 05/Blossom Heights - Chest 05",
  "@Blossom Heights - Chest 06/Blossom Heights - Chest 06/Blossom Heights - Chest 06",
  "@Blossom Heights - Chest 07/Blossom Heights - Chest 07/Blossom Heights - Chest 07",
  "@Boss: Cap'n Crash/Boss: Cap'n Crash/Boss: Cap'n Crash",
  "@Boss: Chirpster/Boss: Chirpster/Boss: Chirpster",
  "@Boss: Dame Demona/Boss: Dame Demona/Boss: Dame Dedtime",
  "@Boss: Dame Demona/Boss: Dame Demona/Boss: Dame Demona",
  "@Boss: Demuncher/Boss: Demuncher/Boss: Demuncher",
  "@Boss: Dromp/Boss: Dromp/Boss: Dromp",
  "@Boss: Duwheel/Boss: Duwheel/Boss: Duwheel",
  "@Boss: Eyeclone/Boss: Eyeclone/Boss: Eyeclone",
  "@Boss: Eyephoon/Boss: Eyephoon/Boss: Eyephoon",
  "@Boss: Gutsy Bones/Boss: Gutsy Bones/Boss: Gutsy Bones",
  "@Boss: Kin/Boss: Kin/Boss: Gin",
  "@Boss: Kin/Boss: Kin/Boss: Kin",
  "@Boss: Massiface/Boss: Massiface/Boss: Massiface",
  "@Boss: Meganyan/Boss: Meganyan/Boss: Meganyan",
  "@Boss: Phantasmurai/Boss: Phantasmurai/Boss: Phantasmurai",
  "@Boss: Tarantutor/Boss: Tarantutor/Boss: Tarantutor",
  "@Boss: Unfairy/Boss: Unfairy/Boss: Unfairy",
  "@Boss: Unkaind/Boss: Unkaind/Boss: Unkaind",
  "@Boss: Unkeen/Boss: Unkeen/Boss: Unkeen",
  "@Boss: Unpleasant/Boss: Unpleasant/Boss: Unpleasant",
  "@Boss: Untidy/Boss: Untidy/Boss: Untidy",
  "@Breezy Hills (Gourd Pond Museum) - Chest 01/Breezy Hills (Gourd Pond Museum) - Chest 01/Breezy Hills (Gourd Pond Museum) - Chest 01",
  "@Breezy Hills (Gourd Pond Museum) - Chest 02/Breezy Hills (Gourd Pond Museum) - Chest 02/Breezy Hills (Gourd Pond Museum) - Chest 02",
  "@Breezy Hills (Gourd Pond Museum) - Chest 03/Breezy Hills (Gourd Pond Museum) - Chest 03/Breezy Hills (Gourd Pond Museum) - Chest 03",
  "@Breezy Hills (Gourd Pond Museum) - Chest 04/Breezy Hills (Gourd Pond Museum) - Chest 04/Breezy Hills (Gourd Pond Museum) - Chest 04",
  "@Breezy Hills (Gourd Pond Museum) - Chest 05/Breezy Hills (Gourd Pond Museum) - Chest 05/Breezy Hills (Gourd Pond Museum) - Chest 05",
  "@Breezy Hills (Gourd Pond Museum) - Chest 06/Breezy Hills (Gourd Pond Museum) - Chest 06/Breezy Hills (Gourd Pond Museum) - Chest 06",
  "@Breezy Hills (Gourd Pond Museum) - Chest 07/Breezy Hills (Gourd Pond Museum) - Chest 07/Breezy Hills (Gourd Pond Museum) - Chest 07",
  "@Breezy Hills (Gourd Pond Museum) - Chest 08/Breezy Hills (Gourd Pond Museum) - Chest 08/Breezy Hills (Gourd Pond Museum) - Chest 08",
  "@Breezy Hills (Jumbo Slider) - Chest 01/Breezy Hills (Jumbo Slider) - Chest 01/Breezy Hills (Jumbo Slider) - Chest 01",
  "@Breezy Hills (Jumbo Slider) - Chest 02/Breezy Hills (Jumbo Slider) - Chest 02/Breezy Hills (Jumbo Slider) - Chest 02",
  "@Breezy Hills (Jumbo Slider) - Chest 03/Breezy Hills (Jumbo Slider) - Chest 03/Breezy Hills (Jumbo Slider) - Chest 03",
  "@Breezy Hills (Stone House) - Chest 01/Breezy Hills (Stone House) - Chest 01/Breezy Hills (Stone House) - Chest 01",
  "@Breezy Hills - Chest 01/Breezy Hills - Chest 01/Breezy Hills - Chest 01",
  "@Breezy Hills - Chest 02/Breezy Hills - Chest 02/Breezy Hills - Chest 02",
  "@Breezy Hills - Chest 03/Breezy Hills - Chest 03/Breezy Hills - Chest 03",
  "@Breezy Hills - Chest 04/Breezy Hills - Chest 04/Breezy Hills - Chest 04",
  "@Breezy Hills - Chest 05/Breezy Hills - Chest 05/Breezy Hills - Chest 05",
  "@Breezy Hills - Chest 06/Breezy Hills - Chest 06/Breezy Hills - Chest 06",
  "@Chapters/Chapters/Chapter 10: Back to Normal!",
  "@Chapters/Chapters/Chapter 11: Old Springdale's in Peril!",
  "@Chapters/Chapters/Chapter 1: The Vanishing Watch",
  "@Chapters/Chapters/Chapter 2: Hi-Tech Hide-and-Seek",
  "@Chapters/Chapters/Chapter 3: School Is Strange",
  "@Chapters/Chapters/Chapter 4: Let's Go to Harrisville!",
  "@Chapters/Chapters/Chapter 5: Wind It Back 60 Years!",
  "@Chapters/Chapters/Chapter 6: Yo-kai Watch Model Zero",
  "@Chapters/Chapters/Chapter 7: The Storm Is Here!",
  "@Chapters/Chapters/Chapter 8: Big Yo-kai Battle",
  "@Chapters/Chapters/Chapter 9: Master Nyada's Trials",
  "@Desolate Lane - Chest 01/Desolate Lane - Chest 01/Desolate Lane - Chest 01",
  "@Downtown Springdale (sub-area) - Chest 01/Downtown Springdale (sub-area) - Chest 01/Downtown Springdale (sub-area) - Chest 01",
  "@Downtown Springdale - Chest 01/Downtown Springdale - Chest 01/Downtown Springdale - Chest 01",
  "@Downtown Springdale - Chest 02/Downtown Springdale - Chest 02/Downtown Springdale - Chest 02",
  "@Downtown Springdale - Chest 03/Downtown Springdale - Chest 03/Downtown Springdale - Chest 03",
  "@Downtown Springdale - Chest 04/Downtown Springdale - Chest 04/Downtown Springdale - Chest 04",
  "@Downtown Springdale - Chest 05/Downtown Springdale - Chest 05/Downtown Springdale - Chest 05",
  "@Downtown Springdale - Chest 06/Downtown Springdale - Chest 06/Downtown Springdale - Chest 06",
  "@Downtown Springdale - Chest 07/Downtown Springdale - Chest 07/Downtown Springdale - Chest 07",
  "@Downtown Springdale - Chest 08/Downtown Springdale - Chest 08/Downtown Springdale - Chest 08",
  "@Excellent Tower - Chest 01/Excellent Tower - Chest 01/Excellent Tower - Chest 01",
  "@Excellent Tower - Chest 02/Excellent Tower - Chest 02/Excellent Tower - Chest 02",
  "@Excellent Tower - Chest 03/Excellent Tower - Chest 03/Excellent Tower - Chest 03",
  "@Excellent Tower - Chest 04/Excellent Tower - Chest 04/Excellent Tower - Chest 04",
  "@Excellent Tower - Chest 05/Excellent Tower - Chest 05/Excellent Tower - Chest 05",
  "@Excellent Tower - Chest 05/Excellent Tower - Chest 05/Excellent Tower - Chest 06",
  "@Flatpot Plains - Chest 01/Flatpot Plains - Chest 01/Flatpot Plains - Chest 01",
  "@Flatpot Plains - Chest 02/Flatpot Plains - Chest 02/Flatpot Plains - Chest 02",
  "@Flatpot Plains - Chest 02/Flatpot Plains - Chest 02/Flatpot Plains - Chest 03",
  "@Flatpot Plains - Chest 04/Flatpot Plains - Chest 04/Flatpot Plains - Chest 04",
  "@Flatpot Plains - Chest 05/Flatpot Plains - Chest 05/Flatpot Plains - Chest 05",
  "@Flatpot Plains - Chest 06/Flatpot Plains - Chest 06/Flatpot Plains - Chest 06",
  "@Flatpot Plains - Chest 07/Flatpot Plains - Chest 07/Flatpot Plains - Chest 07",
  "@Flatpot Plains - Chest 08/Flatpot Plains - Chest 08/Flatpot Plains - Chest 08",
  "@Flatpot Plains - Chest 09/Flatpot Plains - Chest 09/Flatpot Plains - Chest 09",
  "@Flatpot Plains - Chest 10/Flatpot Plains - Chest 10/Flatpot Plains - Chest 10",
  "@Flatpot Plains - Chest 11/Flatpot Plains - Chest 11/Flatpot Plains - Chest 11",
  "@Fox Shrine Road - Chest 01/Fox Shrine Road - Chest 01/Fox Shrine Road - Chest 01",
  "@Gate Room - Chest 01/Gate Room - Chest 01/Gate Room - Chest 01",
  "@Gate Room - Chest 02/Gate Room - Chest 02/Gate Room - Chest 02",
  "@Gate Room - Chest 03/Gate Room - Chest 03/Gate Room - Chest 03",
  "@Gate Room - Chest 04/Gate Room - Chest 04/Gate Room - Chest 04",
  "@Gate Room - Chest 05/Gate Room - Chest 05/Gate Room - Chest 05",
  "@Gate Room - Chest 06/Gate Room - Chest 06/Gate Room - Chest 06",
  "@Gate Room - Chest 07/Gate Room - Chest 07/Gate Room - Chest 07",
  "@Gate Room - Chest 08/Gate Room - Chest 08/Gate Room - Chest 08",
  "@Gate Room - Chest 09/Gate Room - Chest 09/Gate Room - Chest 09",
  "@Gate Room - Chest 10/Gate Room - Chest 10/Gate Room - Chest 10",
  "@Go for Rank C!/Go for Rank C!/Go for Rank A!",
  "@Go for Rank C!/Go for Rank C!/Go for Rank B!",
  "@Go for Rank C!/Go for Rank C!/Go for Rank C!",
  "@Go for Rank C!/Go for Rank C!/Go for Rank S!",
  "@Go for Rank C!/Go for Rank C!/Rank Up: A",
  "@Go for Rank C!/Go for Rank C!/Rank Up: B",
  "@Go for Rank C!/Go for Rank C!/Rank Up: C",
  "@Go for Rank C!/Go for Rank C!/Rank Up: D",
  "@Go for Rank C!/Go for Rank C!/Rank Up: S",
  "@Gourd Pond (past) - Chest 01/Gourd Pond (past) - Chest 01/Gourd Pond (past) - Chest 01",
  "@Harrisville (Cicada Canyon) - Chest 01/Harrisville (Cicada Canyon) - Chest 01/Harrisville (Cicada Canyon) - Chest 01",
  "@Harrisville (Cicada Canyon) - Chest 02/Harrisville (Cicada Canyon) - Chest 02/Harrisville (Cicada Canyon) - Chest 02",
  "@Harrisville (Cicada Canyon) - Chest 03/Harrisville (Cicada Canyon) - Chest 03/Harrisville (Cicada Canyon) - Chest 03",
  "@Harrisville (Facing Rocks) - Chest 01/Harrisville (Facing Rocks) - Chest 01/Harrisville (Facing Rocks) - Chest 01",
  "@Harrisville (Facing Rocks) - Chest 02/Harrisville (Facing Rocks) - Chest 02/Harrisville (Facing Rocks) - Chest 02",
  "@Harrisville (Facing Rocks) - Chest 03/Harrisville (Facing Rocks) - Chest 03/Harrisville (Facing Rocks) - Chest 03",
  "@Harrisville - Chest 01/Harrisville - Chest 01/Harrisville - Chest 01",
  "@Harrisville - Chest 02/Harrisville - Chest 02/Harrisville - Chest 02",
  "@Harrisville - Chest 03/Harrisville - Chest 03/Harrisville - Chest 03",
  "@Harrisville - Chest 04/Harrisville - Chest 04/Harrisville - Chest 04",
  "@Harrisville - Chest 05/Harrisville - Chest 05/Harrisville - Chest 05",
  "@Harrisville - Chest 06/Harrisville - Chest 06/Harrisville - Chest 06",
  "@Harrisville - Chest 07/Harrisville - Chest 07/Harrisville - Chest 07",
  "@Harrisville - Chest 08/Harrisville - Chest 08/Harrisville - Chest 08",
  "@Harrisville - Chest 09/Harrisville - Chest 09/Harrisville - Chest 09",
  "@Harrisville - Chest 10/Harrisville - Chest 10/Harrisville - Chest 10",
  "@Harrisville - Chest 11/Harrisville - Chest 11/Harrisville - Chest 11",
  "@Harrisville - Chest 12/Harrisville - Chest 12/Harrisville - Chest 12",
  "@Harrisville Station Plaza - Chest 01/Harrisville Station Plaza - Chest 01/Harrisville Station Plaza - Chest 01",
  "@Harrisville Station Plaza - Chest 02/Harrisville Station Plaza - Chest 02/Harrisville Station Plaza - Chest 02",
  "@Harrisville Station Plaza - Chest 03/Harrisville Station Plaza - Chest 03/Harrisville Station Plaza - Chest 03",
  "@Harrisville Station Plaza - Chest 04/Harrisville Station Plaza - Chest 04/Harrisville Station Plaza - Chest 04",
  "@Harrisville Station Plaza - Chest 05/Harrisville Station Plaza - Chest 05/Harrisville Station Plaza - Chest 05",
  "@Hidden Side Street - Chest 01/Hidden Side Street - Chest 01/Hidden Side Street - Chest 01",
  "@Hidden Side Street - Chest 01/Hidden Side Street - Chest 01/Lonely Waterway - Chest 01",
  "@Hidden Side Street - Chest 01/Hidden Side Street - Chest 01/Lonely Waterway - Chest 02",
  "@Key Item: Ancient Herb/Key Item: Ancient Herb/Key Item: Ancient Herb",
  "@Key Item: Back Door Key/Key Item: Back Door Key/Key Item: Back Door Key",
  "@Key Item: Bicycle/Key Item: Bicycle/Key Item: Bicycle",
  "@Key Item: Gold Card Key/Key Item: Gold Card Key/Key Item: Gold Card Key",
  "@Key Item: Model Zero/Key Item: Model Zero/Key Item: Model Zero",
  "@Key Item: Pro Screwdriver/Key Item: Pro Screwdriver/Key Item: Pro Screwdriver",
  "@Key Item: School Keys/Key Item: School Keys/Key Item: School Keys",
  "@Key Item: Select-A-Coin/Key Item: Select-A-Coin/Key Item: Select-A-Coin",
  "@Mountain Path - Chest 01/Mountain Path - Chest 01/Mountain Path - Chest 01",
  "@Mt. Middleton (present) - Chest 01/Mt. Middleton (present) - Chest 01/Mt. Middleton (present) - Chest 01",
  "@Mt. Wildwood (Waterway Access) - Chest 01/Mt. Wildwood (Waterway Access) - Chest 01/Mt. Wildwood (Waterway Access) - Chest 01",
  "@Mt. Wildwood (Waterway Access) - Chest 01/Mt. Wildwood (Waterway Access) - Chest 01/Mt. Wildwood (Waterway Access) - Chest 02",
  "@Mt. Wildwood - Chest 01/Mt. Wildwood - Chest 01/Mt. Wildwood - Chest 01",
  "@Mt. Wildwood - Summit - Chest 01/Mt. Wildwood - Summit - Chest 01/Mt. Wildwood - Summit - Chest 01",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Boss: Hans Full",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Key Item: Strange Handle",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 02",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 03",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 04",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 05",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 06",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 07",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 08",
  "@Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 01/Nocturne Hospital - Chest 09",
  "@Old Blossom Heights - Chest 01/Old Blossom Heights - Chest 01/Old Blossom Heights - Chest 01",
  "@Old Blossom Heights - Chest 02/Old Blossom Heights - Chest 02/Old Blossom Heights - Chest 02",
  "@Old Blossom Heights - Chest 03/Old Blossom Heights - Chest 03/Old Blossom Heights - Chest 03",
  "@Old Blossom Heights - Chest 04/Old Blossom Heights - Chest 04/Old Blossom Heights - Chest 04",
  "@Old Harrisville - Chest 01/Old Harrisville - Chest 01/Old Harrisville - Chest 01",
  "@Old Harrisville - Chest 02/Old Harrisville - Chest 02/Old Harrisville - Chest 02",
  "@Old Harrisville - Chest 03/Old Harrisville - Chest 03/Old Harrisville - Chest 03",
  "@Old Harrisville - Chest 04/Old Harrisville - Chest 04/Old Harrisville - Chest 04",
  "@Old Harrisville - Chest 05/Old Harrisville - Chest 05/Old Harrisville - Chest 05",
  "@Old Harrisville - Chest 06/Old Harrisville - Chest 06/Old Harrisville - Chest 06",
  "@Old Harrisville - Chest 07/Old Harrisville - Chest 07/Old Harrisville - Chest 07",
  "@Old Harrisville - Chest 08/Old Harrisville - Chest 08/Old Harrisville - Chest 08",
  "@Old Harrisville - Chest 09/Old Harrisville - Chest 09/Old Harrisville - Chest 09",
  "@Old Harrisville - Chest 10/Old Harrisville - Chest 10/Old Harrisville - Chest 10",
  "@Old Mansion (Back) (Blossom Heights) - Chest 01/Old Mansion (Back) (Blossom Heights) - Chest 01/Old Mansion (Back) (Blossom Heights) - Chest 01",
  "@Old Mansion (Back) (Blossom Heights) - Chest 02/Old Mansion (Back) (Blossom Heights) - Chest 02/Old Mansion (Back) (Blossom Heights) - Chest 02",
  "@Old Mansion (Back) (Blossom Heights) - Chest 03/Old Mansion (Back) (Blossom Heights) - Chest 03/Old Mansion (Back) (Blossom Heights) - Chest 03",
  "@Old Mansion (Back) (Blossom Heights) - Chest 04/Old Mansion (Back) (Blossom Heights) - Chest 04/Old Mansion (Back) (Blossom Heights) - Chest 04",
  "@Old Mansion (Back) (Blossom Heights) - Chest 05/Old Mansion (Back) (Blossom Heights) - Chest 05/Old Mansion (Back) (Blossom Heights) - Chest 05",
  "@Old Mansion (Blossom Heights) - Chest 01/Old Mansion (Blossom Heights) - Chest 01/Old Mansion (Blossom Heights) - Chest 01",
  "@Old Mansion (Blossom Heights) - Chest 02/Old Mansion (Blossom Heights) - Chest 02/Old Mansion (Blossom Heights) - Chest 02",
  "@Old Mansion (Blossom Heights) - Chest 03/Old Mansion (Blossom Heights) - Chest 03/Old Mansion (Blossom Heights) - Chest 03",
  "@Old Mansion (Blossom Heights) - Chest 04/Old Mansion (Blossom Heights) - Chest 04/Old Mansion (Blossom Heights) - Chest 04",
  "@Old Mansion (Blossom Heights) - Chest 05/Old Mansion (Blossom Heights) - Chest 05/Old Mansion (Blossom Heights) - Chest 05",
  "@Old Mansion (Blossom Heights) - Chest 06/Old Mansion (Blossom Heights) - Chest 06/Old Mansion (Blossom Heights) - Chest 06",
  "@Old Mt. Middleton - Chest 01/Old Mt. Middleton - Chest 01/Old Mt. Middleton - Chest 01",
  "@Old Mt. Middleton - Chest 02/Old Mt. Middleton - Chest 02/Old Mt. Middleton - Chest 02",
  "@Old Mt. Middleton - Chest 03/Old Mt. Middleton - Chest 03/Old Mt. Middleton - Chest 03",
  "@Old Mt. Middleton - Chest 04/Old Mt. Middleton - Chest 04/Old Mt. Middleton - Chest 04",
  "@Old Mt. Middleton - Chest 05/Old Mt. Middleton - Chest 05/Old Mt. Middleton - Chest 05",
  "@Old Mt. Wildwood - Chest 01/Old Mt. Wildwood - Chest 01/Old Mt. Wildwood - Chest 01",
  "@Old Uptown Springdale (Ch.10 return) - Chest 01/Old Uptown Springdale (Ch.10 return) - Chest 01/Old Uptown Springdale (Ch.10 return) - Chest 01",
  "@Old Uptown Springdale - Chest 01/Old Uptown Springdale - Chest 01/Old Uptown Springdale - Chest 01",
  "@Old Uptown Springdale - Chest 02/Old Uptown Springdale - Chest 02/Old Uptown Springdale - Chest 02",
  "@Old Uptown Springdale - Chest 03/Old Uptown Springdale - Chest 03/Old Uptown Springdale - Chest 03",
  "@Old Uptown Springdale - Chest 04/Old Uptown Springdale - Chest 04/Old Uptown Springdale - Chest 04",
  "@Old Uptown Springdale - Chest 05/Old Uptown Springdale - Chest 05/Old Uptown Springdale - Chest 05",
  "@Request: A Card-Carrying Liar/Request: A Card-Carrying Liar/Request: A Card-Carrying Liar",
  "@Request: A Cicada Professional/Request: A Cicada Professional/Request: A Cicada Professional",
  "@Request: A Cicada Professional/Request: A Cicada Professional/Request: King of the Cicadas",
  "@Request: A Steamy Friendship/Request: A Steamy Friendship/Request: A Steamy Friendship",
  "@Request: All Aboard/Request: All Aboard/Request: All Aboard",
  "@Request: Bam-Boom! Fusing!/Request: Bam-Boom! Fusing!/Request: Bam-Boom! Fusing!",
  "@Request: Bear Boy: Origins/Request: Bear Boy: Origins/Request: Bear Boy: Origins",
  "@Request: Bear Boy: Origins/Request: Bear Boy: Origins/Request: The Bear Boy Returns",
  "@Request: C-1 Grand Prix A/Request: C-1 Grand Prix A/Request: C-1 Grand Prix A",
  "@Request: C-1 Grand Prix/Request: C-1 Grand Prix/Request: C-1 Grand Prix",
  "@Request: Catchy Fandom/Request: Catchy Fandom/Request: Catchy Fandom",
  "@Request: Customer Attraction!/Request: Customer Attraction!/Request: Customer Attraction!",
  "@Request: Find Gnomey!/Request: Find Gnomey!/Request: Find Gnomey!",
  "@Request: Find Mermaidyn!/Request: Find Mermaidyn!/Request: Find Mermaidyn!",
  "@Request: Find Pallysol!/Request: Find Pallysol!/Request: Find Pallysol!",
  "@Request: Find Predictabull!/Request: Find Predictabull!/Request: Find Predictabull!",
  "@Request: Foodie Feuds/Request: Foodie Feuds/Request: Foodie Feuds",
  "@Request: From the Future!/Request: From the Future!/Request: From the Future!",
  "@Request: Ghost Club at School/Request: Ghost Club at School/Request: Ghost Club at School",
  "@Request: Ghost Club at School/Request: Ghost Club at School/Request: Oden of the Soul Pt. 1",
  "@Request: Ghost Club at School/Request: Ghost Club at School/Request: Oden of the Soul Pt. 2",
  "@Request: Ghost Club at School/Request: Ghost Club at School/Request: Oden of the Soul Pt. 3",
  "@Request: Gone Haunting/Request: Gone Haunting/Request: Gone Haunting",
  "@Request: Gourmet Grand Prix/Request: Gourmet Grand Prix/Request: Gourmet Grand Prix",
  "@Request: Hangout Havoc/Request: Hangout Havoc/Request: Hangout Havoc",
  "@Request: I Just Wanna Grow Up/Request: I Just Wanna Grow Up/Request: I Just Wanna Grow Up",
  "@Request: Inspirited Away/Request: Inspirited Away/Request: Inspirited Away",
  "@Request: Long Lost Love/Request: Long Lost Love/Request: Long Lost Love",
  "@Request: Makeover Takeover/Request: Makeover Takeover/Request: Makeover Takeover",
  "@Request: Matt, Don't Give Up!/Request: Matt, Don't Give Up!/Request: Matt, Don't Give Up!",
  "@Request: Matt, Don't Give Up!/Request: Matt, Don't Give Up!/Request: Treasure Hunters Pt. 1",
  "@Request: Matt, Don't Give Up!/Request: Matt, Don't Give Up!/Request: Treasure Hunters Pt. 2",
  "@Request: Matt, Don't Give Up!/Request: Matt, Don't Give Up!/Request: Treasure Hunters Pt. 3",
  "@Request: Moving Blues/Request: Moving Blues/Request: Moving Blues",
  "@Request: No Time For Fishin'!/Request: No Time For Fishin'!/Key Item: Fishing Rod",
  "@Request: No Time For Fishin'!/Request: No Time For Fishin'!/Request: Find Faux Kappa!",
  "@Request: No Time For Fishin'!/Request: No Time For Fishin'!/Request: No Time For Fishin'!",
  "@Request: Nyada's Trials IV/Request: Nyada's Trials IV/Request: Nyada's Trials IV",
  "@Request: Nyada's Trials V/Request: Nyada's Trials V/Request: Nyada's Trials V",
  "@Request: Nyada's Trials VI/Request: Nyada's Trials VI/Request: Nyada's Trials VI",
  "@Request: Officially Official!/Request: Officially Official!/Request: Officially Official!",
  "@Request: Secrets of Soulcery/Request: Secrets of Soulcery/Request: Secrets of Soulcery",
  "@Request: Slicenrice Under Fire/Request: Slicenrice Under Fire/Request: Slicenrice Under Fire",
  "@Request: Springdale Star Pt. 1/Request: Springdale Star Pt. 1/Request: Springdale Star Pt. 1",
  "@Request: Springdale Star Pt. 2/Request: Springdale Star Pt. 2/Request: Springdale Star Pt. 2",
  "@Request: Super Hide-and-Seek/Request: Super Hide-and-Seek/Request: Super Hide-and-Seek",
  "@Request: Take to the Sea!/Request: Take to the Sea!/Request: Take to the Sea!",
  "@Request: The Gates of Whimsy/Request: The Gates of Whimsy/Request: Collection Correction",
  "@Request: The Gates of Whimsy/Request: The Gates of Whimsy/Request: Eerie, Roving Armor",
  "@Request: The Gates of Whimsy/Request: The Gates of Whimsy/Request: The Final Gate",
  "@Request: The Gates of Whimsy/Request: The Gates of Whimsy/Request: The Gates of Whimsy",
  "@Request: The Gates of Whimsy/Request: The Gates of Whimsy/Request: Time and Toys",
  "@Request: The Haunted Hospital/Request: The Haunted Hospital/Request: The Haunted Hospital",
  "@Request: The Heartthrobs/Request: The Heartthrobs/Request: The Heartthrobs",
  "@Request: The Ironworks' Part/Request: The Ironworks' Part/Request: The Ironworks' Part",
  "@Request: The Price of Iron/Request: The Price of Iron/Request: The Price of Iron",
  "@Request: The Secret Base/Request: The Secret Base/Request: The Secret Base",
  "@Request: The Shrine's Part/Request: The Shrine's Part/Request: The Shrine's Part",
  "@Request: Timers & More's Part/Request: Timers & More's Part/Request: Timers & More's Part",
  "@Request: Too Much Makeover/Request: Too Much Makeover/Request: Too Much Makeover",
  "@Request: True Hide-and-Seek/Request: True Hide-and-Seek/Request: True Hide-and-Seek",
  "@Request: Ultra Hide-and-Seek/Request: Ultra Hide-and-Seek/Request: Ultra Hide-and-Seek",
  "@Request: Which Beetle's Better/Request: Which Beetle's Better/Request: Which Beetle's Better",
  "@Request: Who's That Girl/Request: Who's That Girl/Request: Who's That Girl",
  "@Request: Your Local Mascot/Request: Your Local Mascot/Request: Your Local Mascot",
  "@San Fantastico (Rank C) - Chest 01/San Fantastico (Rank C) - Chest 01/San Fantastico (Rank C) - Chest 01",
  "@San Fantastico - Chest 01/San Fantastico - Chest 01/San Fantastico - Chest 01",
  "@San Fantastico - Chest 02/San Fantastico - Chest 02/San Fantastico - Chest 02",
  "@San Fantastico - Chest 03/San Fantastico - Chest 03/San Fantastico - Chest 03",
  "@San Fantastico - Chest 04/San Fantastico - Chest 04/San Fantastico - Chest 04",
  "@San Fantastico - Chest 05/San Fantastico - Chest 05/San Fantastico - Chest 05",
  "@San Fantastico - Chest 06/San Fantastico - Chest 06/San Fantastico - Chest 06",
  "@San Fantastico - Chest 07/San Fantastico - Chest 07/San Fantastico - Chest 07",
  "@San Fantastico - Chest 08/San Fantastico - Chest 08/San Fantastico - Chest 08",
  "@San Fantastico - Chest 09/San Fantastico - Chest 09/San Fantastico - Chest 09",
  "@San Fantastico - Chest 10/San Fantastico - Chest 10/San Fantastico - Chest 10",
  "@San Fantastico - Chest 11/San Fantastico - Chest 11/San Fantastico - Chest 11",
  "@San Fantastico - Chest 12/San Fantastico - Chest 12/San Fantastico - Chest 12",
  "@San Fantastico - Chest 13/San Fantastico - Chest 13/San Fantastico - Chest 13",
  "@San Fantastico - Chest 14/San Fantastico - Chest 14/San Fantastico - Chest 14",
  "@San Fantastico - Chest 15/San Fantastico - Chest 15/San Fantastico - Chest 15",
  "@San Fantastico - Chest 16/San Fantastico - Chest 16/San Fantastico - Chest 16",
  "@Seaside Cave - Chest 01/Seaside Cave - Chest 01/Seaside Cave - Chest 01",
  "@Seaside Cave - Chest 02/Seaside Cave - Chest 02/Seaside Cave - Chest 02",
  "@Seaside Cave - Chest 03/Seaside Cave - Chest 03/Seaside Cave - Chest 03",
  "@Seaside Cave - Chest 04/Seaside Cave - Chest 04/Seaside Cave - Chest 04",
  "@Seaside Cave - Chest 05/Seaside Cave - Chest 05/Seaside Cave - Chest 05",
  "@Seaside Cave - Chest 06/Seaside Cave - Chest 06/Seaside Cave - Chest 06",
  "@Seaside Cave - Chest 07/Seaside Cave - Chest 07/Seaside Cave - Chest 07",
  "@Seaside Cave - Chest 08/Seaside Cave - Chest 08/Seaside Cave - Chest 08",
  "@Seaside Cave - Chest 09/Seaside Cave - Chest 09/Seaside Cave - Chest 09",
  "@Service: A Likely Story/Service: A Likely Story/Service: A Likely Story",
  "@Service: Bug Hunting/Service: Bug Hunting/Service: Bug Hunting",
  "@Service: Fat Cat's Favor/Service: Fat Cat's Favor/Service: Fat Cat's Favor",
  "@Service: Overstuffed Head/Service: Overstuffed Head/Service: Overstuffed Head",
  "@Service: Popular Training/Service: Popular Training/Service: Popular Training",
  "@Service: Running on Empty/Service: Running on Empty/Service: Running on Empty",
  "@Service: School Pranks/Service: School Pranks/Service: School Pranks",
  "@Service: Struck with Love/Service: Struck with Love/Service: Struck with Love",
  "@Service: Stuck in the Heat/Service: Stuck in the Heat/Service: Stuck in the Heat",
  "@Service: Sweet Satisfaction/Service: Sweet Satisfaction/Service: Sweet Satisfaction",
  "@Shopper's Row (Apt. C-303) - Chest 01/Shopper's Row (Apt. C-303) - Chest 01/Shopper's Row (Apt. C-303) - Chest 01",
  "@Springdale (Shopper's Row) - Chest 01/Springdale (Shopper's Row) - Chest 01/Springdale (Shopper's Row) - Chest 01",
  "@Springdale (Shopper's Row) - Chest 02/Springdale (Shopper's Row) - Chest 02/Springdale (Shopper's Row) - Chest 02",
  "@Springdale (Shopper's Row) - Chest 03/Springdale (Shopper's Row) - Chest 03/Springdale (Shopper's Row) - Chest 03",
  "@Springdale (Shopper's Row) - Chest 04/Springdale (Shopper's Row) - Chest 04/Springdale (Shopper's Row) - Chest 04",
  "@Springdale (Shopper's Row) - Chest 05/Springdale (Shopper's Row) - Chest 05/Springdale (Shopper's Row) - Chest 05",
  "@Springdale (Shopper's Row) - Chest 06/Springdale (Shopper's Row) - Chest 06/Springdale (Shopper's Row) - Chest 06",
  "@Springdale Business Tower (12th Floor) - Chest 01/Springdale Business Tower (12th Floor) - Chest 01/Springdale Business Tower (12th Floor) - Chest 01",
  "@Springdale Business Tower (12th Floor) - Chest 02/Springdale Business Tower (12th Floor) - Chest 02/Springdale Business Tower (12th Floor) - Chest 02",
  "@Springdale Business Tower (12th Floor) - Chest 03/Springdale Business Tower (12th Floor) - Chest 03/Springdale Business Tower (12th Floor) - Chest 03",
  "@Springdale Business Tower (3rd Floor) - Chest 01/Springdale Business Tower (3rd Floor) - Chest 01/Springdale Business Tower (3rd Floor) - Chest 01",
  "@Springdale Business Tower (3rd Floor) - Chest 02/Springdale Business Tower (3rd Floor) - Chest 02/Springdale Business Tower (3rd Floor) - Chest 02",
  "@Springdale Business Tower (3rd Floor) - Chest 03/Springdale Business Tower (3rd Floor) - Chest 03/Springdale Business Tower (3rd Floor) - Chest 03",
  "@Springdale Business Tower (3rd Floor, Rank A) - Chest 01/Springdale Business Tower (3rd Floor, Rank A) - Chest 01/Springdale Business Tower (3rd Floor, Rank A) - Chest 01",
  "@Springdale Elementary School (night) - Chest 01/Springdale Elementary School (night) - Chest 01/Springdale Elementary School (night) - Chest 01",
  "@Springdale Elementary School (night) - Chest 02/Springdale Elementary School (night) - Chest 02/Springdale Elementary School (night) - Chest 02",
  "@Springdale Elementary School (night) - Chest 03/Springdale Elementary School (night) - Chest 03/Springdale Elementary School (night) - Chest 03",
  "@Springdale Elementary School (night) - Chest 04/Springdale Elementary School (night) - Chest 04/Springdale Elementary School (night) - Chest 04",
  "@Springdale Elementary School (night) - Chest 05/Springdale Elementary School (night) - Chest 05/Springdale Elementary School (night) - Chest 05",
  "@Springdale Elementary School (night) - Chest 06/Springdale Elementary School (night) - Chest 06/Springdale Elementary School (night) - Chest 06",
  "@Springdale Elementary School (night) - Chest 07/Springdale Elementary School (night) - Chest 07/Springdale Elementary School (night) - Chest 07",
  "@Springdale Elementary School (night) - Chest 08/Springdale Elementary School (night) - Chest 08/Springdale Elementary School (night) - Chest 08",
  "@Springdale Elementary School (night) - Chest 09/Springdale Elementary School (night) - Chest 09/Springdale Elementary School (night) - Chest 09",
  "@Springdale Elementary School (night) - Chest 10/Springdale Elementary School (night) - Chest 10/Springdale Elementary School (night) - Chest 10",
  "@Springdale Elementary School (night) - Chest 11/Springdale Elementary School (night) - Chest 11/Springdale Elementary School (night) - Chest 11",
  "@Springdale Elementary School (night) - Chest 12/Springdale Elementary School (night) - Chest 12/Springdale Elementary School (night) - Chest 12",
  "@Springdale Elementary School (night) - Chest 13/Springdale Elementary School (night) - Chest 13/Springdale Elementary School (night) - Chest 13",
  "@Springdale Ironworks - Chest 01/Springdale Ironworks - Chest 01/Springdale Ironworks - Chest 01",
  "@Springdale Ironworks - Chest 02/Springdale Ironworks - Chest 02/Springdale Ironworks - Chest 02",
  "@Underground Waterway - Chest 01/Underground Waterway - Chest 01/Underground Waterway - Chest 01",
  "@Underground Waterway - Chest 02/Underground Waterway - Chest 02/Underground Waterway - Chest 02",
  "@Underground Waterway - Chest 03/Underground Waterway - Chest 03/Underground Waterway - Chest 03",
  "@Underground Waterway - Chest 04/Underground Waterway - Chest 04/Underground Waterway - Chest 04",
  "@Underground Waterway - Chest 05/Underground Waterway - Chest 05/Underground Waterway - Chest 05",
  "@Underground Waterway - Chest 06/Underground Waterway - Chest 06/Underground Waterway - Chest 06",
  "@Underground Waterway - Chest 07/Underground Waterway - Chest 07/Underground Waterway - Chest 07",
  "@Underground Waterway - Chest 08/Underground Waterway - Chest 08/Underground Waterway - Chest 08",
  "@Underground Waterway - Chest 09/Underground Waterway - Chest 09/Underground Waterway - Chest 09",
  "@Underground Waterway - Chest 10/Underground Waterway - Chest 10/Underground Waterway - Chest 10",
  "@Underground Waterway - Chest 11/Underground Waterway - Chest 11/Underground Waterway - Chest 11",
  "@Underground Waterway - Chest 12/Underground Waterway - Chest 12/Underground Waterway - Chest 12",
  "@Underground Waterway - Chest 13/Underground Waterway - Chest 13/Underground Waterway - Chest 13",
  "@Uptown Springdale (The Catwalk) - Chest 01/Uptown Springdale (The Catwalk) - Chest 01/Uptown Springdale (The Catwalk) - Chest 01",
  "@Uptown Springdale - Chest 01/Uptown Springdale - Chest 01/Uptown Springdale - Chest 01",
  "@Uptown Springdale - Chest 02/Uptown Springdale - Chest 02/Uptown Springdale - Chest 02",
  "@Uptown Springdale - Chest 03/Uptown Springdale - Chest 03/Uptown Springdale - Chest 03",
  "@Uptown Springdale - Chest 04/Uptown Springdale - Chest 04/Uptown Springdale - Chest 04",
  "@Uptown Springdale - Chest 05/Uptown Springdale - Chest 05/Uptown Springdale - Chest 05",
  "@Uptown Springdale - Chest 06/Uptown Springdale - Chest 06/Uptown Springdale - Chest 06",
  "@Uptown Springdale - Chest 07/Uptown Springdale - Chest 07/Uptown Springdale - Chest 07",
  "@Uptown Springdale - Chest 08/Uptown Springdale - Chest 08/Uptown Springdale - Chest 08",
  "@Uptown Springdale - Chest 09/Uptown Springdale - Chest 09/Uptown Springdale - Chest 09",
  "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Key Item: Bug Net",
  "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Key Item: Mom's Directions",
  "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Request: Dinner on Hold",
  "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Request: Jibanyan's Secret",
  "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Request: Retrace Dad's Steps",
  "@Uptown Springdale - Chest 10/Uptown Springdale - Chest 10/Uptown Springdale - Chest 10",
  "@Well Road - Chest 01/Well Road - Chest 01/Well Road - Chest 01",
  "@Yo-criminals/Yo-criminals/Yo-criminals: 1 capture",
  "@Yo-criminals/Yo-criminals/Yo-criminals: 10 captures",
  "@Yo-criminals/Yo-criminals/Yo-criminals: 20 captures",
  "@Yo-criminals/Yo-criminals/Yo-criminals: 30 captures",
  "@Yo-criminals/Yo-criminals/Yo-criminals: 5 captures",
}