-- GÉNÉRÉ par tools/generate_tracker_pack.py — ne pas éditer.
AP_ITEMS = {
  [59420000] = {action="toggle", code="velo"},
  [59420001] = {action="toggle", code="velo"},
  [59420003] = {action="rang_inc"},
  [59420004] = {action="rang_set", n=1},
  [59420005] = {action="rang_set", n=2},
  [59420006] = {action="rang_set", n=3},
  [59420007] = {action="rang_set", n=4},
  [59420008] = {action="rang_set", n=5},
  [59420009] = {action="chapitre_inc"},
  [59420042] = {action="toggle", code="pile_ou_passe"},
  [59420043] = {action="toggle", code="cles_de_l_ecole"},
  [59420044] = {action="toggle", code="herbe_ancestrale"},
  [59420045] = {action="toggle", code="super_tournevis"},
  [59420046] = {action="toggle", code="canne_a_peche"},
  [59420047] = {action="toggle", code="tenue_de_rocker"},
  [59420048] = {action="toggle", code="modele_zero"},
  [59420049] = {action="toggle", code="jolie_petite_cle"},
  [59420050] = {action="toggle", code="jolie_grande_cle"},
  [59420051] = {action="toggle", code="cle_appartement_c_101"},
  [59420052] = {action="toggle", code="cle_appartement_c_303"},
  [59420053] = {action="toggle", code="cle_appartement_b_301"},
  [59420054] = {action="toggle", code="cle_de_derriere"},
  [59420055] = {action="toggle", code="filet_a_insectes"},
  [59420056] = {action="toggle", code="indications_de_maman"},
  [59420057] = {action="toggle", code="cle_magnetique_or"},
  [59420058] = {action="toggle", code="cle_salle_du_tresor"},
  [59420059] = {action="toggle", code="cle_appartement_b_204"},
  [59420060] = {action="toggle", code="huile_de_tendino"},
  [59420061] = {action="toggle", code="poignee_etrange"},
}
AP_LOCATIONS = {
  [59420000] = "@Chapitres/Chapitres/Chapitre 1 : La montre disparue",
  [59420001] = "@Chapitres/Chapitres/Chapitre 2 : Cache-cache high-tech",
  [59420002] = "@Chapitres/Chapitres/Chapitre 3 : L'étrange école",
  [59420003] = "@Chapitres/Chapitres/Chapitre 4 : En route pour Ourcival !",
  [59420004] = "@Chapitres/Chapitres/Chapitre 5 : Retour 60 ans en arrière !",
  [59420005] = "@Chapitres/Chapitres/Chapitre 6 : Yo-kai Watch Modèle Zéro",
  [59420006] = "@Chapitres/Chapitres/Chapitre 7 : La tempête arrive !",
  [59420007] = "@Chapitres/Chapitres/Chapitre 8 : La grande bataille Yo-kai",
  [59420008] = "@Chapitres/Chapitres/Chapitre 9 : Maître Nyada : le défi",
  [59420009] = "@Chapitres/Chapitres/Chapitre 10 : Retour à la normale !",
  [59420010] = "@Chapitres/Chapitres/Chapitre 11 : Danger au vieux Granval !",
  [59420050] = "@Obtenons le rang C !/Obtenons le rang C !/Obtenons le rang C !",
  [59420051] = "@Obtenons le rang C !/Obtenons le rang C !/Obtenons le rang B !",
  [59420052] = "@Obtenons le rang C !/Obtenons le rang C !/Obtenons le rang A !",
  [59420053] = "@Obtenons le rang C !/Obtenons le rang C !/Obtenons le rang S !",
  [59420054] = "@Obtenons le rang C !/Obtenons le rang C !/Montée de rang : D",
  [59420055] = "@Obtenons le rang C !/Obtenons le rang C !/Montée de rang : C",
  [59420056] = "@Obtenons le rang C !/Obtenons le rang C !/Montée de rang : B",
  [59420057] = "@Obtenons le rang C !/Obtenons le rang C !/Montée de rang : A",
  [59420058] = "@Obtenons le rang C !/Obtenons le rang C !/Montée de rang : S",
  [59420100] = "@Boss : Grolos/Boss : Grolos/Boss : Grolos",
  [59420101] = "@Boss : Méganyan/Boss : Méganyan/Boss : Méganyan",
  [59420102] = "@Boss : Barbefrousse/Boss : Barbefrousse/Boss : Barbefrousse",
  [59420103] = "@Boss : Laure/Boss : Laure/Boss : Laure",
  [59420104] = "@Boss : Laure/Boss : Laure/Boss : Marge",
  [59420105] = "@Boss : Tourbœillon/Boss : Tourbœillon/Boss : Tourbœillon",
  [59420106] = "@Boss : Lady Démona/Boss : Lady Démona/Boss : Lady Perpétua",
  [59420107] = "@Boss : Lady Démona/Boss : Lady Démona/Boss : Lady Démona",
  [59420200] = "@Requête : Spécialiste des cigales/Requête : Spécialiste des cigales/Requête : Spécialiste des cigales",
  [59420201] = "@Requête : Courage, Max !/Requête : Courage, Max !/Requête : Courage, Max !",
  [59420202] = "@Requête : Ça attire les clients !/Requête : Ça attire les clients !/Requête : Ça attire les clients !",
  [59420203] = "@Requête : Les portails mystère/Requête : Les portails mystère/Requête : Musée en détresse",
  [59420204] = "@Requête : Officiellement officiel !/Requête : Officiellement officiel !/Requête : Officiellement officiel !",
  [59420205] = "@Requête : Bam boum ! Fusion !/Requête : Bam boum ! Fusion !/Requête : Bam boum ! Fusion !",
  [59420206] = "@Requête : Les portails mystère/Requête : Les portails mystère/Requête : Les portails mystère",
  [59420207] = "@Requête : Super Balaise : l'origine/Requête : Super Balaise : l'origine/Requête : Super Balaise : l'origine",
  [59420208] = "@Requête : Soirée chaotique/Requête : Soirée chaotique/Requête : Soirée chaotique",
  [59420209] = "@Requête : Courage, Max !/Requête : Courage, Max !/Requête : Chasseurs de trésors 1",
  [59420210] = "@Requête : La base secrète/Requête : La base secrète/Requête : La base secrète",
  [59420211] = "@Requête : Nouveau look/Requête : Nouveau look/Requête : Nouveau look",
  [59420212] = "@Requête : Agonigiri a des soucis/Requête : Agonigiri a des soucis/Requête : Agonigiri a des soucis",
  [59420213] = "@Requête : La star de Granval 1/Requête : La star de Granval 1/Requête : La star de Granval 1",
  [59420214] = "@Requête : Secrets de l'Âmechimie/Requête : Secrets de l'Âmechimie/Requête : Secrets de l'Âmechimie",
  [59420215] = "@Requête : Pas le temps de pêcher !/Requête : Pas le temps de pêcher !/Requête : Pas le temps de pêcher !",
  [59420216] = "@Requête : Vrai cache-cache/Requête : Vrai cache-cache/Requête : Vrai cache-cache",
  [59420217] = "@Requête : Le meilleur scarabée/Requête : Le meilleur scarabée/Requête : Le meilleur scarabée",
  [59420218] = "@Requête : Pièce Au Phil du temps/Requête : Pièce Au Phil du temps/Requête : Pièce Au Phil du temps",
  [59420219] = "@Requête : Pièce sanctuaire/Requête : Pièce sanctuaire/Requête : Pièce sanctuaire",
  [59420220] = "@Requête : Pièce ferronnerie/Requête : Pièce ferronnerie/Requête : Pièce ferronnerie",
  [59420221] = "@Requête : Trouvons Parasolal !/Requête : Trouvons Parasolal !/Requête : Trouvons Parasolal !",
  [59420222] = "@Requête : Trouvons Lulutin !/Requête : Trouvons Lulutin !/Requête : Trouvons Lulutin !",
  [59420223] = "@Requête : Trouvons Métaureaulog !/Requête : Trouvons Métaureaulog !/Requête : Trouvons Métaureaulog !",
  [59420224] = "@Requête : Trouvons Sirénée !/Requête : Trouvons Sirénée !/Requête : Trouvons Sirénée !",
  [59420225] = "@Requête : Pas le temps de pêcher !/Requête : Pas le temps de pêcher !/Requête : Trouvons Faux Kappa !",
  [59420226] = "@Requête : Les portails mystère/Requête : Les portails mystère/Requête : Le portail final",
  [59420227] = "@Requête : Prix de Gastronomie/Requête : Prix de Gastronomie/Requête : Prix de Gastronomie",
  [59420228] = "@Requête : Un amour perdu/Requête : Un amour perdu/Requête : Un amour perdu",
  [59420229] = "@Requête : Votre mascotte locale/Requête : Votre mascotte locale/Requête : Votre mascotte locale",
  [59420230] = "@Requête : Blues du déménagement/Requête : Blues du déménagement/Requête : Blues du déménagement",
  [59420231] = "@Requête : Ectoplasmes à l'école/Requête : Ectoplasmes à l'école/Requête : Oden de l'âme 1",
  [59420232] = "@Requête : Ectoplasmes à l'école/Requête : Ectoplasmes à l'école/Requête : Oden de l'âme 2",
  [59420233] = "@Requête : Ectoplasmes à l'école/Requête : Ectoplasmes à l'école/Requête : Oden de l'âme 3",
  [59420234] = "@Requête : Chasse nocturne/Requête : Chasse nocturne/Requête : Chasse nocturne",
  [59420235] = "@Requête : Voyage de l'envoûtement/Requête : Voyage de l'envoûtement/Requête : Voyage de l'envoûtement",
  [59420236] = "@Requête : Virée en mer !/Requête : Virée en mer !/Requête : Virée en mer !",
  [59420237] = "@Requête : Super cache-cache/Requête : Super cache-cache/Requête : Super cache-cache",
  [59420238] = "@Requête : Tous à bord/Requête : Tous à bord/Requête : Tous à bord",
  [59420239] = "@Requête : Ectoplasmes à l'école/Requête : Ectoplasmes à l'école/Requête : Ectoplasmes à l'école",
  [59420240] = "@Requête : Le prix du fer/Requête : Le prix du fer/Requête : Le prix du fer",
  [59420241] = "@Requête : Super Balaise : l'origine/Requête : Super Balaise : l'origine/Requête : Super Balaise : le retour",
  [59420242] = "@Requête : Courage, Max !/Requête : Courage, Max !/Requête : Chasseurs de trésors 2",
  [59420243] = "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Requête : Le secret de Jibanyan",
  [59420244] = "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Requête : Sur les traces de Papa",
  [59420245] = "@Requête : Triangle amoureux/Requête : Triangle amoureux/Requête : Triangle amoureux",
  [59420246] = "@Requête : Un look trop sophistiqué/Requête : Un look trop sophistiqué/Requête : Un look trop sophistiqué",
  [59420247] = "@Requête : Spécialiste des cigales/Requête : Spécialiste des cigales/Requête : La reine des cigales",
  [59420248] = "@Requête : Les sources de l'amitié/Requête : Les sources de l'amitié/Requête : Les sources de l'amitié",
  [59420249] = "@Requête : Je veux grandir/Requête : Je veux grandir/Requête : Je veux grandir",
  [59420250] = "@Requête : C-1 Grand Prix/Requête : C-1 Grand Prix/Requête : C-1 Grand Prix",
  [59420251] = "@Requête : Un super fan-club/Requête : Un super fan-club/Requête : Un super fan-club",
  [59420252] = "@Requête : Coup de bluff/Requête : Coup de bluff/Requête : Coup de bluff",
  [59420253] = "@Requête : Querelles gourmandes/Requête : Querelles gourmandes/Requête : Querelles gourmandes",
  [59420254] = "@Requête : Les portails mystère/Requête : Les portails mystère/Requête : Jouets d'antan",
  [59420255] = "@Requête : Tout droit sorti du futur !/Requête : Tout droit sorti du futur !/Requête : Tout droit sorti du futur !",
  [59420256] = "@Requête : C-1 Grand Prix A/Requête : C-1 Grand Prix A/Requête : C-1 Grand Prix A",
  [59420257] = "@Requête : Les portails mystère/Requête : Les portails mystère/Requête : Une armure sinistre",
  [59420258] = "@Requête : Méga cache-cache/Requête : Méga cache-cache/Requête : Méga cache-cache",
  [59420259] = "@Requête : Courage, Max !/Requête : Courage, Max !/Requête : Chasseurs de trésors 3",
  [59420260] = "@Requête : Épreuves de Nyada IV/Requête : Épreuves de Nyada IV/Requête : Épreuves de Nyada IV",
  [59420261] = "@Requête : Épreuves de Nyada V/Requête : Épreuves de Nyada V/Requête : Épreuves de Nyada V",
  [59420262] = "@Requête : Épreuves de Nyada VI/Requête : Épreuves de Nyada VI/Requête : Épreuves de Nyada VI",
  [59420263] = "@Requête : La star de Granval 2/Requête : La star de Granval 2/Requête : La star de Granval 2",
  [59420264] = "@Requête : Qui est cette fille/Requête : Qui est cette fille/Requête : Qui est cette fille",
  [59420265] = "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Requête : La faim justifie le moyen",
  [59420266] = "@Requête : La clinique hantée/Requête : La clinique hantée/Requête : La clinique hantée",
  [59420267] = "@Service : Sous un soleil de plomb/Service : Sous un soleil de plomb/Service : Sous un soleil de plomb",
  [59420268] = "@Service : Le ventre vide/Service : Le ventre vide/Service : Le ventre vide",
  [59420269] = "@Service : Que de balivernes/Service : Que de balivernes/Service : Que de balivernes",
  [59420270] = "@Service : Une envie de bonbons/Service : Une envie de bonbons/Service : Une envie de bonbons",
  [59420271] = "@Service : La malade imaginaire/Service : La malade imaginaire/Service : La malade imaginaire",
  [59420272] = "@Service : Espiègleries/Service : Espiègleries/Service : Espiègleries",
  [59420273] = "@Service : Un entraînement de star/Service : Un entraînement de star/Service : Un entraînement de star",
  [59420274] = "@Service : À la chasse aux insectes !/Service : À la chasse aux insectes !/Service : À la chasse aux insectes !",
  [59420275] = "@Service : Un matou en détresse/Service : Un matou en détresse/Service : Un matou en détresse",
  [59420276] = "@Service : Coup de foudre/Service : Coup de foudre/Service : Coup de foudre",
  [59421000] = "@Les Hauts de Granval - Coffre 01/Les Hauts de Granval - Coffre 01/Les Hauts de Granval - Coffre 01",
  [59421001] = "@Les Hauts de Granval - Coffre 02/Les Hauts de Granval - Coffre 02/Les Hauts de Granval - Coffre 02",
  [59421002] = "@Les Hauts de Granval - Coffre 03/Les Hauts de Granval - Coffre 03/Les Hauts de Granval - Coffre 03",
  [59421003] = "@Les Hauts de Granval - Coffre 04/Les Hauts de Granval - Coffre 04/Les Hauts de Granval - Coffre 04",
  [59421004] = "@Les Hauts de Granval - Coffre 05/Les Hauts de Granval - Coffre 05/Les Hauts de Granval - Coffre 05",
  [59421005] = "@Les Hauts de Granval - Coffre 06/Les Hauts de Granval - Coffre 06/Les Hauts de Granval - Coffre 06",
  [59421006] = "@Les Hauts de Granval - Coffre 07/Les Hauts de Granval - Coffre 07/Les Hauts de Granval - Coffre 07",
  [59421007] = "@Les Hauts de Granval - Coffre 08/Les Hauts de Granval - Coffre 08/Les Hauts de Granval - Coffre 08",
  [59421008] = "@Les Hauts de Granval - Coffre 09/Les Hauts de Granval - Coffre 09/Les Hauts de Granval - Coffre 09",
  [59421009] = "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10",
  [59421010] = "@Les Hauts de Granval (Passage des matous) - Coffre 01/Les Hauts de Granval (Passage des matous) - Coffre 01/Les Hauts de Granval (Passage des matous) - Coffre 01",
  [59421011] = "@Ourcival (Rochers de face) - Coffre 01/Ourcival (Rochers de face) - Coffre 01/Ourcival (Rochers de face) - Coffre 01",
  [59421012] = "@Ourcival (Rochers de face) - Coffre 02/Ourcival (Rochers de face) - Coffre 02/Ourcival (Rochers de face) - Coffre 02",
  [59421013] = "@Ourcival (Rochers de face) - Coffre 03/Ourcival (Rochers de face) - Coffre 03/Ourcival (Rochers de face) - Coffre 03",
  [59421014] = "@Ourcival (Canyon de la cigale) - Coffre 01/Ourcival (Canyon de la cigale) - Coffre 01/Ourcival (Canyon de la cigale) - Coffre 01",
  [59421015] = "@Ourcival (Canyon de la cigale) - Coffre 02/Ourcival (Canyon de la cigale) - Coffre 02/Ourcival (Canyon de la cigale) - Coffre 02",
  [59421016] = "@Ourcival (Canyon de la cigale) - Coffre 03/Ourcival (Canyon de la cigale) - Coffre 03/Ourcival (Canyon de la cigale) - Coffre 03",
  [59421017] = "@Ourcival - Coffre 01/Ourcival - Coffre 01/Ourcival - Coffre 01",
  [59421018] = "@Ourcival - Coffre 02/Ourcival - Coffre 02/Ourcival - Coffre 02",
  [59421019] = "@Ourcival - Coffre 03/Ourcival - Coffre 03/Ourcival - Coffre 03",
  [59421020] = "@Ourcival - Coffre 04/Ourcival - Coffre 04/Ourcival - Coffre 04",
  [59421021] = "@Ourcival - Coffre 05/Ourcival - Coffre 05/Ourcival - Coffre 05",
  [59421022] = "@Ourcival - Coffre 06/Ourcival - Coffre 06/Ourcival - Coffre 06",
  [59421023] = "@Ourcival - Coffre 07/Ourcival - Coffre 07/Ourcival - Coffre 07",
  [59421024] = "@Ourcival - Coffre 08/Ourcival - Coffre 08/Ourcival - Coffre 08",
  [59421025] = "@Ourcival - Coffre 09/Ourcival - Coffre 09/Ourcival - Coffre 09",
  [59421026] = "@Ourcival - Coffre 10/Ourcival - Coffre 10/Ourcival - Coffre 10",
  [59421027] = "@Ourcival - Coffre 11/Ourcival - Coffre 11/Ourcival - Coffre 11",
  [59421028] = "@Ourcival - Coffre 12/Ourcival - Coffre 12/Ourcival - Coffre 12",
  [59421029] = "@Centre-ville de Granval - Coffre 01/Centre-ville de Granval - Coffre 01/Centre-ville de Granval - Coffre 01",
  [59421030] = "@Centre-ville de Granval - Coffre 02/Centre-ville de Granval - Coffre 02/Centre-ville de Granval - Coffre 02",
  [59421031] = "@Centre-ville de Granval - Coffre 03/Centre-ville de Granval - Coffre 03/Centre-ville de Granval - Coffre 03",
  [59421032] = "@Centre-ville de Granval - Coffre 04/Centre-ville de Granval - Coffre 04/Centre-ville de Granval - Coffre 04",
  [59421033] = "@Centre-ville de Granval - Coffre 05/Centre-ville de Granval - Coffre 05/Centre-ville de Granval - Coffre 05",
  [59421034] = "@Centre-ville de Granval - Coffre 06/Centre-ville de Granval - Coffre 06/Centre-ville de Granval - Coffre 06",
  [59421035] = "@Centre-ville de Granval - Coffre 07/Centre-ville de Granval - Coffre 07/Centre-ville de Granval - Coffre 07",
  [59421036] = "@Centre-ville de Granval - Coffre 08/Centre-ville de Granval - Coffre 08/Centre-ville de Granval - Coffre 08",
  [59421037] = "@Corniche - Coffre 01/Corniche - Coffre 01/Corniche - Coffre 01",
  [59421038] = "@Corniche - Coffre 02/Corniche - Coffre 02/Corniche - Coffre 02",
  [59421039] = "@Corniche - Coffre 03/Corniche - Coffre 03/Corniche - Coffre 03",
  [59421040] = "@Corniche - Coffre 04/Corniche - Coffre 04/Corniche - Coffre 04",
  [59421041] = "@Corniche - Coffre 05/Corniche - Coffre 05/Corniche - Coffre 05",
  [59421042] = "@Corniche - Coffre 06/Corniche - Coffre 06/Corniche - Coffre 06",
  [59421043] = "@Égouts - Coffre 01/Égouts - Coffre 01/Égouts - Coffre 01",
  [59421044] = "@Égouts - Coffre 02/Égouts - Coffre 02/Égouts - Coffre 02",
  [59421045] = "@Égouts - Coffre 03/Égouts - Coffre 03/Égouts - Coffre 03",
  [59421046] = "@Égouts - Coffre 04/Égouts - Coffre 04/Égouts - Coffre 04",
  [59421047] = "@Égouts - Coffre 05/Égouts - Coffre 05/Égouts - Coffre 05",
  [59421048] = "@Égouts - Coffre 06/Égouts - Coffre 06/Égouts - Coffre 06",
  [59421049] = "@Égouts - Coffre 07/Égouts - Coffre 07/Égouts - Coffre 07",
  [59421050] = "@Égouts - Coffre 08/Égouts - Coffre 08/Égouts - Coffre 08",
  [59421051] = "@Égouts - Coffre 09/Égouts - Coffre 09/Égouts - Coffre 09",
  [59421052] = "@Égouts - Coffre 10/Égouts - Coffre 10/Égouts - Coffre 10",
  [59421053] = "@Égouts - Coffre 11/Égouts - Coffre 11/Égouts - Coffre 11",
  [59421054] = "@Égouts - Coffre 12/Égouts - Coffre 12/Égouts - Coffre 12",
  [59421055] = "@Égouts - Coffre 13/Égouts - Coffre 13/Égouts - Coffre 13",
  [59421056] = "@Allée sinistre - Coffre 01/Allée sinistre - Coffre 01/Allée sinistre - Coffre 01",
  [59421057] = "@Ruelle obscure - Coffre 01/Ruelle obscure - Coffre 01/Ruelle obscure - Coffre 01",
  [59421058] = "@Ruelle obscure - Coffre 01/Ruelle obscure - Coffre 01/Canal isolé - Coffre 01",
  [59421059] = "@Ruelle obscure - Coffre 01/Ruelle obscure - Coffre 01/Canal isolé - Coffre 02",
  [59421060] = "@Corniche (Maison des Roch) - Coffre 01/Corniche (Maison des Roch) - Coffre 01/Corniche (Maison des Roch) - Coffre 01",
  [59421061] = "@Corniche (Méga toboggan) - Coffre 01/Corniche (Méga toboggan) - Coffre 01/Corniche (Méga toboggan) - Coffre 01",
  [59421062] = "@Corniche (Méga toboggan) - Coffre 02/Corniche (Méga toboggan) - Coffre 02/Corniche (Méga toboggan) - Coffre 02",
  [59421063] = "@Corniche (Méga toboggan) - Coffre 03/Corniche (Méga toboggan) - Coffre 03/Corniche (Méga toboggan) - Coffre 03",
  [59421064] = "@Corniche (Musée) - Coffre 01/Corniche (Musée) - Coffre 01/Corniche (Musée) - Coffre 01",
  [59421065] = "@Corniche (Musée) - Coffre 02/Corniche (Musée) - Coffre 02/Corniche (Musée) - Coffre 02",
  [59421066] = "@Corniche (Musée) - Coffre 03/Corniche (Musée) - Coffre 03/Corniche (Musée) - Coffre 03",
  [59421067] = "@Corniche (Musée) - Coffre 04/Corniche (Musée) - Coffre 04/Corniche (Musée) - Coffre 04",
  [59421068] = "@Corniche (Musée) - Coffre 05/Corniche (Musée) - Coffre 05/Corniche (Musée) - Coffre 05",
  [59421069] = "@Corniche (Musée) - Coffre 06/Corniche (Musée) - Coffre 06/Corniche (Musée) - Coffre 06",
  [59421070] = "@Corniche (Musée) - Coffre 07/Corniche (Musée) - Coffre 07/Corniche (Musée) - Coffre 07",
  [59421071] = "@Corniche (Musée) - Coffre 08/Corniche (Musée) - Coffre 08/Corniche (Musée) - Coffre 08",
  [59421072] = "@Tunnel abandonné (salle du trésor) - Coffre 01/Tunnel abandonné (salle du trésor) - Coffre 01/Tunnel abandonné (salle du trésor) - Coffre 01",
  [59421073] = "@Tunnel abandonné (salle du trésor) - Coffre 02/Tunnel abandonné (salle du trésor) - Coffre 02/Tunnel abandonné (salle du trésor) - Coffre 02",
  [59421074] = "@Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 03",
  [59421075] = "@Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 04",
  [59421076] = "@Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 05",
  [59421077] = "@Tunnel abandonné (salle du trésor) - Coffre 06/Tunnel abandonné (salle du trésor) - Coffre 06/Tunnel abandonné (salle du trésor) - Coffre 06",
  [59421078] = "@Tunnel abandonné (salle du trésor) - Coffre 07/Tunnel abandonné (salle du trésor) - Coffre 07/Tunnel abandonné (salle du trésor) - Coffre 07",
  [59421079] = "@Tunnel abandonné (salle du trésor) - Coffre 08/Tunnel abandonné (salle du trésor) - Coffre 08/Tunnel abandonné (salle du trésor) - Coffre 08",
  [59421080] = "@Tunnel abandonné est - Coffre 01/Tunnel abandonné est - Coffre 01/Tunnel abandonné est - Coffre 01",
  [59421081] = "@Tunnel abandonné est - Coffre 02/Tunnel abandonné est - Coffre 02/Tunnel abandonné est - Coffre 02",
  [59421082] = "@Tunnel abandonné est - Coffre 03/Tunnel abandonné est - Coffre 03/Tunnel abandonné est - Coffre 03",
  [59421083] = "@Tunnel abandonné est - Coffre 04/Tunnel abandonné est - Coffre 04/Tunnel abandonné est - Coffre 04",
  [59421084] = "@Tunnel abandonné est - Coffre 05/Tunnel abandonné est - Coffre 05/Tunnel abandonné est - Coffre 05",
  [59421085] = "@Tunnel abandonné est - Coffre 06/Tunnel abandonné est - Coffre 06/Tunnel abandonné est - Coffre 06",
  [59421086] = "@Sommet du Mont Sylvestre - Coffre 01/Sommet du Mont Sylvestre - Coffre 01/Sommet du Mont Sylvestre - Coffre 01",
  [59421087] = "@Sentier de randonnée - Coffre 01/Sentier de randonnée - Coffre 01/Sentier de randonnée - Coffre 01",
  [59421088] = "@Mont Sylvestre - Coffre 01/Mont Sylvestre - Coffre 01/Mont Sylvestre - Coffre 01",
  [59421089] = "@Mont Sylvestre (accès égouts) - Coffre 01/Mont Sylvestre (accès égouts) - Coffre 01/Mont Sylvestre (accès égouts) - Coffre 01",
  [59421090] = "@Mont Sylvestre (accès égouts) - Coffre 01/Mont Sylvestre (accès égouts) - Coffre 01/Mont Sylvestre (accès égouts) - Coffre 02",
  [59421091] = "@École élémentaire de Granval (nuit) - Coffre 01/École élémentaire de Granval (nuit) - Coffre 01/École élémentaire de Granval (nuit) - Coffre 01",
  [59421092] = "@École élémentaire de Granval (nuit) - Coffre 02/École élémentaire de Granval (nuit) - Coffre 02/École élémentaire de Granval (nuit) - Coffre 02",
  [59421093] = "@École élémentaire de Granval (nuit) - Coffre 03/École élémentaire de Granval (nuit) - Coffre 03/École élémentaire de Granval (nuit) - Coffre 03",
  [59421094] = "@École élémentaire de Granval (nuit) - Coffre 04/École élémentaire de Granval (nuit) - Coffre 04/École élémentaire de Granval (nuit) - Coffre 04",
  [59421095] = "@École élémentaire de Granval (nuit) - Coffre 05/École élémentaire de Granval (nuit) - Coffre 05/École élémentaire de Granval (nuit) - Coffre 05",
  [59421096] = "@École élémentaire de Granval (nuit) - Coffre 06/École élémentaire de Granval (nuit) - Coffre 06/École élémentaire de Granval (nuit) - Coffre 06",
  [59421097] = "@École élémentaire de Granval (nuit) - Coffre 07/École élémentaire de Granval (nuit) - Coffre 07/École élémentaire de Granval (nuit) - Coffre 07",
  [59421098] = "@École élémentaire de Granval (nuit) - Coffre 08/École élémentaire de Granval (nuit) - Coffre 08/École élémentaire de Granval (nuit) - Coffre 08",
  [59421099] = "@École élémentaire de Granval (nuit) - Coffre 09/École élémentaire de Granval (nuit) - Coffre 09/École élémentaire de Granval (nuit) - Coffre 09",
  [59421100] = "@École élémentaire de Granval (nuit) - Coffre 10/École élémentaire de Granval (nuit) - Coffre 10/École élémentaire de Granval (nuit) - Coffre 10",
  [59421101] = "@École élémentaire de Granval (nuit) - Coffre 11/École élémentaire de Granval (nuit) - Coffre 11/École élémentaire de Granval (nuit) - Coffre 11",
  [59421102] = "@École élémentaire de Granval (nuit) - Coffre 12/École élémentaire de Granval (nuit) - Coffre 12/École élémentaire de Granval (nuit) - Coffre 12",
  [59421103] = "@École élémentaire de Granval (nuit) - Coffre 13/École élémentaire de Granval (nuit) - Coffre 13/École élémentaire de Granval (nuit) - Coffre 13",
  [59421104] = "@Coteau fleuri - Coffre 01/Coteau fleuri - Coffre 01/Coteau fleuri - Coffre 01",
  [59421105] = "@Coteau fleuri - Coffre 02/Coteau fleuri - Coffre 02/Coteau fleuri - Coffre 02",
  [59421106] = "@Coteau fleuri - Coffre 03/Coteau fleuri - Coffre 03/Coteau fleuri - Coffre 03",
  [59421107] = "@Coteau fleuri - Coffre 04/Coteau fleuri - Coffre 04/Coteau fleuri - Coffre 04",
  [59421108] = "@Coteau fleuri - Coffre 05/Coteau fleuri - Coffre 05/Coteau fleuri - Coffre 05",
  [59421109] = "@Coteau fleuri - Coffre 06/Coteau fleuri - Coffre 06/Coteau fleuri - Coffre 06",
  [59421110] = "@Coteau fleuri - Coffre 07/Coteau fleuri - Coffre 07/Coteau fleuri - Coffre 07",
  [59421111] = "@Granval (Quartier des boutiques) - Coffre 01/Granval (Quartier des boutiques) - Coffre 01/Granval (Quartier des boutiques) - Coffre 01",
  [59421112] = "@Granval (Quartier des boutiques) - Coffre 02/Granval (Quartier des boutiques) - Coffre 02/Granval (Quartier des boutiques) - Coffre 02",
  [59421113] = "@Granval (Quartier des boutiques) - Coffre 03/Granval (Quartier des boutiques) - Coffre 03/Granval (Quartier des boutiques) - Coffre 03",
  [59421114] = "@Granval (Quartier des boutiques) - Coffre 04/Granval (Quartier des boutiques) - Coffre 04/Granval (Quartier des boutiques) - Coffre 04",
  [59421115] = "@Granval (Quartier des boutiques) - Coffre 05/Granval (Quartier des boutiques) - Coffre 05/Granval (Quartier des boutiques) - Coffre 05",
  [59421116] = "@Granval (Quartier des boutiques) - Coffre 06/Granval (Quartier des boutiques) - Coffre 06/Granval (Quartier des boutiques) - Coffre 06",
  [59421117] = "@Centre-ville de Granval (sous-zone) - Coffre 01/Centre-ville de Granval (sous-zone) - Coffre 01/Centre-ville de Granval (sous-zone) - Coffre 01",
  [59421118] = "@Manoir (Coteau fleuri) - Coffre 01/Manoir (Coteau fleuri) - Coffre 01/Manoir (Coteau fleuri) - Coffre 01",
  [59421119] = "@Manoir (Coteau fleuri) - Coffre 02/Manoir (Coteau fleuri) - Coffre 02/Manoir (Coteau fleuri) - Coffre 02",
  [59421120] = "@Manoir (Coteau fleuri) - Coffre 03/Manoir (Coteau fleuri) - Coffre 03/Manoir (Coteau fleuri) - Coffre 03",
  [59421121] = "@Manoir (Coteau fleuri) - Coffre 04/Manoir (Coteau fleuri) - Coffre 04/Manoir (Coteau fleuri) - Coffre 04",
  [59421122] = "@Manoir (Coteau fleuri) - Coffre 05/Manoir (Coteau fleuri) - Coffre 05/Manoir (Coteau fleuri) - Coffre 05",
  [59421123] = "@Manoir (Coteau fleuri) - Coffre 06/Manoir (Coteau fleuri) - Coffre 06/Manoir (Coteau fleuri) - Coffre 06",
  [59421124] = "@Manoir arrière (Coteau fleuri) - Coffre 01/Manoir arrière (Coteau fleuri) - Coffre 01/Manoir arrière (Coteau fleuri) - Coffre 01",
  [59421125] = "@Manoir arrière (Coteau fleuri) - Coffre 02/Manoir arrière (Coteau fleuri) - Coffre 02/Manoir arrière (Coteau fleuri) - Coffre 02",
  [59421126] = "@Manoir arrière (Coteau fleuri) - Coffre 03/Manoir arrière (Coteau fleuri) - Coffre 03/Manoir arrière (Coteau fleuri) - Coffre 03",
  [59421127] = "@Manoir arrière (Coteau fleuri) - Coffre 04/Manoir arrière (Coteau fleuri) - Coffre 04/Manoir arrière (Coteau fleuri) - Coffre 04",
  [59421128] = "@Manoir arrière (Coteau fleuri) - Coffre 05/Manoir arrière (Coteau fleuri) - Coffre 05/Manoir arrière (Coteau fleuri) - Coffre 05",
  [59421129] = "@Tour Excellence - Coffre 01/Tour Excellence - Coffre 01/Tour Excellence - Coffre 01",
  [59421130] = "@Tour Excellence - Coffre 02/Tour Excellence - Coffre 02/Tour Excellence - Coffre 02",
  [59421131] = "@Tour Excellence - Coffre 03/Tour Excellence - Coffre 03/Tour Excellence - Coffre 03",
  [59421132] = "@Tour Excellence - Coffre 04/Tour Excellence - Coffre 04/Tour Excellence - Coffre 04",
  [59421133] = "@Tour Excellence - Coffre 05/Tour Excellence - Coffre 05/Tour Excellence - Coffre 05",
  [59421134] = "@Tour Excellence - Coffre 05/Tour Excellence - Coffre 05/Tour Excellence - Coffre 06",
  [59421135] = "@Parvis de la gare d'Ourcival - Coffre 01/Parvis de la gare d'Ourcival - Coffre 01/Parvis de la gare d'Ourcival - Coffre 01",
  [59421136] = "@Parvis de la gare d'Ourcival - Coffre 02/Parvis de la gare d'Ourcival - Coffre 02/Parvis de la gare d'Ourcival - Coffre 02",
  [59421137] = "@Parvis de la gare d'Ourcival - Coffre 03/Parvis de la gare d'Ourcival - Coffre 03/Parvis de la gare d'Ourcival - Coffre 03",
  [59421138] = "@Parvis de la gare d'Ourcival - Coffre 04/Parvis de la gare d'Ourcival - Coffre 04/Parvis de la gare d'Ourcival - Coffre 04",
  [59421139] = "@Parvis de la gare d'Ourcival - Coffre 05/Parvis de la gare d'Ourcival - Coffre 05/Parvis de la gare d'Ourcival - Coffre 05",
  [59421140] = "@Mont de l'Ours (présent) - Coffre 01/Mont de l'Ours (présent) - Coffre 01/Mont de l'Ours (présent) - Coffre 01",
  [59421141] = "@San Fantastico - Coffre 01/San Fantastico - Coffre 01/San Fantastico - Coffre 01",
  [59421142] = "@San Fantastico - Coffre 02/San Fantastico - Coffre 02/San Fantastico - Coffre 02",
  [59421143] = "@San Fantastico - Coffre 03/San Fantastico - Coffre 03/San Fantastico - Coffre 03",
  [59421144] = "@San Fantastico - Coffre 04/San Fantastico - Coffre 04/San Fantastico - Coffre 04",
  [59421145] = "@San Fantastico - Coffre 05/San Fantastico - Coffre 05/San Fantastico - Coffre 05",
  [59421146] = "@San Fantastico - Coffre 06/San Fantastico - Coffre 06/San Fantastico - Coffre 06",
  [59421147] = "@San Fantastico - Coffre 07/San Fantastico - Coffre 07/San Fantastico - Coffre 07",
  [59421148] = "@San Fantastico - Coffre 08/San Fantastico - Coffre 08/San Fantastico - Coffre 08",
  [59421149] = "@San Fantastico - Coffre 09/San Fantastico - Coffre 09/San Fantastico - Coffre 09",
  [59421150] = "@San Fantastico - Coffre 10/San Fantastico - Coffre 10/San Fantastico - Coffre 10",
  [59421151] = "@San Fantastico - Coffre 11/San Fantastico - Coffre 11/San Fantastico - Coffre 11",
  [59421152] = "@San Fantastico - Coffre 12/San Fantastico - Coffre 12/San Fantastico - Coffre 12",
  [59421153] = "@San Fantastico - Coffre 13/San Fantastico - Coffre 13/San Fantastico - Coffre 13",
  [59421154] = "@San Fantastico - Coffre 14/San Fantastico - Coffre 14/San Fantastico - Coffre 14",
  [59421155] = "@San Fantastico - Coffre 15/San Fantastico - Coffre 15/San Fantastico - Coffre 15",
  [59421156] = "@San Fantastico - Coffre 16/San Fantastico - Coffre 16/San Fantastico - Coffre 16",
  [59421157] = "@San Fantastico (rang C) - Coffre 01/San Fantastico (rang C) - Coffre 01/San Fantastico (rang C) - Coffre 01",
  [59421158] = "@Tour du commerce (3e étage) - Coffre 01/Tour du commerce (3e étage) - Coffre 01/Tour du commerce (3e étage) - Coffre 01",
  [59421159] = "@Tour du commerce (3e étage) - Coffre 02/Tour du commerce (3e étage) - Coffre 02/Tour du commerce (3e étage) - Coffre 02",
  [59421160] = "@Tour du commerce (3e étage) - Coffre 03/Tour du commerce (3e étage) - Coffre 03/Tour du commerce (3e étage) - Coffre 03",
  [59421161] = "@Tour du commerce (3e étage, rang A) - Coffre 01/Tour du commerce (3e étage, rang A) - Coffre 01/Tour du commerce (3e étage, rang A) - Coffre 01",
  [59421162] = "@Tour du commerce (12e étage) - Coffre 01/Tour du commerce (12e étage) - Coffre 01/Tour du commerce (12e étage) - Coffre 01",
  [59421163] = "@Tour du commerce (12e étage) - Coffre 02/Tour du commerce (12e étage) - Coffre 02/Tour du commerce (12e étage) - Coffre 02",
  [59421164] = "@Tour du commerce (12e étage) - Coffre 03/Tour du commerce (12e étage) - Coffre 03/Tour du commerce (12e étage) - Coffre 03",
  [59421165] = "@Quartier des boutiques (appartement C-303) - Coffre 01/Quartier des boutiques (appartement C-303) - Coffre 01/Quartier des boutiques (appartement C-303) - Coffre 01",
  [59421166] = "@Grotte du littoral - Coffre 01/Grotte du littoral - Coffre 01/Grotte du littoral - Coffre 01",
  [59421167] = "@Grotte du littoral - Coffre 02/Grotte du littoral - Coffre 02/Grotte du littoral - Coffre 02",
  [59421168] = "@Grotte du littoral - Coffre 03/Grotte du littoral - Coffre 03/Grotte du littoral - Coffre 03",
  [59421169] = "@Grotte du littoral - Coffre 04/Grotte du littoral - Coffre 04/Grotte du littoral - Coffre 04",
  [59421170] = "@Grotte du littoral - Coffre 05/Grotte du littoral - Coffre 05/Grotte du littoral - Coffre 05",
  [59421171] = "@Grotte du littoral - Coffre 06/Grotte du littoral - Coffre 06/Grotte du littoral - Coffre 06",
  [59421172] = "@Grotte du littoral - Coffre 07/Grotte du littoral - Coffre 07/Grotte du littoral - Coffre 07",
  [59421173] = "@Grotte du littoral - Coffre 08/Grotte du littoral - Coffre 08/Grotte du littoral - Coffre 08",
  [59421174] = "@Grotte du littoral - Coffre 09/Grotte du littoral - Coffre 09/Grotte du littoral - Coffre 09",
  [59421175] = "@Coteau fleuri (présent) - Coffre 01/Coteau fleuri (présent) - Coffre 01/Coteau fleuri (présent) - Coffre 01",
  [59421176] = "@Coteau fleuri (rang C) - Coffre 01/Coteau fleuri (rang C) - Coffre 01/Coteau fleuri (rang C) - Coffre 01",
  [59421177] = "@Coteau fleuri (présent) - Coffre 01/Coteau fleuri (présent) - Coffre 01/Coteau fleuri (rang C) - Coffre 02",
  [59421178] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01",
  [59421179] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 02",
  [59421180] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 03",
  [59421181] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 04",
  [59421182] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 05",
  [59421183] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 06",
  [59421184] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 07",
  [59421185] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 08",
  [59421186] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 09",
  [59421187] = "@Vieux Hauts de Granval - Coffre 01/Vieux Hauts de Granval - Coffre 01/Vieux Hauts de Granval - Coffre 01",
  [59421188] = "@Vieux Hauts de Granval - Coffre 02/Vieux Hauts de Granval - Coffre 02/Vieux Hauts de Granval - Coffre 02",
  [59421189] = "@Vieux Hauts de Granval - Coffre 03/Vieux Hauts de Granval - Coffre 03/Vieux Hauts de Granval - Coffre 03",
  [59421190] = "@Vieux Hauts de Granval - Coffre 04/Vieux Hauts de Granval - Coffre 04/Vieux Hauts de Granval - Coffre 04",
  [59421191] = "@Vieux Hauts de Granval - Coffre 05/Vieux Hauts de Granval - Coffre 05/Vieux Hauts de Granval - Coffre 05",
  [59421192] = "@Vieux Hauts de Granval (retour Ch10) - Coffre 01/Vieux Hauts de Granval (retour Ch10) - Coffre 01/Vieux Hauts de Granval (retour Ch10) - Coffre 01",
  [59421193] = "@Vieux Coteau Fleuri - Coffre 01/Vieux Coteau Fleuri - Coffre 01/Vieux Coteau Fleuri - Coffre 01",
  [59421194] = "@Vieux Coteau Fleuri - Coffre 02/Vieux Coteau Fleuri - Coffre 02/Vieux Coteau Fleuri - Coffre 02",
  [59421195] = "@Vieux Coteau Fleuri - Coffre 03/Vieux Coteau Fleuri - Coffre 03/Vieux Coteau Fleuri - Coffre 03",
  [59421196] = "@Vieux Coteau Fleuri - Coffre 04/Vieux Coteau Fleuri - Coffre 04/Vieux Coteau Fleuri - Coffre 04",
  [59421197] = "@Chemin du Sanctuaire du Renard - Coffre 01/Chemin du Sanctuaire du Renard - Coffre 01/Chemin du Sanctuaire du Renard - Coffre 01",
  [59421198] = "@Chemin du Puits - Coffre 01/Chemin du Puits - Coffre 01/Chemin du Puits - Coffre 01",
  [59421199] = "@Vieille Ferronnerie de Granval - Coffre 01/Vieille Ferronnerie de Granval - Coffre 01/Vieille Ferronnerie de Granval - Coffre 01",
  [59421200] = "@Vieille Ferronnerie de Granval - Coffre 02/Vieille Ferronnerie de Granval - Coffre 02/Vieille Ferronnerie de Granval - Coffre 02",
  [59421201] = "@Vieux Mont Sylvestre - Coffre 01/Vieux Mont Sylvestre - Coffre 01/Vieux Mont Sylvestre - Coffre 01",
  [59421202] = "@Lac des Coloquintes (passé) - Coffre 01/Lac des Coloquintes (passé) - Coffre 01/Lac des Coloquintes (passé) - Coffre 01",
  [59421203] = "@Vieil Ourcival - Coffre 01/Vieil Ourcival - Coffre 01/Vieil Ourcival - Coffre 01",
  [59421204] = "@Vieil Ourcival - Coffre 02/Vieil Ourcival - Coffre 02/Vieil Ourcival - Coffre 02",
  [59421205] = "@Vieil Ourcival - Coffre 03/Vieil Ourcival - Coffre 03/Vieil Ourcival - Coffre 03",
  [59421206] = "@Vieil Ourcival - Coffre 04/Vieil Ourcival - Coffre 04/Vieil Ourcival - Coffre 04",
  [59421207] = "@Vieil Ourcival - Coffre 05/Vieil Ourcival - Coffre 05/Vieil Ourcival - Coffre 05",
  [59421208] = "@Vieil Ourcival - Coffre 06/Vieil Ourcival - Coffre 06/Vieil Ourcival - Coffre 06",
  [59421209] = "@Vieil Ourcival - Coffre 07/Vieil Ourcival - Coffre 07/Vieil Ourcival - Coffre 07",
  [59421210] = "@Vieil Ourcival - Coffre 08/Vieil Ourcival - Coffre 08/Vieil Ourcival - Coffre 08",
  [59421211] = "@Vieil Ourcival - Coffre 09/Vieil Ourcival - Coffre 09/Vieil Ourcival - Coffre 09",
  [59421212] = "@Vieil Ourcival - Coffre 10/Vieil Ourcival - Coffre 10/Vieil Ourcival - Coffre 10",
  [59421213] = "@Vieux Mont de l'Ours - Coffre 01/Vieux Mont de l'Ours - Coffre 01/Vieux Mont de l'Ours - Coffre 01",
  [59421214] = "@Vieux Mont de l'Ours - Coffre 02/Vieux Mont de l'Ours - Coffre 02/Vieux Mont de l'Ours - Coffre 02",
  [59421215] = "@Vieux Mont de l'Ours - Coffre 03/Vieux Mont de l'Ours - Coffre 03/Vieux Mont de l'Ours - Coffre 03",
  [59421216] = "@Vieux Mont de l'Ours - Coffre 04/Vieux Mont de l'Ours - Coffre 04/Vieux Mont de l'Ours - Coffre 04",
  [59421217] = "@Vieux Mont de l'Ours - Coffre 05/Vieux Mont de l'Ours - Coffre 05/Vieux Mont de l'Ours - Coffre 05",
  [59421218] = "@Coteau fleuri (rang B) - Coffre 01/Coteau fleuri (rang B) - Coffre 01/Coteau fleuri (rang B) - Coffre 01",
  [59421219] = "@Plaines Plinpot - Coffre 01/Plaines Plinpot - Coffre 01/Plaines Plinpot - Coffre 01",
  [59421220] = "@Plaines Plinpot - Coffre 02/Plaines Plinpot - Coffre 02/Plaines Plinpot - Coffre 02",
  [59421221] = "@Plaines Plinpot - Coffre 02/Plaines Plinpot - Coffre 02/Plaines Plinpot - Coffre 03",
  [59421222] = "@Plaines Plinpot - Coffre 04/Plaines Plinpot - Coffre 04/Plaines Plinpot - Coffre 04",
  [59421223] = "@Plaines Plinpot - Coffre 05/Plaines Plinpot - Coffre 05/Plaines Plinpot - Coffre 05",
  [59421224] = "@Plaines Plinpot - Coffre 06/Plaines Plinpot - Coffre 06/Plaines Plinpot - Coffre 06",
  [59421225] = "@Plaines Plinpot - Coffre 07/Plaines Plinpot - Coffre 07/Plaines Plinpot - Coffre 07",
  [59421226] = "@Plaines Plinpot - Coffre 08/Plaines Plinpot - Coffre 08/Plaines Plinpot - Coffre 08",
  [59421227] = "@Plaines Plinpot - Coffre 09/Plaines Plinpot - Coffre 09/Plaines Plinpot - Coffre 09",
  [59421228] = "@Plaines Plinpot - Coffre 10/Plaines Plinpot - Coffre 10/Plaines Plinpot - Coffre 10",
  [59421229] = "@Plaines Plinpot - Coffre 11/Plaines Plinpot - Coffre 11/Plaines Plinpot - Coffre 11",
  [59421230] = "@Zone des portails - Coffre 01/Zone des portails - Coffre 01/Zone des portails - Coffre 01",
  [59421231] = "@Zone des portails - Coffre 02/Zone des portails - Coffre 02/Zone des portails - Coffre 02",
  [59421232] = "@Zone des portails - Coffre 03/Zone des portails - Coffre 03/Zone des portails - Coffre 03",
  [59421233] = "@Zone des portails - Coffre 04/Zone des portails - Coffre 04/Zone des portails - Coffre 04",
  [59421234] = "@Zone des portails - Coffre 05/Zone des portails - Coffre 05/Zone des portails - Coffre 05",
  [59421235] = "@Zone des portails - Coffre 06/Zone des portails - Coffre 06/Zone des portails - Coffre 06",
  [59421236] = "@Zone des portails - Coffre 07/Zone des portails - Coffre 07/Zone des portails - Coffre 07",
  [59421237] = "@Zone des portails - Coffre 08/Zone des portails - Coffre 08/Zone des portails - Coffre 08",
  [59421238] = "@Zone des portails - Coffre 09/Zone des portails - Coffre 09/Zone des portails - Coffre 09",
  [59421239] = "@Zone des portails - Coffre 10/Zone des portails - Coffre 10/Zone des portails - Coffre 10",
  [59422300] = "@Tablo-blabla n°01 : Granpapéti/Tablo-blabla n°01 : Granpapéti/Tablo-blabla n°01 : Granpapéti",
  [59422301] = "@Tablo-blabla n°02 : Feulion/Tablo-blabla n°02 : Feulion/Tablo-blabla n°02 : Feulion",
  [59422302] = "@Tablo-blabla n°03 : Triptic-tac/Tablo-blabla n°03 : Triptic-tac/Tablo-blabla n°03 : Triptic-tac",
  [59422303] = "@Tablo-blabla n°04 : Robonyan/Tablo-blabla n°04 : Robonyan/Tablo-blabla n°04 : Robonyan",
  [59422304] = "@Tablo-blabla n°05 : Draconfus/Tablo-blabla n°05 : Draconfus/Tablo-blabla n°05 : Draconfus",
  [59422307] = "@Tablo-blabla n°08 : Ronimpec/Tablo-blabla n°08 : Ronimpec/Tablo-blabla n°08 : Ronimpec",
  [59422308] = "@Tablo-blabla n°09 : Sumochi/Tablo-blabla n°09 : Sumochi/Tablo-blabla n°09 : Sumochi",
  [59422310] = "@Tablo-blabla n°11 : Hiblusion/Tablo-blabla n°11 : Hiblusion/Tablo-blabla n°11 : Hiblusion",
  [59422311] = "@Tablo-blabla n°12 : Maître Oden/Tablo-blabla n°12 : Maître Oden/Tablo-blabla n°12 : Maître Oden",
  [59422312] = "@Tablo-blabla n°13 : Cupistol/Tablo-blabla n°13 : Cupistol/Tablo-blabla n°13 : Cupistol",
  [59422313] = "@Tablo-blabla n°14 : Cigalopin/Tablo-blabla n°14 : Cigalopin/Tablo-blabla n°14 : Cigalopin",
  [59422314] = "@Tablo-blabla n°15 : Chiperpiou/Tablo-blabla n°15 : Chiperpiou/Tablo-blabla n°15 : Chiperpiou",
  [59422315] = "@Tablo-blabla n°16 : Grégrigry/Tablo-blabla n°16 : Grégrigry/Tablo-blabla n°16 : Grégrigry",
  [59422316] = "@Tablo-blabla n°17 : Chaipô/Tablo-blabla n°17 : Chaipô/Tablo-blabla n°17 : Chaipô",
  [59422317] = "@Tablo-blabla n°18 : Croquin/Tablo-blabla n°18 : Croquin/Tablo-blabla n°18 : Croquin",
  [59422318] = "@Tablo-blabla n°19 : Supernoël/Tablo-blabla n°19 : Supernoël/Tablo-blabla n°19 : Supernoël",
  [59422319] = "@Tablo-blabla n°20 : Noripop/Tablo-blabla n°20 : Noripop/Tablo-blabla n°20 : Noripop",
  [59422320] = "@Tablo-blabla n°21 : Wakapoeira/Tablo-blabla n°21 : Wakapoeira/Tablo-blabla n°21 : Wakapoeira",
  [59422321] = "@Tablo-blabla n°22 : Salsalga/Tablo-blabla n°22 : Salsalga/Tablo-blabla n°22 : Salsalga",
  [59422450] = "@Yo-criminels/Yo-criminels/Yo-criminels : 1 capture",
  [59422451] = "@Yo-criminels/Yo-criminels/Yo-criminels : 5 captures",
  [59422452] = "@Yo-criminels/Yo-criminels/Yo-criminels : 10 captures",
  [59422453] = "@Yo-criminels/Yo-criminels/Yo-criminels : 20 captures",
  [59422454] = "@Yo-criminels/Yo-criminels/Yo-criminels : 30 captures",
  [59422700] = "@Requête : Pas le temps de pêcher !/Requête : Pas le temps de pêcher !/Objet-clé : Canne à pêche",
  [59422702] = "@Objet-clé : Pile ou passe/Objet-clé : Pile ou passe/Objet-clé : Pile ou passe",
  [59422703] = "@Objet-clé : Clés de l'école/Objet-clé : Clés de l'école/Objet-clé : Clés de l'école",
  [59422704] = "@Objet-clé : Herbe ancestrale/Objet-clé : Herbe ancestrale/Objet-clé : Herbe ancestrale",
  [59422705] = "@Objet-clé : Super tournevis/Objet-clé : Super tournevis/Objet-clé : Super tournevis",
  [59422707] = "@Objet-clé : Modèle zéro/Objet-clé : Modèle zéro/Objet-clé : Modèle zéro",
  [59422713] = "@Objet-clé : Clé de derrière/Objet-clé : Clé de derrière/Objet-clé : Clé de derrière",
  [59422714] = "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Objet-clé : Filet à insectes",
  [59422715] = "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Objet-clé : Indications de Maman",
  [59422716] = "@Objet-clé : Clé magnétique or/Objet-clé : Clé magnétique or/Objet-clé : Clé magnétique or",
  [59422717] = "@Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 03/Objet-clé : Clé salle du trésor",
  [59422720] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Objet-clé : Poignée étrange",
  [59423001] = "@Objet-clé : Vélo/Objet-clé : Vélo/Objet-clé : Vélo",
  [59423002] = "@Boss : Didgeai/Boss : Didgeai/Boss : Didgeai",
  [59423003] = "@Boss : Sabroclair/Boss : Sabroclair/Boss : Sabroclair",
  [59423004] = "@Boss : Ombraptor/Boss : Ombraptor/Boss : Ombraptor",
  [59423005] = "@Boss : Inamygal/Boss : Inamygal/Boss : Inamygal",
  [59423006] = "@Boss : Volteface/Boss : Volteface/Boss : Volteface",
  [59423007] = "@Boss : Misterre/Boss : Misterre/Boss : Misterre",
  [59423008] = "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Boss : Firmain",
  [59423009] = "@Boss : Démophage/Boss : Démophage/Boss : Démophage",
  [59423010] = "@Boss : Injustin/Boss : Injustin/Boss : Injustin",
  [59423011] = "@Boss : Fielippine/Boss : Fielippine/Boss : Fielippine",
  [59423012] = "@Boss : Cyrustre/Boss : Cyrustre/Boss : Cyrustre",
  [59423013] = "@Boss : Maudicko/Boss : Maudicko/Boss : Maudicko",
  [59423014] = "@Boss : Ronéan/Boss : Ronéan/Boss : Ronéan",
  [59423015] = "@Tablo-blabla n°08 : Ronimpec/Tablo-blabla n°08 : Ronimpec/Boss : Crocho",
  [59423016] = "@Boss : Tromplœil/Boss : Tromplœil/Boss : Tromplœil",
}
AP_CHAPTER_LOCATIONS = {
  [59420000] = 1,
  [59420001] = 2,
  [59420002] = 3,
  [59420003] = 4,
  [59420004] = 5,
  [59420005] = 6,
  [59420006] = 7,
  [59420007] = 8,
  [59420008] = 9,
  [59420009] = 10,
  [59420010] = 11,
}
AP_ALL_SECTIONS = {
  "@Allée sinistre - Coffre 01/Allée sinistre - Coffre 01/Allée sinistre - Coffre 01",
  "@Boss : Barbefrousse/Boss : Barbefrousse/Boss : Barbefrousse",
  "@Boss : Cyrustre/Boss : Cyrustre/Boss : Cyrustre",
  "@Boss : Didgeai/Boss : Didgeai/Boss : Didgeai",
  "@Boss : Démophage/Boss : Démophage/Boss : Démophage",
  "@Boss : Fielippine/Boss : Fielippine/Boss : Fielippine",
  "@Boss : Grolos/Boss : Grolos/Boss : Grolos",
  "@Boss : Inamygal/Boss : Inamygal/Boss : Inamygal",
  "@Boss : Injustin/Boss : Injustin/Boss : Injustin",
  "@Boss : Lady Démona/Boss : Lady Démona/Boss : Lady Démona",
  "@Boss : Lady Démona/Boss : Lady Démona/Boss : Lady Perpétua",
  "@Boss : Laure/Boss : Laure/Boss : Laure",
  "@Boss : Laure/Boss : Laure/Boss : Marge",
  "@Boss : Maudicko/Boss : Maudicko/Boss : Maudicko",
  "@Boss : Misterre/Boss : Misterre/Boss : Misterre",
  "@Boss : Méganyan/Boss : Méganyan/Boss : Méganyan",
  "@Boss : Ombraptor/Boss : Ombraptor/Boss : Ombraptor",
  "@Boss : Ronéan/Boss : Ronéan/Boss : Ronéan",
  "@Boss : Sabroclair/Boss : Sabroclair/Boss : Sabroclair",
  "@Boss : Tourbœillon/Boss : Tourbœillon/Boss : Tourbœillon",
  "@Boss : Tromplœil/Boss : Tromplœil/Boss : Tromplœil",
  "@Boss : Volteface/Boss : Volteface/Boss : Volteface",
  "@Centre-ville de Granval (sous-zone) - Coffre 01/Centre-ville de Granval (sous-zone) - Coffre 01/Centre-ville de Granval (sous-zone) - Coffre 01",
  "@Centre-ville de Granval - Coffre 01/Centre-ville de Granval - Coffre 01/Centre-ville de Granval - Coffre 01",
  "@Centre-ville de Granval - Coffre 02/Centre-ville de Granval - Coffre 02/Centre-ville de Granval - Coffre 02",
  "@Centre-ville de Granval - Coffre 03/Centre-ville de Granval - Coffre 03/Centre-ville de Granval - Coffre 03",
  "@Centre-ville de Granval - Coffre 04/Centre-ville de Granval - Coffre 04/Centre-ville de Granval - Coffre 04",
  "@Centre-ville de Granval - Coffre 05/Centre-ville de Granval - Coffre 05/Centre-ville de Granval - Coffre 05",
  "@Centre-ville de Granval - Coffre 06/Centre-ville de Granval - Coffre 06/Centre-ville de Granval - Coffre 06",
  "@Centre-ville de Granval - Coffre 07/Centre-ville de Granval - Coffre 07/Centre-ville de Granval - Coffre 07",
  "@Centre-ville de Granval - Coffre 08/Centre-ville de Granval - Coffre 08/Centre-ville de Granval - Coffre 08",
  "@Chapitres/Chapitres/Chapitre 1 : La montre disparue",
  "@Chapitres/Chapitres/Chapitre 10 : Retour à la normale !",
  "@Chapitres/Chapitres/Chapitre 11 : Danger au vieux Granval !",
  "@Chapitres/Chapitres/Chapitre 2 : Cache-cache high-tech",
  "@Chapitres/Chapitres/Chapitre 3 : L'étrange école",
  "@Chapitres/Chapitres/Chapitre 4 : En route pour Ourcival !",
  "@Chapitres/Chapitres/Chapitre 5 : Retour 60 ans en arrière !",
  "@Chapitres/Chapitres/Chapitre 6 : Yo-kai Watch Modèle Zéro",
  "@Chapitres/Chapitres/Chapitre 7 : La tempête arrive !",
  "@Chapitres/Chapitres/Chapitre 8 : La grande bataille Yo-kai",
  "@Chapitres/Chapitres/Chapitre 9 : Maître Nyada : le défi",
  "@Chemin du Puits - Coffre 01/Chemin du Puits - Coffre 01/Chemin du Puits - Coffre 01",
  "@Chemin du Sanctuaire du Renard - Coffre 01/Chemin du Sanctuaire du Renard - Coffre 01/Chemin du Sanctuaire du Renard - Coffre 01",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Boss : Firmain",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 02",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 03",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 04",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 05",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 06",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 07",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 08",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 09",
  "@Clinique du Crépuscule - Coffre 01/Clinique du Crépuscule - Coffre 01/Objet-clé : Poignée étrange",
  "@Corniche (Maison des Roch) - Coffre 01/Corniche (Maison des Roch) - Coffre 01/Corniche (Maison des Roch) - Coffre 01",
  "@Corniche (Musée) - Coffre 01/Corniche (Musée) - Coffre 01/Corniche (Musée) - Coffre 01",
  "@Corniche (Musée) - Coffre 02/Corniche (Musée) - Coffre 02/Corniche (Musée) - Coffre 02",
  "@Corniche (Musée) - Coffre 03/Corniche (Musée) - Coffre 03/Corniche (Musée) - Coffre 03",
  "@Corniche (Musée) - Coffre 04/Corniche (Musée) - Coffre 04/Corniche (Musée) - Coffre 04",
  "@Corniche (Musée) - Coffre 05/Corniche (Musée) - Coffre 05/Corniche (Musée) - Coffre 05",
  "@Corniche (Musée) - Coffre 06/Corniche (Musée) - Coffre 06/Corniche (Musée) - Coffre 06",
  "@Corniche (Musée) - Coffre 07/Corniche (Musée) - Coffre 07/Corniche (Musée) - Coffre 07",
  "@Corniche (Musée) - Coffre 08/Corniche (Musée) - Coffre 08/Corniche (Musée) - Coffre 08",
  "@Corniche (Méga toboggan) - Coffre 01/Corniche (Méga toboggan) - Coffre 01/Corniche (Méga toboggan) - Coffre 01",
  "@Corniche (Méga toboggan) - Coffre 02/Corniche (Méga toboggan) - Coffre 02/Corniche (Méga toboggan) - Coffre 02",
  "@Corniche (Méga toboggan) - Coffre 03/Corniche (Méga toboggan) - Coffre 03/Corniche (Méga toboggan) - Coffre 03",
  "@Corniche - Coffre 01/Corniche - Coffre 01/Corniche - Coffre 01",
  "@Corniche - Coffre 02/Corniche - Coffre 02/Corniche - Coffre 02",
  "@Corniche - Coffre 03/Corniche - Coffre 03/Corniche - Coffre 03",
  "@Corniche - Coffre 04/Corniche - Coffre 04/Corniche - Coffre 04",
  "@Corniche - Coffre 05/Corniche - Coffre 05/Corniche - Coffre 05",
  "@Corniche - Coffre 06/Corniche - Coffre 06/Corniche - Coffre 06",
  "@Coteau fleuri (présent) - Coffre 01/Coteau fleuri (présent) - Coffre 01/Coteau fleuri (présent) - Coffre 01",
  "@Coteau fleuri (présent) - Coffre 01/Coteau fleuri (présent) - Coffre 01/Coteau fleuri (rang C) - Coffre 02",
  "@Coteau fleuri (rang B) - Coffre 01/Coteau fleuri (rang B) - Coffre 01/Coteau fleuri (rang B) - Coffre 01",
  "@Coteau fleuri (rang C) - Coffre 01/Coteau fleuri (rang C) - Coffre 01/Coteau fleuri (rang C) - Coffre 01",
  "@Coteau fleuri - Coffre 01/Coteau fleuri - Coffre 01/Coteau fleuri - Coffre 01",
  "@Coteau fleuri - Coffre 02/Coteau fleuri - Coffre 02/Coteau fleuri - Coffre 02",
  "@Coteau fleuri - Coffre 03/Coteau fleuri - Coffre 03/Coteau fleuri - Coffre 03",
  "@Coteau fleuri - Coffre 04/Coteau fleuri - Coffre 04/Coteau fleuri - Coffre 04",
  "@Coteau fleuri - Coffre 05/Coteau fleuri - Coffre 05/Coteau fleuri - Coffre 05",
  "@Coteau fleuri - Coffre 06/Coteau fleuri - Coffre 06/Coteau fleuri - Coffre 06",
  "@Coteau fleuri - Coffre 07/Coteau fleuri - Coffre 07/Coteau fleuri - Coffre 07",
  "@Granval (Quartier des boutiques) - Coffre 01/Granval (Quartier des boutiques) - Coffre 01/Granval (Quartier des boutiques) - Coffre 01",
  "@Granval (Quartier des boutiques) - Coffre 02/Granval (Quartier des boutiques) - Coffre 02/Granval (Quartier des boutiques) - Coffre 02",
  "@Granval (Quartier des boutiques) - Coffre 03/Granval (Quartier des boutiques) - Coffre 03/Granval (Quartier des boutiques) - Coffre 03",
  "@Granval (Quartier des boutiques) - Coffre 04/Granval (Quartier des boutiques) - Coffre 04/Granval (Quartier des boutiques) - Coffre 04",
  "@Granval (Quartier des boutiques) - Coffre 05/Granval (Quartier des boutiques) - Coffre 05/Granval (Quartier des boutiques) - Coffre 05",
  "@Granval (Quartier des boutiques) - Coffre 06/Granval (Quartier des boutiques) - Coffre 06/Granval (Quartier des boutiques) - Coffre 06",
  "@Grotte du littoral - Coffre 01/Grotte du littoral - Coffre 01/Grotte du littoral - Coffre 01",
  "@Grotte du littoral - Coffre 02/Grotte du littoral - Coffre 02/Grotte du littoral - Coffre 02",
  "@Grotte du littoral - Coffre 03/Grotte du littoral - Coffre 03/Grotte du littoral - Coffre 03",
  "@Grotte du littoral - Coffre 04/Grotte du littoral - Coffre 04/Grotte du littoral - Coffre 04",
  "@Grotte du littoral - Coffre 05/Grotte du littoral - Coffre 05/Grotte du littoral - Coffre 05",
  "@Grotte du littoral - Coffre 06/Grotte du littoral - Coffre 06/Grotte du littoral - Coffre 06",
  "@Grotte du littoral - Coffre 07/Grotte du littoral - Coffre 07/Grotte du littoral - Coffre 07",
  "@Grotte du littoral - Coffre 08/Grotte du littoral - Coffre 08/Grotte du littoral - Coffre 08",
  "@Grotte du littoral - Coffre 09/Grotte du littoral - Coffre 09/Grotte du littoral - Coffre 09",
  "@Lac des Coloquintes (passé) - Coffre 01/Lac des Coloquintes (passé) - Coffre 01/Lac des Coloquintes (passé) - Coffre 01",
  "@Les Hauts de Granval (Passage des matous) - Coffre 01/Les Hauts de Granval (Passage des matous) - Coffre 01/Les Hauts de Granval (Passage des matous) - Coffre 01",
  "@Les Hauts de Granval - Coffre 01/Les Hauts de Granval - Coffre 01/Les Hauts de Granval - Coffre 01",
  "@Les Hauts de Granval - Coffre 02/Les Hauts de Granval - Coffre 02/Les Hauts de Granval - Coffre 02",
  "@Les Hauts de Granval - Coffre 03/Les Hauts de Granval - Coffre 03/Les Hauts de Granval - Coffre 03",
  "@Les Hauts de Granval - Coffre 04/Les Hauts de Granval - Coffre 04/Les Hauts de Granval - Coffre 04",
  "@Les Hauts de Granval - Coffre 05/Les Hauts de Granval - Coffre 05/Les Hauts de Granval - Coffre 05",
  "@Les Hauts de Granval - Coffre 06/Les Hauts de Granval - Coffre 06/Les Hauts de Granval - Coffre 06",
  "@Les Hauts de Granval - Coffre 07/Les Hauts de Granval - Coffre 07/Les Hauts de Granval - Coffre 07",
  "@Les Hauts de Granval - Coffre 08/Les Hauts de Granval - Coffre 08/Les Hauts de Granval - Coffre 08",
  "@Les Hauts de Granval - Coffre 09/Les Hauts de Granval - Coffre 09/Les Hauts de Granval - Coffre 09",
  "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10",
  "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Objet-clé : Filet à insectes",
  "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Objet-clé : Indications de Maman",
  "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Requête : La faim justifie le moyen",
  "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Requête : Le secret de Jibanyan",
  "@Les Hauts de Granval - Coffre 10/Les Hauts de Granval - Coffre 10/Requête : Sur les traces de Papa",
  "@Manoir (Coteau fleuri) - Coffre 01/Manoir (Coteau fleuri) - Coffre 01/Manoir (Coteau fleuri) - Coffre 01",
  "@Manoir (Coteau fleuri) - Coffre 02/Manoir (Coteau fleuri) - Coffre 02/Manoir (Coteau fleuri) - Coffre 02",
  "@Manoir (Coteau fleuri) - Coffre 03/Manoir (Coteau fleuri) - Coffre 03/Manoir (Coteau fleuri) - Coffre 03",
  "@Manoir (Coteau fleuri) - Coffre 04/Manoir (Coteau fleuri) - Coffre 04/Manoir (Coteau fleuri) - Coffre 04",
  "@Manoir (Coteau fleuri) - Coffre 05/Manoir (Coteau fleuri) - Coffre 05/Manoir (Coteau fleuri) - Coffre 05",
  "@Manoir (Coteau fleuri) - Coffre 06/Manoir (Coteau fleuri) - Coffre 06/Manoir (Coteau fleuri) - Coffre 06",
  "@Manoir arrière (Coteau fleuri) - Coffre 01/Manoir arrière (Coteau fleuri) - Coffre 01/Manoir arrière (Coteau fleuri) - Coffre 01",
  "@Manoir arrière (Coteau fleuri) - Coffre 02/Manoir arrière (Coteau fleuri) - Coffre 02/Manoir arrière (Coteau fleuri) - Coffre 02",
  "@Manoir arrière (Coteau fleuri) - Coffre 03/Manoir arrière (Coteau fleuri) - Coffre 03/Manoir arrière (Coteau fleuri) - Coffre 03",
  "@Manoir arrière (Coteau fleuri) - Coffre 04/Manoir arrière (Coteau fleuri) - Coffre 04/Manoir arrière (Coteau fleuri) - Coffre 04",
  "@Manoir arrière (Coteau fleuri) - Coffre 05/Manoir arrière (Coteau fleuri) - Coffre 05/Manoir arrière (Coteau fleuri) - Coffre 05",
  "@Mont Sylvestre (accès égouts) - Coffre 01/Mont Sylvestre (accès égouts) - Coffre 01/Mont Sylvestre (accès égouts) - Coffre 01",
  "@Mont Sylvestre (accès égouts) - Coffre 01/Mont Sylvestre (accès égouts) - Coffre 01/Mont Sylvestre (accès égouts) - Coffre 02",
  "@Mont Sylvestre - Coffre 01/Mont Sylvestre - Coffre 01/Mont Sylvestre - Coffre 01",
  "@Mont de l'Ours (présent) - Coffre 01/Mont de l'Ours (présent) - Coffre 01/Mont de l'Ours (présent) - Coffre 01",
  "@Objet-clé : Clé de derrière/Objet-clé : Clé de derrière/Objet-clé : Clé de derrière",
  "@Objet-clé : Clé magnétique or/Objet-clé : Clé magnétique or/Objet-clé : Clé magnétique or",
  "@Objet-clé : Clés de l'école/Objet-clé : Clés de l'école/Objet-clé : Clés de l'école",
  "@Objet-clé : Herbe ancestrale/Objet-clé : Herbe ancestrale/Objet-clé : Herbe ancestrale",
  "@Objet-clé : Modèle zéro/Objet-clé : Modèle zéro/Objet-clé : Modèle zéro",
  "@Objet-clé : Pile ou passe/Objet-clé : Pile ou passe/Objet-clé : Pile ou passe",
  "@Objet-clé : Super tournevis/Objet-clé : Super tournevis/Objet-clé : Super tournevis",
  "@Objet-clé : Vélo/Objet-clé : Vélo/Objet-clé : Vélo",
  "@Obtenons le rang C !/Obtenons le rang C !/Montée de rang : A",
  "@Obtenons le rang C !/Obtenons le rang C !/Montée de rang : B",
  "@Obtenons le rang C !/Obtenons le rang C !/Montée de rang : C",
  "@Obtenons le rang C !/Obtenons le rang C !/Montée de rang : D",
  "@Obtenons le rang C !/Obtenons le rang C !/Montée de rang : S",
  "@Obtenons le rang C !/Obtenons le rang C !/Obtenons le rang A !",
  "@Obtenons le rang C !/Obtenons le rang C !/Obtenons le rang B !",
  "@Obtenons le rang C !/Obtenons le rang C !/Obtenons le rang C !",
  "@Obtenons le rang C !/Obtenons le rang C !/Obtenons le rang S !",
  "@Ourcival (Canyon de la cigale) - Coffre 01/Ourcival (Canyon de la cigale) - Coffre 01/Ourcival (Canyon de la cigale) - Coffre 01",
  "@Ourcival (Canyon de la cigale) - Coffre 02/Ourcival (Canyon de la cigale) - Coffre 02/Ourcival (Canyon de la cigale) - Coffre 02",
  "@Ourcival (Canyon de la cigale) - Coffre 03/Ourcival (Canyon de la cigale) - Coffre 03/Ourcival (Canyon de la cigale) - Coffre 03",
  "@Ourcival (Rochers de face) - Coffre 01/Ourcival (Rochers de face) - Coffre 01/Ourcival (Rochers de face) - Coffre 01",
  "@Ourcival (Rochers de face) - Coffre 02/Ourcival (Rochers de face) - Coffre 02/Ourcival (Rochers de face) - Coffre 02",
  "@Ourcival (Rochers de face) - Coffre 03/Ourcival (Rochers de face) - Coffre 03/Ourcival (Rochers de face) - Coffre 03",
  "@Ourcival - Coffre 01/Ourcival - Coffre 01/Ourcival - Coffre 01",
  "@Ourcival - Coffre 02/Ourcival - Coffre 02/Ourcival - Coffre 02",
  "@Ourcival - Coffre 03/Ourcival - Coffre 03/Ourcival - Coffre 03",
  "@Ourcival - Coffre 04/Ourcival - Coffre 04/Ourcival - Coffre 04",
  "@Ourcival - Coffre 05/Ourcival - Coffre 05/Ourcival - Coffre 05",
  "@Ourcival - Coffre 06/Ourcival - Coffre 06/Ourcival - Coffre 06",
  "@Ourcival - Coffre 07/Ourcival - Coffre 07/Ourcival - Coffre 07",
  "@Ourcival - Coffre 08/Ourcival - Coffre 08/Ourcival - Coffre 08",
  "@Ourcival - Coffre 09/Ourcival - Coffre 09/Ourcival - Coffre 09",
  "@Ourcival - Coffre 10/Ourcival - Coffre 10/Ourcival - Coffre 10",
  "@Ourcival - Coffre 11/Ourcival - Coffre 11/Ourcival - Coffre 11",
  "@Ourcival - Coffre 12/Ourcival - Coffre 12/Ourcival - Coffre 12",
  "@Parvis de la gare d'Ourcival - Coffre 01/Parvis de la gare d'Ourcival - Coffre 01/Parvis de la gare d'Ourcival - Coffre 01",
  "@Parvis de la gare d'Ourcival - Coffre 02/Parvis de la gare d'Ourcival - Coffre 02/Parvis de la gare d'Ourcival - Coffre 02",
  "@Parvis de la gare d'Ourcival - Coffre 03/Parvis de la gare d'Ourcival - Coffre 03/Parvis de la gare d'Ourcival - Coffre 03",
  "@Parvis de la gare d'Ourcival - Coffre 04/Parvis de la gare d'Ourcival - Coffre 04/Parvis de la gare d'Ourcival - Coffre 04",
  "@Parvis de la gare d'Ourcival - Coffre 05/Parvis de la gare d'Ourcival - Coffre 05/Parvis de la gare d'Ourcival - Coffre 05",
  "@Plaines Plinpot - Coffre 01/Plaines Plinpot - Coffre 01/Plaines Plinpot - Coffre 01",
  "@Plaines Plinpot - Coffre 02/Plaines Plinpot - Coffre 02/Plaines Plinpot - Coffre 02",
  "@Plaines Plinpot - Coffre 02/Plaines Plinpot - Coffre 02/Plaines Plinpot - Coffre 03",
  "@Plaines Plinpot - Coffre 04/Plaines Plinpot - Coffre 04/Plaines Plinpot - Coffre 04",
  "@Plaines Plinpot - Coffre 05/Plaines Plinpot - Coffre 05/Plaines Plinpot - Coffre 05",
  "@Plaines Plinpot - Coffre 06/Plaines Plinpot - Coffre 06/Plaines Plinpot - Coffre 06",
  "@Plaines Plinpot - Coffre 07/Plaines Plinpot - Coffre 07/Plaines Plinpot - Coffre 07",
  "@Plaines Plinpot - Coffre 08/Plaines Plinpot - Coffre 08/Plaines Plinpot - Coffre 08",
  "@Plaines Plinpot - Coffre 09/Plaines Plinpot - Coffre 09/Plaines Plinpot - Coffre 09",
  "@Plaines Plinpot - Coffre 10/Plaines Plinpot - Coffre 10/Plaines Plinpot - Coffre 10",
  "@Plaines Plinpot - Coffre 11/Plaines Plinpot - Coffre 11/Plaines Plinpot - Coffre 11",
  "@Quartier des boutiques (appartement C-303) - Coffre 01/Quartier des boutiques (appartement C-303) - Coffre 01/Quartier des boutiques (appartement C-303) - Coffre 01",
  "@Requête : Agonigiri a des soucis/Requête : Agonigiri a des soucis/Requête : Agonigiri a des soucis",
  "@Requête : Bam boum ! Fusion !/Requête : Bam boum ! Fusion !/Requête : Bam boum ! Fusion !",
  "@Requête : Blues du déménagement/Requête : Blues du déménagement/Requête : Blues du déménagement",
  "@Requête : C-1 Grand Prix A/Requête : C-1 Grand Prix A/Requête : C-1 Grand Prix A",
  "@Requête : C-1 Grand Prix/Requête : C-1 Grand Prix/Requête : C-1 Grand Prix",
  "@Requête : Chasse nocturne/Requête : Chasse nocturne/Requête : Chasse nocturne",
  "@Requête : Coup de bluff/Requête : Coup de bluff/Requête : Coup de bluff",
  "@Requête : Courage, Max !/Requête : Courage, Max !/Requête : Chasseurs de trésors 1",
  "@Requête : Courage, Max !/Requête : Courage, Max !/Requête : Chasseurs de trésors 2",
  "@Requête : Courage, Max !/Requête : Courage, Max !/Requête : Chasseurs de trésors 3",
  "@Requête : Courage, Max !/Requête : Courage, Max !/Requête : Courage, Max !",
  "@Requête : Ectoplasmes à l'école/Requête : Ectoplasmes à l'école/Requête : Ectoplasmes à l'école",
  "@Requête : Ectoplasmes à l'école/Requête : Ectoplasmes à l'école/Requête : Oden de l'âme 1",
  "@Requête : Ectoplasmes à l'école/Requête : Ectoplasmes à l'école/Requête : Oden de l'âme 2",
  "@Requête : Ectoplasmes à l'école/Requête : Ectoplasmes à l'école/Requête : Oden de l'âme 3",
  "@Requête : Je veux grandir/Requête : Je veux grandir/Requête : Je veux grandir",
  "@Requête : La base secrète/Requête : La base secrète/Requête : La base secrète",
  "@Requête : La clinique hantée/Requête : La clinique hantée/Requête : La clinique hantée",
  "@Requête : La star de Granval 1/Requête : La star de Granval 1/Requête : La star de Granval 1",
  "@Requête : La star de Granval 2/Requête : La star de Granval 2/Requête : La star de Granval 2",
  "@Requête : Le meilleur scarabée/Requête : Le meilleur scarabée/Requête : Le meilleur scarabée",
  "@Requête : Le prix du fer/Requête : Le prix du fer/Requête : Le prix du fer",
  "@Requête : Les portails mystère/Requête : Les portails mystère/Requête : Jouets d'antan",
  "@Requête : Les portails mystère/Requête : Les portails mystère/Requête : Le portail final",
  "@Requête : Les portails mystère/Requête : Les portails mystère/Requête : Les portails mystère",
  "@Requête : Les portails mystère/Requête : Les portails mystère/Requête : Musée en détresse",
  "@Requête : Les portails mystère/Requête : Les portails mystère/Requête : Une armure sinistre",
  "@Requête : Les sources de l'amitié/Requête : Les sources de l'amitié/Requête : Les sources de l'amitié",
  "@Requête : Méga cache-cache/Requête : Méga cache-cache/Requête : Méga cache-cache",
  "@Requête : Nouveau look/Requête : Nouveau look/Requête : Nouveau look",
  "@Requête : Officiellement officiel !/Requête : Officiellement officiel !/Requête : Officiellement officiel !",
  "@Requête : Pas le temps de pêcher !/Requête : Pas le temps de pêcher !/Objet-clé : Canne à pêche",
  "@Requête : Pas le temps de pêcher !/Requête : Pas le temps de pêcher !/Requête : Pas le temps de pêcher !",
  "@Requête : Pas le temps de pêcher !/Requête : Pas le temps de pêcher !/Requête : Trouvons Faux Kappa !",
  "@Requête : Pièce Au Phil du temps/Requête : Pièce Au Phil du temps/Requête : Pièce Au Phil du temps",
  "@Requête : Pièce ferronnerie/Requête : Pièce ferronnerie/Requête : Pièce ferronnerie",
  "@Requête : Pièce sanctuaire/Requête : Pièce sanctuaire/Requête : Pièce sanctuaire",
  "@Requête : Prix de Gastronomie/Requête : Prix de Gastronomie/Requête : Prix de Gastronomie",
  "@Requête : Querelles gourmandes/Requête : Querelles gourmandes/Requête : Querelles gourmandes",
  "@Requête : Qui est cette fille/Requête : Qui est cette fille/Requête : Qui est cette fille",
  "@Requête : Secrets de l'Âmechimie/Requête : Secrets de l'Âmechimie/Requête : Secrets de l'Âmechimie",
  "@Requête : Soirée chaotique/Requête : Soirée chaotique/Requête : Soirée chaotique",
  "@Requête : Spécialiste des cigales/Requête : Spécialiste des cigales/Requête : La reine des cigales",
  "@Requête : Spécialiste des cigales/Requête : Spécialiste des cigales/Requête : Spécialiste des cigales",
  "@Requête : Super Balaise : l'origine/Requête : Super Balaise : l'origine/Requête : Super Balaise : l'origine",
  "@Requête : Super Balaise : l'origine/Requête : Super Balaise : l'origine/Requête : Super Balaise : le retour",
  "@Requête : Super cache-cache/Requête : Super cache-cache/Requête : Super cache-cache",
  "@Requête : Tous à bord/Requête : Tous à bord/Requête : Tous à bord",
  "@Requête : Tout droit sorti du futur !/Requête : Tout droit sorti du futur !/Requête : Tout droit sorti du futur !",
  "@Requête : Triangle amoureux/Requête : Triangle amoureux/Requête : Triangle amoureux",
  "@Requête : Trouvons Lulutin !/Requête : Trouvons Lulutin !/Requête : Trouvons Lulutin !",
  "@Requête : Trouvons Métaureaulog !/Requête : Trouvons Métaureaulog !/Requête : Trouvons Métaureaulog !",
  "@Requête : Trouvons Parasolal !/Requête : Trouvons Parasolal !/Requête : Trouvons Parasolal !",
  "@Requête : Trouvons Sirénée !/Requête : Trouvons Sirénée !/Requête : Trouvons Sirénée !",
  "@Requête : Un amour perdu/Requête : Un amour perdu/Requête : Un amour perdu",
  "@Requête : Un look trop sophistiqué/Requête : Un look trop sophistiqué/Requête : Un look trop sophistiqué",
  "@Requête : Un super fan-club/Requête : Un super fan-club/Requête : Un super fan-club",
  "@Requête : Virée en mer !/Requête : Virée en mer !/Requête : Virée en mer !",
  "@Requête : Votre mascotte locale/Requête : Votre mascotte locale/Requête : Votre mascotte locale",
  "@Requête : Voyage de l'envoûtement/Requête : Voyage de l'envoûtement/Requête : Voyage de l'envoûtement",
  "@Requête : Vrai cache-cache/Requête : Vrai cache-cache/Requête : Vrai cache-cache",
  "@Requête : Ça attire les clients !/Requête : Ça attire les clients !/Requête : Ça attire les clients !",
  "@Requête : Épreuves de Nyada IV/Requête : Épreuves de Nyada IV/Requête : Épreuves de Nyada IV",
  "@Requête : Épreuves de Nyada V/Requête : Épreuves de Nyada V/Requête : Épreuves de Nyada V",
  "@Requête : Épreuves de Nyada VI/Requête : Épreuves de Nyada VI/Requête : Épreuves de Nyada VI",
  "@Ruelle obscure - Coffre 01/Ruelle obscure - Coffre 01/Canal isolé - Coffre 01",
  "@Ruelle obscure - Coffre 01/Ruelle obscure - Coffre 01/Canal isolé - Coffre 02",
  "@Ruelle obscure - Coffre 01/Ruelle obscure - Coffre 01/Ruelle obscure - Coffre 01",
  "@San Fantastico (rang C) - Coffre 01/San Fantastico (rang C) - Coffre 01/San Fantastico (rang C) - Coffre 01",
  "@San Fantastico - Coffre 01/San Fantastico - Coffre 01/San Fantastico - Coffre 01",
  "@San Fantastico - Coffre 02/San Fantastico - Coffre 02/San Fantastico - Coffre 02",
  "@San Fantastico - Coffre 03/San Fantastico - Coffre 03/San Fantastico - Coffre 03",
  "@San Fantastico - Coffre 04/San Fantastico - Coffre 04/San Fantastico - Coffre 04",
  "@San Fantastico - Coffre 05/San Fantastico - Coffre 05/San Fantastico - Coffre 05",
  "@San Fantastico - Coffre 06/San Fantastico - Coffre 06/San Fantastico - Coffre 06",
  "@San Fantastico - Coffre 07/San Fantastico - Coffre 07/San Fantastico - Coffre 07",
  "@San Fantastico - Coffre 08/San Fantastico - Coffre 08/San Fantastico - Coffre 08",
  "@San Fantastico - Coffre 09/San Fantastico - Coffre 09/San Fantastico - Coffre 09",
  "@San Fantastico - Coffre 10/San Fantastico - Coffre 10/San Fantastico - Coffre 10",
  "@San Fantastico - Coffre 11/San Fantastico - Coffre 11/San Fantastico - Coffre 11",
  "@San Fantastico - Coffre 12/San Fantastico - Coffre 12/San Fantastico - Coffre 12",
  "@San Fantastico - Coffre 13/San Fantastico - Coffre 13/San Fantastico - Coffre 13",
  "@San Fantastico - Coffre 14/San Fantastico - Coffre 14/San Fantastico - Coffre 14",
  "@San Fantastico - Coffre 15/San Fantastico - Coffre 15/San Fantastico - Coffre 15",
  "@San Fantastico - Coffre 16/San Fantastico - Coffre 16/San Fantastico - Coffre 16",
  "@Sentier de randonnée - Coffre 01/Sentier de randonnée - Coffre 01/Sentier de randonnée - Coffre 01",
  "@Service : Coup de foudre/Service : Coup de foudre/Service : Coup de foudre",
  "@Service : Espiègleries/Service : Espiègleries/Service : Espiègleries",
  "@Service : La malade imaginaire/Service : La malade imaginaire/Service : La malade imaginaire",
  "@Service : Le ventre vide/Service : Le ventre vide/Service : Le ventre vide",
  "@Service : Que de balivernes/Service : Que de balivernes/Service : Que de balivernes",
  "@Service : Sous un soleil de plomb/Service : Sous un soleil de plomb/Service : Sous un soleil de plomb",
  "@Service : Un entraînement de star/Service : Un entraînement de star/Service : Un entraînement de star",
  "@Service : Un matou en détresse/Service : Un matou en détresse/Service : Un matou en détresse",
  "@Service : Une envie de bonbons/Service : Une envie de bonbons/Service : Une envie de bonbons",
  "@Service : À la chasse aux insectes !/Service : À la chasse aux insectes !/Service : À la chasse aux insectes !",
  "@Sommet du Mont Sylvestre - Coffre 01/Sommet du Mont Sylvestre - Coffre 01/Sommet du Mont Sylvestre - Coffre 01",
  "@Tablo-blabla n°01 : Granpapéti/Tablo-blabla n°01 : Granpapéti/Tablo-blabla n°01 : Granpapéti",
  "@Tablo-blabla n°02 : Feulion/Tablo-blabla n°02 : Feulion/Tablo-blabla n°02 : Feulion",
  "@Tablo-blabla n°03 : Triptic-tac/Tablo-blabla n°03 : Triptic-tac/Tablo-blabla n°03 : Triptic-tac",
  "@Tablo-blabla n°04 : Robonyan/Tablo-blabla n°04 : Robonyan/Tablo-blabla n°04 : Robonyan",
  "@Tablo-blabla n°05 : Draconfus/Tablo-blabla n°05 : Draconfus/Tablo-blabla n°05 : Draconfus",
  "@Tablo-blabla n°08 : Ronimpec/Tablo-blabla n°08 : Ronimpec/Boss : Crocho",
  "@Tablo-blabla n°08 : Ronimpec/Tablo-blabla n°08 : Ronimpec/Tablo-blabla n°08 : Ronimpec",
  "@Tablo-blabla n°09 : Sumochi/Tablo-blabla n°09 : Sumochi/Tablo-blabla n°09 : Sumochi",
  "@Tablo-blabla n°11 : Hiblusion/Tablo-blabla n°11 : Hiblusion/Tablo-blabla n°11 : Hiblusion",
  "@Tablo-blabla n°12 : Maître Oden/Tablo-blabla n°12 : Maître Oden/Tablo-blabla n°12 : Maître Oden",
  "@Tablo-blabla n°13 : Cupistol/Tablo-blabla n°13 : Cupistol/Tablo-blabla n°13 : Cupistol",
  "@Tablo-blabla n°14 : Cigalopin/Tablo-blabla n°14 : Cigalopin/Tablo-blabla n°14 : Cigalopin",
  "@Tablo-blabla n°15 : Chiperpiou/Tablo-blabla n°15 : Chiperpiou/Tablo-blabla n°15 : Chiperpiou",
  "@Tablo-blabla n°16 : Grégrigry/Tablo-blabla n°16 : Grégrigry/Tablo-blabla n°16 : Grégrigry",
  "@Tablo-blabla n°17 : Chaipô/Tablo-blabla n°17 : Chaipô/Tablo-blabla n°17 : Chaipô",
  "@Tablo-blabla n°18 : Croquin/Tablo-blabla n°18 : Croquin/Tablo-blabla n°18 : Croquin",
  "@Tablo-blabla n°19 : Supernoël/Tablo-blabla n°19 : Supernoël/Tablo-blabla n°19 : Supernoël",
  "@Tablo-blabla n°20 : Noripop/Tablo-blabla n°20 : Noripop/Tablo-blabla n°20 : Noripop",
  "@Tablo-blabla n°21 : Wakapoeira/Tablo-blabla n°21 : Wakapoeira/Tablo-blabla n°21 : Wakapoeira",
  "@Tablo-blabla n°22 : Salsalga/Tablo-blabla n°22 : Salsalga/Tablo-blabla n°22 : Salsalga",
  "@Tour Excellence - Coffre 01/Tour Excellence - Coffre 01/Tour Excellence - Coffre 01",
  "@Tour Excellence - Coffre 02/Tour Excellence - Coffre 02/Tour Excellence - Coffre 02",
  "@Tour Excellence - Coffre 03/Tour Excellence - Coffre 03/Tour Excellence - Coffre 03",
  "@Tour Excellence - Coffre 04/Tour Excellence - Coffre 04/Tour Excellence - Coffre 04",
  "@Tour Excellence - Coffre 05/Tour Excellence - Coffre 05/Tour Excellence - Coffre 05",
  "@Tour Excellence - Coffre 05/Tour Excellence - Coffre 05/Tour Excellence - Coffre 06",
  "@Tour du commerce (12e étage) - Coffre 01/Tour du commerce (12e étage) - Coffre 01/Tour du commerce (12e étage) - Coffre 01",
  "@Tour du commerce (12e étage) - Coffre 02/Tour du commerce (12e étage) - Coffre 02/Tour du commerce (12e étage) - Coffre 02",
  "@Tour du commerce (12e étage) - Coffre 03/Tour du commerce (12e étage) - Coffre 03/Tour du commerce (12e étage) - Coffre 03",
  "@Tour du commerce (3e étage) - Coffre 01/Tour du commerce (3e étage) - Coffre 01/Tour du commerce (3e étage) - Coffre 01",
  "@Tour du commerce (3e étage) - Coffre 02/Tour du commerce (3e étage) - Coffre 02/Tour du commerce (3e étage) - Coffre 02",
  "@Tour du commerce (3e étage) - Coffre 03/Tour du commerce (3e étage) - Coffre 03/Tour du commerce (3e étage) - Coffre 03",
  "@Tour du commerce (3e étage, rang A) - Coffre 01/Tour du commerce (3e étage, rang A) - Coffre 01/Tour du commerce (3e étage, rang A) - Coffre 01",
  "@Tunnel abandonné (salle du trésor) - Coffre 01/Tunnel abandonné (salle du trésor) - Coffre 01/Tunnel abandonné (salle du trésor) - Coffre 01",
  "@Tunnel abandonné (salle du trésor) - Coffre 02/Tunnel abandonné (salle du trésor) - Coffre 02/Tunnel abandonné (salle du trésor) - Coffre 02",
  "@Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 03/Objet-clé : Clé salle du trésor",
  "@Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 03",
  "@Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 04",
  "@Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 03/Tunnel abandonné (salle du trésor) - Coffre 05",
  "@Tunnel abandonné (salle du trésor) - Coffre 06/Tunnel abandonné (salle du trésor) - Coffre 06/Tunnel abandonné (salle du trésor) - Coffre 06",
  "@Tunnel abandonné (salle du trésor) - Coffre 07/Tunnel abandonné (salle du trésor) - Coffre 07/Tunnel abandonné (salle du trésor) - Coffre 07",
  "@Tunnel abandonné (salle du trésor) - Coffre 08/Tunnel abandonné (salle du trésor) - Coffre 08/Tunnel abandonné (salle du trésor) - Coffre 08",
  "@Tunnel abandonné est - Coffre 01/Tunnel abandonné est - Coffre 01/Tunnel abandonné est - Coffre 01",
  "@Tunnel abandonné est - Coffre 02/Tunnel abandonné est - Coffre 02/Tunnel abandonné est - Coffre 02",
  "@Tunnel abandonné est - Coffre 03/Tunnel abandonné est - Coffre 03/Tunnel abandonné est - Coffre 03",
  "@Tunnel abandonné est - Coffre 04/Tunnel abandonné est - Coffre 04/Tunnel abandonné est - Coffre 04",
  "@Tunnel abandonné est - Coffre 05/Tunnel abandonné est - Coffre 05/Tunnel abandonné est - Coffre 05",
  "@Tunnel abandonné est - Coffre 06/Tunnel abandonné est - Coffre 06/Tunnel abandonné est - Coffre 06",
  "@Vieil Ourcival - Coffre 01/Vieil Ourcival - Coffre 01/Vieil Ourcival - Coffre 01",
  "@Vieil Ourcival - Coffre 02/Vieil Ourcival - Coffre 02/Vieil Ourcival - Coffre 02",
  "@Vieil Ourcival - Coffre 03/Vieil Ourcival - Coffre 03/Vieil Ourcival - Coffre 03",
  "@Vieil Ourcival - Coffre 04/Vieil Ourcival - Coffre 04/Vieil Ourcival - Coffre 04",
  "@Vieil Ourcival - Coffre 05/Vieil Ourcival - Coffre 05/Vieil Ourcival - Coffre 05",
  "@Vieil Ourcival - Coffre 06/Vieil Ourcival - Coffre 06/Vieil Ourcival - Coffre 06",
  "@Vieil Ourcival - Coffre 07/Vieil Ourcival - Coffre 07/Vieil Ourcival - Coffre 07",
  "@Vieil Ourcival - Coffre 08/Vieil Ourcival - Coffre 08/Vieil Ourcival - Coffre 08",
  "@Vieil Ourcival - Coffre 09/Vieil Ourcival - Coffre 09/Vieil Ourcival - Coffre 09",
  "@Vieil Ourcival - Coffre 10/Vieil Ourcival - Coffre 10/Vieil Ourcival - Coffre 10",
  "@Vieille Ferronnerie de Granval - Coffre 01/Vieille Ferronnerie de Granval - Coffre 01/Vieille Ferronnerie de Granval - Coffre 01",
  "@Vieille Ferronnerie de Granval - Coffre 02/Vieille Ferronnerie de Granval - Coffre 02/Vieille Ferronnerie de Granval - Coffre 02",
  "@Vieux Coteau Fleuri - Coffre 01/Vieux Coteau Fleuri - Coffre 01/Vieux Coteau Fleuri - Coffre 01",
  "@Vieux Coteau Fleuri - Coffre 02/Vieux Coteau Fleuri - Coffre 02/Vieux Coteau Fleuri - Coffre 02",
  "@Vieux Coteau Fleuri - Coffre 03/Vieux Coteau Fleuri - Coffre 03/Vieux Coteau Fleuri - Coffre 03",
  "@Vieux Coteau Fleuri - Coffre 04/Vieux Coteau Fleuri - Coffre 04/Vieux Coteau Fleuri - Coffre 04",
  "@Vieux Hauts de Granval (retour Ch10) - Coffre 01/Vieux Hauts de Granval (retour Ch10) - Coffre 01/Vieux Hauts de Granval (retour Ch10) - Coffre 01",
  "@Vieux Hauts de Granval - Coffre 01/Vieux Hauts de Granval - Coffre 01/Vieux Hauts de Granval - Coffre 01",
  "@Vieux Hauts de Granval - Coffre 02/Vieux Hauts de Granval - Coffre 02/Vieux Hauts de Granval - Coffre 02",
  "@Vieux Hauts de Granval - Coffre 03/Vieux Hauts de Granval - Coffre 03/Vieux Hauts de Granval - Coffre 03",
  "@Vieux Hauts de Granval - Coffre 04/Vieux Hauts de Granval - Coffre 04/Vieux Hauts de Granval - Coffre 04",
  "@Vieux Hauts de Granval - Coffre 05/Vieux Hauts de Granval - Coffre 05/Vieux Hauts de Granval - Coffre 05",
  "@Vieux Mont Sylvestre - Coffre 01/Vieux Mont Sylvestre - Coffre 01/Vieux Mont Sylvestre - Coffre 01",
  "@Vieux Mont de l'Ours - Coffre 01/Vieux Mont de l'Ours - Coffre 01/Vieux Mont de l'Ours - Coffre 01",
  "@Vieux Mont de l'Ours - Coffre 02/Vieux Mont de l'Ours - Coffre 02/Vieux Mont de l'Ours - Coffre 02",
  "@Vieux Mont de l'Ours - Coffre 03/Vieux Mont de l'Ours - Coffre 03/Vieux Mont de l'Ours - Coffre 03",
  "@Vieux Mont de l'Ours - Coffre 04/Vieux Mont de l'Ours - Coffre 04/Vieux Mont de l'Ours - Coffre 04",
  "@Vieux Mont de l'Ours - Coffre 05/Vieux Mont de l'Ours - Coffre 05/Vieux Mont de l'Ours - Coffre 05",
  "@Yo-criminels/Yo-criminels/Yo-criminels : 1 capture",
  "@Yo-criminels/Yo-criminels/Yo-criminels : 10 captures",
  "@Yo-criminels/Yo-criminels/Yo-criminels : 20 captures",
  "@Yo-criminels/Yo-criminels/Yo-criminels : 30 captures",
  "@Yo-criminels/Yo-criminels/Yo-criminels : 5 captures",
  "@Zone des portails - Coffre 01/Zone des portails - Coffre 01/Zone des portails - Coffre 01",
  "@Zone des portails - Coffre 02/Zone des portails - Coffre 02/Zone des portails - Coffre 02",
  "@Zone des portails - Coffre 03/Zone des portails - Coffre 03/Zone des portails - Coffre 03",
  "@Zone des portails - Coffre 04/Zone des portails - Coffre 04/Zone des portails - Coffre 04",
  "@Zone des portails - Coffre 05/Zone des portails - Coffre 05/Zone des portails - Coffre 05",
  "@Zone des portails - Coffre 06/Zone des portails - Coffre 06/Zone des portails - Coffre 06",
  "@Zone des portails - Coffre 07/Zone des portails - Coffre 07/Zone des portails - Coffre 07",
  "@Zone des portails - Coffre 08/Zone des portails - Coffre 08/Zone des portails - Coffre 08",
  "@Zone des portails - Coffre 09/Zone des portails - Coffre 09/Zone des portails - Coffre 09",
  "@Zone des portails - Coffre 10/Zone des portails - Coffre 10/Zone des portails - Coffre 10",
  "@École élémentaire de Granval (nuit) - Coffre 01/École élémentaire de Granval (nuit) - Coffre 01/École élémentaire de Granval (nuit) - Coffre 01",
  "@École élémentaire de Granval (nuit) - Coffre 02/École élémentaire de Granval (nuit) - Coffre 02/École élémentaire de Granval (nuit) - Coffre 02",
  "@École élémentaire de Granval (nuit) - Coffre 03/École élémentaire de Granval (nuit) - Coffre 03/École élémentaire de Granval (nuit) - Coffre 03",
  "@École élémentaire de Granval (nuit) - Coffre 04/École élémentaire de Granval (nuit) - Coffre 04/École élémentaire de Granval (nuit) - Coffre 04",
  "@École élémentaire de Granval (nuit) - Coffre 05/École élémentaire de Granval (nuit) - Coffre 05/École élémentaire de Granval (nuit) - Coffre 05",
  "@École élémentaire de Granval (nuit) - Coffre 06/École élémentaire de Granval (nuit) - Coffre 06/École élémentaire de Granval (nuit) - Coffre 06",
  "@École élémentaire de Granval (nuit) - Coffre 07/École élémentaire de Granval (nuit) - Coffre 07/École élémentaire de Granval (nuit) - Coffre 07",
  "@École élémentaire de Granval (nuit) - Coffre 08/École élémentaire de Granval (nuit) - Coffre 08/École élémentaire de Granval (nuit) - Coffre 08",
  "@École élémentaire de Granval (nuit) - Coffre 09/École élémentaire de Granval (nuit) - Coffre 09/École élémentaire de Granval (nuit) - Coffre 09",
  "@École élémentaire de Granval (nuit) - Coffre 10/École élémentaire de Granval (nuit) - Coffre 10/École élémentaire de Granval (nuit) - Coffre 10",
  "@École élémentaire de Granval (nuit) - Coffre 11/École élémentaire de Granval (nuit) - Coffre 11/École élémentaire de Granval (nuit) - Coffre 11",
  "@École élémentaire de Granval (nuit) - Coffre 12/École élémentaire de Granval (nuit) - Coffre 12/École élémentaire de Granval (nuit) - Coffre 12",
  "@École élémentaire de Granval (nuit) - Coffre 13/École élémentaire de Granval (nuit) - Coffre 13/École élémentaire de Granval (nuit) - Coffre 13",
  "@Égouts - Coffre 01/Égouts - Coffre 01/Égouts - Coffre 01",
  "@Égouts - Coffre 02/Égouts - Coffre 02/Égouts - Coffre 02",
  "@Égouts - Coffre 03/Égouts - Coffre 03/Égouts - Coffre 03",
  "@Égouts - Coffre 04/Égouts - Coffre 04/Égouts - Coffre 04",
  "@Égouts - Coffre 05/Égouts - Coffre 05/Égouts - Coffre 05",
  "@Égouts - Coffre 06/Égouts - Coffre 06/Égouts - Coffre 06",
  "@Égouts - Coffre 07/Égouts - Coffre 07/Égouts - Coffre 07",
  "@Égouts - Coffre 08/Égouts - Coffre 08/Égouts - Coffre 08",
  "@Égouts - Coffre 09/Égouts - Coffre 09/Égouts - Coffre 09",
  "@Égouts - Coffre 10/Égouts - Coffre 10/Égouts - Coffre 10",
  "@Égouts - Coffre 11/Égouts - Coffre 11/Égouts - Coffre 11",
  "@Égouts - Coffre 12/Égouts - Coffre 12/Égouts - Coffre 12",
  "@Égouts - Coffre 13/Égouts - Coffre 13/Égouts - Coffre 13",
}